### ISSUE TITLE
Default values for `labels` when loading files.

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#1003]
**Describe the bug**
The default values for `labels` when loading files has additional metadata labels that aren't part of the default pysat standard any longer.

The consequence of this is, with a default Instrument, if a user writes a file, then loads that file back into a pysat.Instrument, there will be additional metadata labels the user never provided. It isn't actively harmful but consistency is good.

**To Reproduce**
1. Create a pysat.Instrument, no messing with `labels` input.
2. Load data
3. Create file, `pysat.utils.io.inst_to_netcdf(inst, ....)
4. Load file, `data, meta = pysat.utils.io.load_netcdf( ... )5. 
5. Look at meta labels as loaded, compare against meta labels in steps 1, 2.6. 

**Expected behavior**
Consistent defaults across packages. The additional labels used to be part of the pysat standard, pre-standardization ;P

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version [e.g. 22]: Python 3.9
 - Other details about your setup that could be relevant

**Additional context**
See pull #983 for first identification.

**Comment by jklenzing** [comment]
loaded file adds 'plot_label', 'axis', 'scale'
