### ISSUE TITLE
BUG: xarray and `multi_file_day` and data padding.

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#1005]
**Describe the bug**
Checks on the time index aren't consistent across pandas and xarray. Things work for pandas, they don't for xarray.

**To Reproduce**
1. `gold = pysat.Instrument("ses14", "gold", "nmax")`
2. `gold.multi_file_day = True`
3. `gold.load(2020, 1)`

```
File ~/Code/pysat/pysat/_instrument.py:2935, in Instrument.load(self, yr, doy, end_yr, end_doy, date, end_date, fname, stop_fname, verifyPad, use_header, **kwargs)
   2933     self._prev_data.sort_index(inplace=True)
   2934 if not self._index(self._curr_data).is_monotonic_increasing:
-> 2935     self._curr_data.sort_index(inplace=True)
   2936 if not self._index(self._next_data).is_monotonic_increasing:
   2937     self._next_data.sort_index(inplace=True)

AttributeError: 'Dataset' object has no attribute 'sort_index'

```

The error is on `_curr_data` and not `_prev_data` since there is no data for `_prev_data`

**Expected behavior**
Gold data goes past date boundaries. Trying to clean that up with existing pysat features. Lack of testing got us here :(

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version [e.g. 22] Python 3.9
 - Other details about your setup that could be relevant

**Additional context**
🐬

**Comment by rstoneback** [comment]
This is only a problem if the times aren't monotonic.

**Comment by rstoneback** [comment]
Short term fix, put in type check and put I correct code for xarray.

**Comment by jklenzing** [comment]
xarray.Dataset does not have the `sort_index` method.  It needs `data.sortby('time')`

**Comment by jklenzing** [comment]
I've got a fix in the queue, but testing is going to be a nightmare.  We currently do not test for a non-monotonic index in the padding tests.  Adding the `malformed_index` kwarg into the tests currently has 12 broken tests, 6 passing tests per class.
