### ISSUE TITLE
TST: add an option to simulate CI options for inherited tests

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#1042]
**Is your feature request related to a problem? Please describe.**
Since unit tests are inherited in other packages (eg, pysatSpaceWeather), sometimes options that are only run in a CI environment are not tests until release.

**Describe the solution you'd like**
A kwarg in the tests that simulates a `True` response when checking for CI environment locally.

**Describe alternatives you've considered**
- The code can be manually altered, which works but requires a code alteration each time
- Set up workflows on other packages to check against a release candidate before the final RC is approved

**Additional context**
Found in pysat/pysatSpaceWeather#85

- [x] pysatCDAAC -- https://github.com/pysat/pysatCDAAC/pull/38
- [x] pysatCDF -- https://github.com/pysat/pysatCDF/pull/39
- [x] pysatMadrigal -- https://github.com/pysat/pysatMadrigal/pull/75
- [x] pysatMissions -- https://github.com/pysat/pysatMissions/pull/101
- [x] pysatModels -- https://github.com/pysat/pysatModels/pull/122
- [x] pysatNASA -- https://github.com/pysat/pysatNASA/pull/131
- [x] pysatSeasons -- https://github.com/pysat/pysatSeasons/pull/36
- [x] pysatSpaceWeather -- https://github.com/pysat/pysatSpaceWeather/pull/97

**Comment by rstoneback** [comment]
Must be spread around. checklists!
