### ISSUE TITLE
BUG: pandas 1.5.0 change in children

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#1044]
**Describe the bug**
metadata operations have changed when pandas 1.5.0 is used.  Previously, `children` was set to `None` if the higher order data was not used.  With pandas 1.5.0, it is set to `NaN`.  This make the code assume that any new metadata is a higher-order variable, sending it to loops that won't work.

**To Reproduce**
- Load a pandas instrument.
- Inspect the metadata for any 1d variable

**Expected behavior**
Code should be consistent.  Need to check for `None` or `NaN` to trigger the loop.

**Screenshots**
This is the broken bit:
https://github.com/pysat/pysat/blob/1e98fe5dc507d493ab50073e4a158f5c79cef7da/pysat/_meta.py#L484-L487

**Desktop (please complete the following information):**
All throughout the GA environments.

**Additional context**
First seen in pysatSpaceWeather

**Comment by jklenzing** [comment]
NOTE: other errors may lurk beneath...

**Comment by jklenzing** [comment]
After playing with some potential fixes, I think the error is deeper down.  The default value for 'children' is no longer set as None when adding new metadata.  After discussions with @aburrell, I think this happens on the pysat side.

**Comment by rstoneback** [comment]
Children is NaN instead of None. Our checks are set up for None.

**Comment by rstoneback** [comment]
Here's pysat code in _meta.py
```
                meta_row = self.data.loc[new_key]  # .copy()
                if new_key in self.keys_nD():
                    meta_row.at['children'] = self.ho_data[new_key]  # .copy()
                else:
                    print('Setting to None')
                    meta_row.at['children'] = None  # Return empty meta instance
```
 This is what pops out
```
In [8]: meta['f107']
Setting to None
Out[8]: 
units                                                  SFU
long_name                             F10.7 cm solar index
notes                                                     
desc         F10.7 cm radio flux in Solar Flux Units (SFU)
value_min                                              0.0
value_max                                              inf
fill                                                   NaN
children                                               NaN
Name: f107, dtype: object
```

pandas takes our None and makes it NaN.

**Comment by aburrell** [comment]
Yes, this is what @jklenzing identified.  The issue is now we need to change the evaluations to allow detection of both `None` and `NaN` everywhere, or do something more clever in the class to allow both to pass.

**Comment by rstoneback** [comment]
> Yes, this is what @jklenzing identified. 

It wasn't fully clear.

> The issue is now we need to change the evaluations to allow detection of both `None` and `NaN` everywhere, or do something more clever in the class to allow both to pass.

If we can assign into the frame as an object type column, rather than a float type column, we should get the None back.

**Comment by jklenzing** [comment]
Instead of checking for false, we could check for True.  ie
```
import pysat
inst = pysat.Instrument('pysat', 'testing2d')
inst.load(2009, 3)

isinstance(inst.meta['profiles']['children'], type(pysat.Meta()))
```

**Comment by rstoneback** [comment]
I believe this is complete with the 3.0.5 release
