### ISSUE TITLE
ENH: data version check

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#1049]
**Is your feature request related to a problem? Please describe.**
Sometimes a user may have older versions of data that may not adhere to current standards.  This could either stem from not updating data, or dates which are no longer supported.

**Describe the solution you'd like**
A check upon load if the version of a given file matches the most recent version (as determined from the file list).  If the version is old, a warning pops up suggesting that the user check for updated files or the data PI on usage of older files.

**Describe alternatives you've considered**
:otter:

**Additional context**
See discussion at https://github.com/pysat/pysatNASA/issues/123

**Comment by aburrell** [comment]
One potential issue with this solution is that not all files are going to have version numbers.  This will work for pysatNASA, but not other repositories.
