### ISSUE TITLE
DEP: setup.py deprecated by pip

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#1051]
**Is your feature request related to a problem? Please describe.**
From the unit tests at pysatCDAAC:
```
 DEPRECATION: pysat is being installed using the legacy 'setup.py install' method, because it does not have a 
'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change.
```

**Describe the solution you'd like**
pyproject.toml

**Describe alternatives you've considered**
🎡 

**Projects to update**
- [x] pysat -- #1134 
- [x] pysatCDAAC -- pysat/pysatCDAAC#39
- [x] pysatCDF
- [x] pysatMadrigal
- [x] pysatMissions -- https://github.com/pysat/pysatMissions/pull/99
- [x] pysatModels
- [x] pysatNASA -- pysat/pysatNASA#129
- [x] pysatSeasons
- [x] pysatSpaceWeather
- [x] template package

**Comment by rstoneback** [comment]
![image](https://user-images.githubusercontent.com/3595641/197888000-76603123-433f-4a92-9473-8e1eaeac2564.png)

**Comment by jklenzing** [comment]
I'm very close to a functional version of pysatNASA using pyproject.toml. Two problems left to solve:
- NEP 29 compliance
- pysatCDF install

I may may try on another package first to simplify dependencies

**Comment by jklenzing** [comment]
Sample version up at https://github.com/pysat/pysatCDAAC/pull/39

**Comment by jklenzing** [comment]
From the test cases so far, I've been able to consolidate metadata / settings info from 5 files to 2.

**Comment by jklenzing** [comment]
Dropping open pulls down to drafts until we can discuss at the next meeting.   Comments/questions are welcome.  Currently researching background more.

**Comment by jklenzing** [comment]
Notes from discussion today:
- use setup.cfg instead of tox.ini
- maintain setup.py for backward compatibility
- research parsers for readthedocs integration

**Comment by jklenzing** [comment]
pip 23.1 has been released and is wreaking havoc in the tests.  This issue should be accelerated.

**Comment by jklenzing** [comment]
Some things that are relevant to our build processes for pip 23.1.0 (Released 4-15-2023).  From https://pip.pypa.io/en/stable/news/

`--no-binary` does not imply setup.py install anymore. Instead a wheel will be built locally and installed. 

`--no-binary` does not disable the cache of locally built wheels anymore. It only means “don’t download wheels”. 

Remove setup.py install fallback when building a wheel failed for projects without pyproject.toml. 

When the wheel package is not installed, pip now uses the default build backend instead of setup.py install and setup.py develop for project without pyproject.toml.

**Comment by jklenzing** [comment]
TODO: open issues at remaining packages, close this one.

**Comment by jklenzing** [comment]
Issues added to remaining packages.
