### ISSUE TITLE
BUG: meta children warning can be thrown incorrectly for series input

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#1055]
**Describe the bug**
pysat mistakenly warns users about higher-order meta deprecations when users set new metadata.

**To Reproduce**
```
import warnings
import pysat
import pysatSpaceWeather
warnings.simplefilter('always')
inst = pysat.Instrument(inst_module=pysatSpaceWeather.instruments.sw_f107, tag='historic')
inst.load(2018, 3)
```
yields 
```
DeprecationWarning: Support for higher order metadata has been deprecated and will be removed in 3.2.0+.
```

**Expected behavior**
Inspecting the metadata reveals no children.  Should not be raised!

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Mac Monterrey
 - Python 3.8.11
 - develop branches of pysat and pysatSpaceWeather

**Additional context**
https://github.com/pysat/pysat/blob/bb62a4dd44fcc493b576fa90263eb0ee18265429/pysat/_meta.py#L478-L487

I think the warn statement needs to be moved into the if block.  Right now it's thrown always when a series is input as new meta, which can happen often.

It should look something like
```
if child is not None:
    # If there is data in the child object, assign it here
    self.ho_data[data_vars] = child
else:
    self._warn_meta_children()
```

**Comment by rstoneback** [comment]
Yeah, it shouldn't be thrown all the time, only when children is going to be assigned.
```
if child is not None:
    # If there is data in the child object, assign it here
    self._warn_meta_children()
    self.ho_data[data_vars] = child
```

**Comment by jklenzing** [comment]
NOTE to self: remove `else` statement
