### ISSUE TITLE
Data Access

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#1058]
**Describe the bug**
The data access examples includes slicing by datetime and by name. This works in pandas, but not xarray.

**To Reproduce**
```
inst = pysat.Instrument("pysat", "testing")
inst.load(2009, 2)
inst[inst.index[0]:inst.index[10], 'uts':'slt']
```
works fine
```
                      uts        mlt        slt
Epoch                                          
2009-01-02 00:00:00   0.0  20.288660  20.371134
2009-01-02 00:00:01   1.0  20.292784  20.375258
2009-01-02 00:00:02   2.0  20.296907  20.379381
2009-01-02 00:00:03   3.0  20.301031  20.383505
2009-01-02 00:00:04   4.0  20.305155  20.387629
2009-01-02 00:00:05   5.0  20.309278  20.391753
2009-01-02 00:00:06   6.0  20.313402  20.395876
2009-01-02 00:00:07   7.0  20.317526  20.400000
2009-01-02 00:00:08   8.0  20.321649  20.404124
2009-01-02 00:00:09   9.0  20.325773  20.408247
2009-01-02 00:00:10  10.0  20.329897  20.412371
```

Same process with xarray does not work.
```
inst = pysat.Instrument("pysat", "testing_xarray")
inst.load(2019, 2)
inst[inst.index[0]:inst.index[10], 'uts':'slt']
```
does not work. neither does slicing by name.
```
TypeError: slice indices must be integers or None or have an __index__ method
```

**Expected behavior**
Data access examples should be consistent with functionality.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Python 3.10

**Additional context**
Either fix the docs, or fix the functionality.

**Comment by jklenzing** [comment]
I can run the above snippet using the test instrument in pandas, but not using other pandas instruments (e.g., missions_sgp4).  Not sure if the bug is here or there.

**Comment by rstoneback** [comment]
I don't see one.

**Comment by rstoneback** [comment]
> I don't see one.

I made things more confusing 🤷 

The example I note in the issue report is in the docstring for `__getitem__`.

**Comment by jklenzing** [comment]
OK. I caught those, but wasn't sure if I was missing something else.  The PR is ready for review in that case.
