### ISSUE TITLE
Add `__delitem__` to Meta and Instrument

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#1078]
**Is your feature request related to a problem? Please describe.**
Sometimes when reshaping data to be appropriate for pysat, it is necessary to delete old metadata.  It may also be desirable to delete data from a pysat Instrument

**Describe the solution you'd like**
Add the `__delitem__` method to the Instrument and Meta classes.

**Describe alternatives you've considered**
- Carrying around metadata for variables that have been renamed or removed. 
-  Not allowing the use of pysat load_netcdf when doing complicated Instrument loads.

**Additional context**
Found the issue when developing the DMSP SSUSI Instrument: https://github.com/pysat/pysatNASA/pull/147

**Comment by jklenzing** [comment]
Start with meta, then instrument can call this
