### ISSUE TITLE
DEP: deprecated `labels` kwarg

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#1104]
**Is your feature request related to a problem? Please describe.**
The `labels` kwarg was deprecated in the pysat 3.1.0 release, to be removed in the pysat 3.2.0 release.

**Describe the solution you'd like**
Remove support for `labels` in:

- [x] test_instrument.py
- [x] test_utils_io.py
- [x] io.py
- [x] _instrument.py

**Comment by jklenzing** [comment]
@aburrell, what is the correct way of using meta_kwargs? A number of tests elsewhere initialize with the labels kwarg

**Comment by aburrell** [comment]
```
inst = pysat.Instrument('pysat', 'testing', meta_kwargs={'labels': {'min_val': ('value_min', (int))}, 'header_data': {'PI': 'Jeff'}})
```

Basically `meta_kwargs` will take any/all of the meta keywords so we don't have to keep adding them to the Instrument, etcetera input.
