### ISSUE TITLE
STY: space after operator (E275)

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#1118]
**Is your feature request related to a problem? Please describe.**
`pycodestyle` 2.9.1 changes how E275 is checked. This creates an error where `if(~~~)` is used for lengthy evaluation statements so that the tab for a continued line is not 4 characters.  This style issue pops up 15 times in the code.

***EDIT:*** Looking over the rationale at `pycodestyle`, the intent looks like the whitespace should distinguish between a statement (if, assert, raise) and a function.

**Describe the solution you'd like**
Update syntax accordingly. For example:
```
if(not isinstance(self.file_format, str)
   or (self.file_format.find("{") < 0)
   or (self.file_format.find("}") < 0)):
```
becomes
```
cond1 = not isinstance(self.file_format, str)
cond2 = self.file_format.find("{") < 0
cond3 = self.file_format.find("}") < 0
if (cond1 or cond2 or cond3):
```
or potentially
```
if (any([not isinstance(self.file_format, str),
         (self.file_format.find("{") < 0),
         (self.file_format.find("}") < 0)]):
```
**Describe alternatives you've considered**
Ignore E275 and leave the code alone

**Additional context**
Discovered during #1116.  Set to ignore this rule there, but should be a larger discussion among developers on how to move forward.

**Comment by jklenzing** [comment]
It's fine like that.  But then the code run conditionally follows the same indentation level as the continued conditions.

**Comment by jklenzing** [comment]
> Looking at [rule E275](https://www.flake8rules.com/rules/E275.html), I'm not sure where the error is coming from here

I think it's just the missing whitespace

**Comment by jklenzing** [comment]
> It's fine like that. But then the code run conditionally follows the same indentation level as the continued conditions.

that sentence got away from me somewhere...

**Comment by jklenzing** [comment]
Found the cause: it appears to be an intentional change with `pycodestyle` as of version 2.9.0: https://github.com/PyCQA/pycodestyle/issues/1096

**Comment by jklenzing** [comment]
Pinging @aburrell, any thoughts on which option to pursue? I'm leaning toward using `any` and `all` to bump the indentation point over

**Comment by aburrell** [comment]
Ugg, I find the change annoying (probably because it's a change).  What's the execution time difference on them?

**Comment by jklenzing** [comment]
Running code snippets in `timeit`, tiny.

**Comment by aburrell** [comment]
I suppose using `any` and `all` is going to make the line breaks easier, so doing that is probably the least painful thing.
