### ISSUE TITLE
BUG: sphinx 7.0.0 and 'style'

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#1119]
**Describe the bug**
sphinx 7.0.0 gives an error in the workflow.

**To Reproduce**
Look through the logs

**Expected behavior**
docs should build?

**Screenshots**
```
Theme error:
An error happened in rendering the page analysis/pysatMissions.
Reason: UndefinedError("'style' is undefined")
Error: Process completed with exit code 2.
```

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version python 3.9

**Additional context**
found in all pull requests after release of 7.0.0.  A version cap fixes this for now.

Note that this is occurring throughout the ecosystem

**Comment by jklenzing** [comment]
Read the Docs currently using sphinx 5.3.0

**Comment by aburrell** [comment]
From recent RTD build: `Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)`

**Comment by jklenzing** [comment]
Adding a yml to manage readthedocs sorted this, I think because it updated the python version.  See https://github.com/pysat/pysatNASA/pull/168

**Comment by jklenzing** [comment]
> Adding a yml to manage readthedocs sorted this, I think because it updated the python version. See [pysat/pysatNASA#168](https://github.com/pysat/pysatNASA/pull/168)

Noting this is in reference to the build at RTD, not the GA tests
