### ISSUE TITLE
STY: pysat_testing and empty datasets

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#1120]
**Is your feature request related to a problem? Please describe.**
For options where pysat_testing is required to return empty data / metadata, it is generated then discarded.

**Describe the solution you'd like**
Checking before generation could speed up the code.

**Describe alternatives you've considered**
Acceptance.

**Additional context**
Brought up during #1115

**Comment by aburrell** [comment]
Specifically changing the logic on lines 188-193 of `pysat/instruments/pysat_testing.py` and PR #1116
