### ISSUE TITLE
Coordinate transformation support

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#114]
Collect the coordinate transformations in pysatMagVect, along with the transformations to be added by A. Burrell in utils.py, into a pysat.coords submodule. Include outside packages into pysat's setup.py and make them available from within pysat.coords, presuming they are pip installable.

**Comment by rstoneback** [comment]
pysat has seen some organization improvements that implies this coupling of MagVect and regular pysat should happen sooner than later.

**Comment by jklenzing** [comment]
Since the bits of this that are breaking changes have been incorporated already (methods reorg), moving the remainder to 2.1.0.

**Comment by jklenzing** [comment]
Link to #167.  What is the future of this issue with the reorganization?

**Comment by rstoneback** [comment]
Sure.
