### ISSUE TITLE
C/NOFS IVM Cleaning Routine

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#115]
C/NOFS IVM cleaning routine uses one level of cleanliness for all data, but reliability criteria for drifts is more stringent than density values.  We should update accordingly.

**Comment by jklenzing** [comment]
Proposed cleaning mechanism:
- Use a baseline for density measurements (based on rpaflag), replace more stringent parameters (such as drifts) with NaNs.
- Ion temperatures should require a O^+ fraction of 0.15 or higher, citing the Hairston paper.
- From my notes, drifts should be based on a combination of [O^+] and flag information.  In my old matlab routines, there is a 'dmpts' parameter in addition to the drift meter flag which I don't see in the pysat metadata.  It's likely my shorthand for something rather than an official name.
- I would also suggest dropping the drifts for 100% O^+.

**Comment by rstoneback** [comment]
We will keep it simple, different parameters for cleaning on drifts, lower threshold for density, temperature, and composition.

**Comment by aburrell** [comment]
I think it would be useful to look at the DEMETER studies for guidance on identifying useful conditions for CINDI drifts.

**Comment by jklenzing** [comment]
Updates:  Reading over the documentation, it looks like the above parameters are handled in the quality flags.  However, to close this issue, there should be a way to be more stringent on velocity (rpa flag of 0 only) whilst letting the density and other parameters use more flags (rpa flag 0 or 1).  

The simplest way to implement this is to just pass NaNs through for velocity values where the rpa flag is 1 on the 'clean' setting.  Does anyone see any issues with this?

**Comment by aburrell** [comment]
That's fine with me.  If I recall correction, I think that in 'dusty' velocities should be passed down to RPA flag of '3'.  Aren't the other parameters also good down to the RPA_flag=3?  Or am I remembering the IDM flag?

**Comment by jklenzing** [comment]
From the document on CDAWeb:

RPA Quality Flag
0.  High quality data. 
1.	High quality data except for the ram velocity Vx and the spacecraft sensor plane potential. These two values are suspect and should be used with caution.
2.	Not used.
3.	Good quality data. The RMS fitting error is large and/or |Vx|>1000 m/s. The data may have more noise than quality flag = 0 data. Use Vx with caution.
4.	Good quality data. The RMS fitting error may be large, leading to greater noise levels. The ram velocity Vx and the spacecraft sensor plane potential values are suspect and should not be used.
5.	Undetermined. This value will only be seen if the quality control algorithm has failed.
6.	Not used.
7.	Ion temperature, composition, velocity, or density values are out of acceptable range and are untrustworthy. Data values have been set to fill data. 
8.	Not used.
9.	Poor quality data. Do not use. 


DM Quality Flag
0.  High quality data.
1.	Not used.
2.	Not used.
3.	Good quality data. 
4.	Not used.
5.	The angle between the ram direction and the sun is between 35 and 48 indicating possible sun glint into the instrument. Use data with caution.
6.	Indicates Torquer Rod flag is set indicating that the torquer rods are firing within about 10 seconds of this time. Current and nearby drift data are suspect. 
7.	|Vy| > 1000 or |Vz| > 600 or DM ion density < 1000. As a result, the following geophysical quantities have been set to fill data:  Vy, Vy variance, Vz, Vz variance, DM density, and DM density variance. 
8.	DM telemetry word has hit the positive or negative limit. The data is bad.
9.	Poor quality data. Do not use.

**Comment by jklenzing** [comment]
Proposed changes:
clean
- rpa flag of 0 or 1 required for all
- rpa flag of 0 and dm flag of 0 for velocities


I need to think a little more about dusty vs dirty.  I think that the ones labeled 'should not be used' (eg, rpa>=4) should be reserved for no cleaning.

**Comment by jklenzing** [comment]
Proposed modifications based on document.  The rationale for using all DM flags on non-drift data is that density / composition / temperature is not dependent on the DM. 
![Screen Shot 2019-09-19 at 2 44 51 PM](https://user-images.githubusercontent.com/19592220/65271951-26d2d880-daec-11e9-99ed-b9e53ea79ccf.png)

**Comment by jklenzing** [comment]
Pinging @JonathonMSmith

**Comment by aburrell** [comment]
Proposed sounds good, though we should probably add my logic for identifying bad 0.0 velocities and places where Vx doesn't contribute to the 3D V

**Comment by jklenzing** [comment]
Closed with merge of #289.
