### ISSUE TITLE
MAINT: datetime deprecation

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#1186]
# Description
```
DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC)
```

## Test configuration
 - OS: All
 - Version: Python 3.12
 - Other details about your setup that could be relevant

**Comment by jklenzing** [comment]
Noting that `dt.UTC` was added in python 3.11. May need separate solutions for different versions.

**Comment by jklenzing** [comment]
`dt.timezone.utc` is backwards compatible with all supported versions
