### ISSUE TITLE
MAINT: Day.delta deprecation in pandas

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#1193]
# Description
From running the unit tests:
```
  /home/runner/work/pysat/pysat/pysat/_orbits.py:382: FutureWarning: Day.delta is deprecated and will be removed in a future version. Use pd.Timedelta(obj) instead
    step = dt.timedelta(seconds=step.delta.total_seconds())
```

## Potential impact

- FutureWarning, will probably take place with pandas 3.0 release (2024?)
- Needs to be replaced or version capped

## Potential solution(s)
Update to `pds.Timedelta` notation. Simply replacing this for `step.delta` breaks the code quite a bit. More research is needed.

# Alternatives
Rewrite this section.

**Comment by aburrell** [comment]
@JonathonMSmith is this addressed?
