### ISSUE TITLE
ENH/BUG: Update data directory structure

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#123]
See pull #118 

To close:
- [x] Need to address #309 
- [x] Update default directory template - platform/name/inst_id/tag
- [x] Need a method to translate from one directory structure to another (pysat 2 -> pysat 3)

**Comment by rstoneback** [comment]
See pull #143 which makes the download testing more stringent. This change now requires the list_files routine to actually return a list of files as part of download testing, thus typos in filenames will be caught. As I type this, there may still me a small window for sat_id, where the filename for one sat_id may actually correspond to a different sat_id. This potential loophole is closed if there is a new temporary directory for every instrument tested, which may already be the case. Check the test_instruments code.

**Comment by rstoneback** [comment]
I remember checking, and there is a single temporary directory. The small loop hole remains.

**Comment by rstoneback** [comment]
pinging @jklenzing as an FYI given he is working on this code, though not this issue.

**Comment by jklenzing** [comment]
Do we need to create a unique temporary directory for each instrument test?

**Comment by rstoneback** [comment]
That is the question!

We can leave as is, including the small window for file errors related to sat_id, or we go full on individual temp folders.

Pinging @aburrell to get full team input. It may be a bit of a pain to go full on temp folders. Risk/reward time.

Also, you can tell me to stop talking about this, but the amount of pysat work and discussion going on is awesome. Even when I’m behind seeing a bunch of github emails coming in makes me smile. Speaking of, I’m behind.

It is official. Pysat is becoming its own thing, bigger than any individual. :)

Cue a monty burns clip, ‘Excellent.....’

Cheers,
Russell

On Feb 21, 2019, at 12:06 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


Do we need to create a unique temporary directory for each instrument test?

**Comment by aburrell** [comment]
I say we close the loophole.  I think we'll run against this again at some point, and it would be good to have the confidence that our unit tests will catch our mistakes.

**Comment by rstoneback** [comment]
One potential easy fix is to include sat_id in the default directory naming structure. The downside is having to move files on current installations.

I’m not sure what my original reasoning was for leaving it off. There could be something I’m forgetting.

On Feb 21, 2019, at 3:56 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


I say we close the loophole. I think we'll run against this again at some point, and it would be good to have the confidence that our unit tests will catch our mistakes.

**Comment by jklenzing** [comment]
> One potential easy fix is to include sat_id in the default directory naming structure. The downside is having to move files on current installations.

Does this loophole only affect the temporary files created during testing, or all the files?

**Comment by rstoneback** [comment]
All files that have a sat_id.

**Comment by jklenzing** [comment]
Adding to agenda for next week's meeting.

**Comment by jklenzing** [comment]
Given the volume of data files GOLD is expected to produce and the likelihood we will fully use sat_id and tag here (and maybe a third thing to be determined), we should discuss the plan forward.  Adding to agenda.

Possibility: Instead of sat_id / tag  use  sat_id / level / product

**Comment by jklenzing** [comment]
For GOLD: Use sat_id for channel, tag for level, name for data product.

**Comment by rstoneback** [comment]
I just recently downloaded new JRO data and the file names were different than what we have in pysat. Tests are still passing.....

**Comment by aburrell** [comment]
@rstoneback is that good or bad? :-P

**Comment by rstoneback** [comment]
No bueno! Not sure why that wasn't caught.


I've repurposed tag in some places to be level but that only works since I only have one product. I've also broken things into multiple instruments. Conceivably I could pull them all together with another dimension. 

We currently have:
platform / name (instrument) / sat_id / tag
Proposal:
platform / name / sat_id / level / product

**Comment by jklenzing** [comment]
Since this and #183 change the directory structure, should they be moved to 3.0.0?

**Comment by rstoneback** [comment]
Yes, I agree this should be a 3.0

**Comment by jklenzing** [comment]
Adding a note that this affects ICON data with the current format used by ICON instruments.

**Comment by jklenzing** [comment]
Needs a method to clean up old directory structure to the new structure.  
- Run a file list on current directory. 
- Spawn new instrument name list
- create new directories
- move files
