### ISSUE TITLE
Streamline handling of instrument download tests in Travis CI.

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#156]
This is a followup on changes implemented in #143.  As of this pull request, instruments using FTP downloads are excluded from the main instrument download tests and run via `test_ftp_instruments.py`, which is not run on Travis CI due to FTP services being inconsistently run there.  This is working now, but it will become increasingly difficult to maintain as new instruments are added.  

We need to maintain a way to run these tests locally, while preventing testing errors due to the Travis CI environment.  Ideally, we can simplify the test_environment as part of this change to aid the addition of new instruments.

Proposed changes:
- Each instrument / tag / sat_id combination should have a `travis_dl_skip` keyword, defaulting to false, to allow some data products to be skipped in the Travis tests due to FTP services not being available. 
- Each run of `test_download_and_load` and `check_download` should check to see if the environment is Travis and if the `travis_dl_skip` flag is True.  If both are True, then the `raise skip.SkipTest` notation (as used in `test_sw.py`) should be implemented.
- The exclude list will be maintained for instruments which have not yet launched or do not yet have publicly available data (eg, ICON, SPORT).
- `new_instrument.rst` should be updated to read that HTTPS is the preferred method of download; however, the `travis_dl_skip` flag is available for datasets where FTP is the only option.
- The tests within `test_ftp_instruments.py` can be folded back into the main testing file, as the checks outlined above should fix the original problem.
- Ideally, a check for server being down should be implemented as outlined in #133.

**Comment by aburrell** [comment]
This is a good idea, I think adding a flag to the instrument would be the easiest way to make sure new instruments are tested appropriately since it reduces the amount of tasks that need to be performed when adding a new instrument.

**Comment by jklenzing** [comment]
Adding to this:  `list_remote_files` is currently untested.  It's trivial to add to the `test_instruments.py` routines (and passes for the cdaweb_methods), but this does not exist for all instruments.  Should we add to the list of changes, potentially with a check to see if this method exists for each instrument?

**Comment by rstoneback** [comment]
Thanks for bringing this up again. I sometimes forget how much of the discussion is in issues rather than pulls.

I generally like the plan, though I am confused by some details.
Is the exclude list maintained in a central place, or is the travis_dl_skip included in the instrument file?
How do we check for a server being down vs a failed download?

I think it is good to check for the presence of the list_remote… but a bit premature to error on it.
The madrigal methods one is super slow. It will really slow things down if we include it in testing.
How many instruments are missing the list_remote_files method?

Cheers,
Russell



On Feb 22, 2019, at 1:47 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


Adding to this: list_remote_files is currently untested. It's trivial to add to the test_instruments.py routines (and passes for the cdaweb_methods), but this does not exist for all instruments. Should we add to the list of changes, potentially with a check to see if this method exists for each instrument?

**Comment by aburrell** [comment]
Several of the instruments don't have this method... basically most of them that don't use cdaweb or madrigal.

**Comment by rstoneback** [comment]
I checked over the instrument support. There are a number of instruments missing the method but some also don’t have any download support.

By my count, we need to add support to:
SuperDARN, assuming we can
Kp
Dst
F10.7, though you may already have this covered
cosmic
cosmic2013


Instruments without a real download:
champ
demeter
supermag
tiegcm
sport, sortie, icon will, once there is something to download
SGP4, downloads don’t make sense
test functions


On Feb 22, 2019, at 2:20 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


Several of the instruments don't have this method... basically most of them that don't use cdaweb or madrigal.

**Comment by aburrell** [comment]
I did not add the function to F10.7.  That was a lot of work that I don't have time for at the moment :-P

**Comment by jklenzing** [comment]
A quick solution would be to implement a check if the method exists, and skip the test if it doesn't.

As a test earlier in the week, I added the lines to `test_instrument.py`.  It worked well for the instruments with the method, but failed on those listed above (as expected).

**Comment by jklenzing** [comment]
> Is the exclude list maintained in a central place, or is the travis_dl_skip included in the instrument file? How do we check for a server being down vs a failed download?

My thought is that the exclude list would remain in `test_instruments.py`.  `travis_dl_skip` would be part of the instrument object similar to the `pandas_format` keyword.  I'm not sure how to test for the server being down.  Presumably we can ping it, but there should be a warning returned to the user to retry the tests.

**Comment by jklenzing** [comment]
To close:
- [ ] Implement `travis_dl_skip` flags in instruments,  Should include multiple flags for multiple tags
- [ ] Include check for `list_remote_files` as part of end-to-end test, which is skipped if this module is not detected.
- [ ] Update new_instrument.rst
- [ ] Fold test_ftp_instruments back into main testing routine.

**Comment by jklenzing** [comment]
Once #291 and #269 are done, this should be re-evaluated in the context of instrument sub-modules that inherit test routines from pysat_core

**Comment by jklenzing** [comment]
Closing with merge of #415
