### ISSUE TITLE
Panel deprecation

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#159]
```
/home/travis/build/rstoneback/pysat/pysat/ssnl/avg.py:167: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex 
on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.
```

**Comment by rstoneback** [comment]
For what I use Panel for (seasons averaging) I think Panel may be it. It has been awhile since I looked at this. I do remember checking into things when they first deprecated Panel. For reasons that I don’t remember I decided to stick with it. May or may not be good to remove. Not the most helpful statement, I know.

On Feb 13, 2019, at 2:00 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


/home/travis/build/rstoneback/pysat/pysat/ssnl/avg.py:167: FutureWarning:
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex
on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

**Comment by jklenzing** [comment]
No problem.  I'm tidying up the pandas update with the newest merge updates, and deciding whether to add some of these other ones in.  Sounds like we should leave this alone for now so we can determine the impact.

**Comment by rstoneback** [comment]
Agreed.

**Comment by jklenzing** [comment]
Leaving a note for future me:
http://xarray.pydata.org/en/stable/pandas.html

**Comment by jklenzing** [comment]
Officially deprecated as of pandas 0.25.0.  Capped pandas in #249.

**Comment by asher-pembroke** [comment]
I have a lot of experience using multi-indexed data. It's especially useful if you need to categorize your index. For instance, in pysat you have the notion of orbits which are just categorized time. In your multi-level index, you would have the primary one being time, a secondary one being orbit, and a third local time. For higher-dimensional data, you just add more levels. This pattern would make it easier to write instrument-independent code.

**Comment by rstoneback** [comment]
If you have a dataframe with a multi-index does it also support columns of data with only a single index? TIEGCM has some 4d data sets (3 spatial and time), plus it can have say a status flag that only depends on time.

**Comment by asher-pembroke** [comment]
Yes, here is a quick example:

```python
import pandas as pd
import numpy as np
```


```python
x = np.linspace(-1,1,2)
y = np.linspace(-2,2,3)
z = np.linspace(-3,3,4)
xx,yy,zz = np.meshgrid(x,y,z, indexing = 'ij')


data = xx**2 + yy*2 + zz**2
index = pd.MultiIndex.from_product([range(len(x)),range(len(y)), range(len(z))], 
                                   names = list('ijk'))

df3d = pd.DataFrame(data.ravel(), index = index)
df3d.head(12)
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th></th>
      <th>0</th>
    </tr>
    <tr>
      <th>i</th>
      <th>j</th>
      <th>k</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="12" valign="top">0</th>
      <th rowspan="4" valign="top">0</th>
      <th>0</th>
      <td>6.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>-2.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>-2.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>6.0</td>
    </tr>
    <tr>
      <th rowspan="4" valign="top">1</th>
      <th>0</th>
      <td>10.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>10.0</td>
    </tr>
    <tr>
      <th rowspan="4" valign="top">2</th>
      <th>0</th>
      <td>14.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>6.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>6.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>14.0</td>
    </tr>
  </tbody>
</table>
</div>




```python
df1d = pd.DataFrame(z)
df1d
```




<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>-3.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>-1.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3.0</td>
    </tr>
  </tbody>
</table>
</div>




```python
def mean(data):
   '''This function works on both single-indexed data and multi-indexed data'''
    return data.mean()
```


```python
mean(df1d)
```




    0    0.0
    dtype: float64




```python
mean(df3d)
```




    0    6.0
    dtype: float64

**Comment by jklenzing** [comment]
Migrating to pysat/pysatSeasons#4 and closing here.
