### ISSUE TITLE
Streamlining seasonal averaging

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#165]

**Comment by aburrell** [comment]
The seasonal binning and averaging is not very flexible.  Currently, there are 1D and 2D binning functions that only allow medians to be calculated.  I think the best way to improve this is to write an ND median/ave/other stat function. The statistical function could be provided as an input, allowing people to do clever things like find the moments from a Gaussian fit the the data in the desired bin. Then all the stat functions could go into utils.stats, and the seasonal binning part would live in ssnl. And if we do ND, then we won't have to keep re-writting things when we eventually want 3D or 4D binning.

**Comment by jklenzing** [comment]
Migrating to pysat/pysatSeasons#5 and closing here.
