### ISSUE TITLE
Incorporate ESMPy into model_utils

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#177]
Different ITM models use different coordinate systems as their reference frame.  This are often not compatible with the way measurements are recorded, requiring re-gridding and interpolation.  ESMPy is designed specifically for this an could be useful to incorporate.

https://www.earthsystemcog.org/projects/esmpy/

**Comment by jklenzing** [comment]
Migrating to pysat/pysatModelUtils#3 and closing here.
