### ISSUE TITLE
Windows Installation Using Conda without Pyglow

### ISSUE THREAD

**Issue by tcopp** [pysat/pysat#241]
installation order for windows conda python
(no pyglow)

make a new environment:
	conda create -n pysat --clone root
	conda activate pysat

setup mingw32 to build fortan:
	https://superuser.com/questions/1399738/pip-error-no-fortran-compiler-found-but-compiler-already-present
	install mingw32 with c++ and fortran compilers
	write a distutils.cfg file in C:\...\Anaconda3\Lib\distutils with the following:

		[build]           
		compiler=mingw32 

install pysat dependencies:
	conda install -c conda-forge netcdf4 pyephem sgp4 libpython xarray
	conda install -c rstoneback pysatcdf
	conda install -c msys2 m2w64-toolchain
	pip install apexpy madrigalWeb pysatMagVect

install develop version of pysat:
	install git
	clone git directory:
		git clone https://github.com/rstoneback/pysat
	change directory to where pysat was downloaded:
		cd pysat
	checkout develop branch:
		git checkout -b develop origin/develop
	install pysat through pip
		pip install .

**Comment by jklenzing** [comment]
pyglow as a dependency (along with other specialty packages) will be removed in pysat 2.1.0.  This will streamline the install across all platforms.

**Comment by jklenzing** [comment]
v2.1 and beyond no longer has pyglow as a dependency.  A number of other dependencies (auch as apexpy, etc) have also been removed as part of an overall streamlining.  Closing this issue.
