### ISSUE TITLE
multi_file_day option reveals concat_data bug

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#262]
**Describe the bug**
sort=True is a keyword on line 704 of _instrument.py, within concat_data. Needs to be removed and sorting behavior investigated now that option has been deprecated.

**To Reproduce**
1. create an Instrument object with multi_file_day=True
2. Load a day of data with neighboring days of data
3. See error

**Expected behavior**
We(I) should've had a test with this flag to catch any pandas version deprecations.

**Screenshots**

**Desktop (please complete the following information):**
 - Other details about your setup that could be relevant

**Additional context**

**Comment by rstoneback** [comment]
See pull #264

**Comment by jklenzing** [comment]
`sort` is a new option with pandas 0.23.  The "deprecation" comes from using an old version of pandas.  It looks like the issue is coming from using pandas 0.20 in pull #264.  I think this means we need to update the pandas version rather than remove the option.

See #125 and #152 for rationale for adding this option.  Essentially it was added because the default sorting behaviour was changing.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html

**Comment by rstoneback** [comment]
Thanks Jeff. My old pandas version got me in multiple places. I’ll update it back.


On Aug 21, 2019, at 4:46 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


sort is a new option with pandas 0.23. The "deprecation" comes from using an old version of pandas. It looks like the issue is coming from using pandas 0.20 in pull #264<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frstoneback%2Fpysat%2Fpull%2F264&data=02%7C01%7Crstoneba%40utdallas.edu%7C9cec8661fb4a49f5c93e08d72680fb47%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637020207730112009&sdata=%2FFk%2BR8gK3yhfcn6vweg5gkJA5l0fTZcIjTxyah9aWgs%3D&reserved=0>. I think this means we need to update the pandas version rather than remove the option.

See #125<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frstoneback%2Fpysat%2Fpull%2F125&data=02%7C01%7Crstoneba%40utdallas.edu%7C9cec8661fb4a49f5c93e08d72680fb47%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637020207730112009&sdata=uJr5TqwycNqz8DIC9QompujKmCOmXqru%2BklpNmWX9ls%3D&reserved=0> and #152<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frstoneback%2Fpysat%2Fissues%2F152&data=02%7C01%7Crstoneba%40utdallas.edu%7C9cec8661fb4a49f5c93e08d72680fb47%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637020207730122005&sdata=%2B3t9espJg9G8Uq364KlyVTaB8IdJhnQesPxn0Rbs1oY%3D&reserved=0> for rationale for adding this option. Essentially it was added because the default sorting behaviour was changing.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpandas.pydata.org%2Fpandas-docs%2Fstable%2Freference%2Fapi%2Fpandas.concat.html&data=02%7C01%7Crstoneba%40utdallas.edu%7C9cec8661fb4a49f5c93e08d72680fb47%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637020207730122005&sdata=rbNXwmlmaVt3ARNo8UlzpJ0pF43FjJelR0puUVicBr8%3D&reserved=0>

**Comment by jklenzing** [comment]
Np problem.  Double checked setup.py requirements and 0.23 is the minimum requirement for pandas, so this should be good for new users.
