### ISSUE TITLE
Expand support for instrument modules outside of pysat

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#265]
**Is your feature request related to a problem? Please describe.**
Instrument modules within the pysat.instruments folder are first class citizens. We need a mechanism to include other python modules when a user is trying to instantiate an Instrument object.

We need this to help:
1) Outside users with their own modules
  - Operational users
  - Science users
2) rstoneback to process IVM measurements (this works, but instantiation could be cleaner)
3) Reduce pysat's library footprint - instrument modules are destined for their own package 

**Describe the solution you'd like**
The solution needs to be discussed.

Options:
 - pysat searches for any modules starting with pysat and looks for a .instruments sub module.
  We can get false positives, not a big deal with error handling. We will miss some packages unless outside folks adopt the naming scheme. Has the benefit of it working 'automagically' when new packages installed. Particularly if module list always generated at Instrument instantiation. 
 - require users to register modules. We'll need add_instrument_module and remove_instrument_module methods. We are also storing more data in .pysat .
 - both (?). Order would be user modules then pysat* modules.

**Describe alternatives you've considered**

Please see above.

**Additional context**
Experience here may be useful in making pysat an auto meta package. I mean that anything with pysat* is auto imported.... This would provide a solution to breaking pysat functions off while also making it easy to use any 'powered by pysat' modules that are installed.

**Comment by rstoneback** [comment]
pinging @aburrell and @jklenzing given the relationship to fundamentals of v3.0

**Comment by aburrell** [comment]
I don't think that anything with pysat* should be imported.  There are other reasons that users would have something named like this that is not related (`pysatellite`, for instance) and that would be a barrier to wanting to use pysat.

**Comment by rstoneback** [comment]
Fair enough, thanks for the feedback!

**Comment by jklenzing** [comment]
Thinking about how pysatMissionPlanning will be set up, I vote for option 2 (registration).  For this module, registration could be completed as part of the setup procedures there.

**Comment by rstoneback** [comment]
The current code in the pull request supports both #1 and #2. I asked Asher to take out #1 and to add methods so we can register and remove instrument packages as needed.

**Comment by jklenzing** [comment]
@rstoneback, has this been solved by #269?  Or is there something else we need?

**Comment by rstoneback** [comment]
I believe this is solved.
