### ISSUE TITLE
Dropping duplicated times and Instrument data access

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#267]
**Describe the bug**
If there are duplicate times in the pandas time index then data access has problems.
Fixing it can be a challenge as well. The following doesn't work.

        print('Unique IVM times 1 :', ivm.index.is_unique)
        uq, idx = np.unique(ivm.index, return_index=True)
        ivm.data = ivm[idx, :]
        print('Unique IVM times 2 :', ivm.index.is_unique)

It doesn't work since pysat translates the integers supplied into index labels, then accesses the data in the dataframe by label. The labels are times, so all duplicate times are kept. The dataframe is no different after this than before.

**To Reproduce**
1. Create an instrument object with at least one duplicate time in the index
2. Follow code above

**Expected behavior**
I expected to downselect on the data

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Version 10.14.5

**Additional context**
We should consider replacing the .loc indexing with .iloc in the __getitem__ method.
This particular bug is not destined to last long, even without changes, since we adopted the strict_time_flag option and plan on enforcing that in the future. Nevertheless, I feel that indexing by integer should have the maximum reliability.

**Comment by rstoneback** [comment]
pinging @jklenzing given his work in this area as an FYI

**Comment by jklenzing** [comment]
This looks like a syntax issue. `ivm.data = ivm[idx, :]` should be `ivm.data = ivm[idx]`

Testing using the de2 _lang instrument for the test date, in develop-3:

```
In [24]:     print('Unique times 1 :', lang.index.is_unique) 
    ...:     uq, idx = np.unique(lang.index, return_index=True) 
    ...:     lang.data = lang[idx, :] 
    ...:     print('Unique times 2 :', lang.index.is_unique)                                                                                         
Unique times 1 : False
Unique times 2 : False

In [25]:     print('Unique times 1 :', lang.index.is_unique) 
    ...:     uq, idx = np.unique(lang.index, return_index=True) 
    ...:     lang.data = lang[idx] 
    ...:     print('Unique times 2 :', lang.index.is_unique)                                                                                         
Unique times 1 : False
Unique times 2 : True
```

**Comment by jklenzing** [comment]
`.loc` is used to allow labels to be passed through.  We can rewrite to use `.iloc`, but we would need to convert any labels to integers beforehand, and the code becomes a lot messier (more decision points).  The change in syntax is a result of pandas deprecating the `.ix` syntax. 

While ':' is not necessary, this does seem like a hole that needs to be plugged.  Even if strict_time_flag is True, each instrument with potential non-unique data will likely need a cleaning routine.  See #412.

**Comment by jklenzing** [comment]
Since `strict_time_flag` is now engaged by default, dropping this
