### ISSUE TITLE
Custom functions called when there is no data

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#277]
**Describe the bug**
The pysat kernel should only apply the custom functions to data if there is data. Does this by checking the length of the index. So if the dataframe is all NaNs routines still get called. Switch to using the inst.empty flag instead.

**To Reproduce**
1. Load a data set that produces all NaNs
2. If the instrument object has custom functions, they'll get applied
3. See error

**Expected behavior**
Custom functions should only be invoked if there is something there to work on

**Desktop (please complete the following information):**
 - OS: MacOS
 -10.14.5

**Additional context**

**Comment by jklenzing** [comment]
Looking through `develop`, it looks like the `empty` flag is already applied.

https://github.com/pysat/pysat/blob/84bcb06ad8e7fb638927713465c63b67e2830f82/pysat/_custom.py#L122-L129

https://github.com/pysat/pysat/blob/84bcb06ad8e7fb638927713465c63b67e2830f82/pysat/_instrument.py#L1410-L1411

Is there something else I'm missing on this issue?

**Comment by rstoneback** [comment]
No, I think we are good then.


On Jan 7, 2020, at 1:57 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


Looking through develop, it looks like the empty flag is already applied.

https://github.com/pysat/pysat/blob/84bcb06ad8e7fb638927713465c63b67e2830f82/pysat/_custom.py#L122-L129<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpysat%2Fpysat%2Fblob%2F84bcb06ad8e7fb638927713465c63b67e2830f82%2Fpysat%2F_custom.py%23L122-L129&data=02%7C01%7Crstoneba%40utdallas.edu%7C6e9258ec82754062d1a508d793abc553%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637140238279392111&sdata=kXlFh3FwYvGAI6qqXSRtBwHFTdD%2FJVaND%2BAZdeRH8qI%3D&reserved=0>

https://github.com/pysat/pysat/blob/84bcb06ad8e7fb638927713465c63b67e2830f82/pysat/_instrument.py#L1410-L1411<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpysat%2Fpysat%2Fblob%2F84bcb06ad8e7fb638927713465c63b67e2830f82%2Fpysat%2F_instrument.py%23L1410-L1411&data=02%7C01%7Crstoneba%40utdallas.edu%7C6e9258ec82754062d1a508d793abc553%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637140238279402105&sdata=usdWBz3q4qRSrKrGrT6pZswdRxiziAVWguWaKVgEvCk%3D&reserved=0>

Is there something else I'm missing on this issue?
