### ISSUE TITLE
Add a 'How to Cite' to readme

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#278]
**Is your feature request related to a problem? Please describe.**
Help the community properly spread the word about python in publications

**Describe the solution you'd like**
Add info to the Readme. Include a note about pysat paper, and perhaps a request in Acknowledgements.

**Describe alternatives you've considered**
No information

**Additional context**
similar approach pursued in sami2py

**Comment by jklenzing** [comment]
From zenodo:
```
@misc{russell_stoneback_2019_3321222,
  author       = {Russell Stoneback and
                  Jeff Klenzing and
                  Angeline Burrell and
                  Carey Spence and
                  Matthew Depew and
                  NHargrave and
                  vvonbose and
                  Silvio Luis and
                  Gayatri},
  title        = {rstoneback/pysat v2.0},
  month        = jul,
  year         = 2019,
  doi          = {10.5281/zenodo.3321222},
  url          = {https://doi.org/10.5281/zenodo.3321222}
}
```

**Comment by aburrell** [comment]
We'll need to fix the author names, obviously.  And suggest a citekey that won't cause LaTeX to puke.

**Comment by jklenzing** [comment]
How about `pysat200`?

**Comment by jklenzing** [comment]
Draft up here:  https://github.com/rstoneback/pysat/blob/doc_how_to_cite/docs/citing.rst

The format is still pretty bad, but at least is readable.

**Comment by rstoneback** [comment]
Thanks @jklenzing and @aburrell. I modified the title and expanded the developer names.

**Comment by jklenzing** [comment]
Closing with merge of #283.
