### ISSUE TITLE
ENH: Provide user feedback when a non-pysat keyword supplied to Instrument

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#292]
**Is your feature request related to a problem? Please describe.**
Users can add any keyword to Instrument instantiation. Non-pysat keywords are passed to the corresponding instrument .load method. pysat.Instrument() set up commands will appear to work just fine even when a user mistypes a pysat keyword. 

**Describe the solution you'd like**
Provide feedback when non-pysat keywords are registered.

**Describe alternatives you've considered**
Currently no feedback. Some feedback has to be better as this issue has tripped up pysat devs. If it isn't clear to us it isn't clear to users.

Open to other suggestions.

**Comment by rstoneback** [comment]
Technically there is some feedback. For example, as can be seen below, keywords are listed. Though a user may only do a print(inst) once they are aware things have gone wrong. A proactive print (or soon to be logging) helps out.

import pysat
from pysatMissionPlanning.instruments import pysat_sgp4

sgp4 = pysat.Instrument(inst_module=pysat_sgp4)

print(sgp4)

pysat Instrument object
-----------------------
Platform: pysat
Name: sgp4
Tag: 
Satellite id: 

Data Processing
---------------
Cleaning Level: clean
Data Padding: None
Keyword Arguments Passed to load(): {}
Custom Functions : 
    <function add_quasi_dipole_coordinates at 0x123fa7b90>
    <function add_aacgm_coordinates at 0x123fa7c08>
    <function calculate_ecef_velocity at 0x123fa7b18>
    <function add_sc_attitude_vectors at 0x123fa7aa0>
    <function add_iri_thermal_plasma at 0x123fa7c80>
    <function add_hwm_winds_and_ecef_vectors at 0x123fa7cf8>
    <function add_igrf at 0x123fa7d70>
    <function project_ecef_vector_onto_sc at 0x123fa7e60>
    <function project_hwm_onto_sc at 0x123fa7ed8>
    <function add_msis at 0x123fa7de8>

Orbit Settings
--------------
Orbit properties not set.

Local File Statistics
---------------------
Number of files: 366
Date Range: 01 December 2017 --- 01 December 2018

Loaded Data Statistics
----------------------
No loaded data.

**Comment by jklenzing** [comment]
Should this trigger when non-pysat keywords are used, or for just non-pysat keywords that are unused in `load`?

**Comment by aburrell** [comment]
Probably should trigger in the instantiation and download, too.  It would be pretty simple to write a little warning routine that could be called by each of these.

**Comment by jklenzing** [comment]
So here's the scenario I'm thinking of.  A user is building an instrument that requires some additional input.  Let's say there's a boolean variable called `shiny` that determines whether certain post-processing routines are done on the data.  And for arguments sake, this must be done at the load level rather than clean for reasons.

If I'm the user, I don't want to be pinged each time I instantiate this object.  The ability to pass keywords through to an instrument is a feature that could be valuable (though perhaps redundant).  Likewise, the ability to warn the user if something is misspelled is also useful.  

Can the `_instrument` class check to see if keywords are used down the line before providing user feedback?  Or is there a better way of implementing this?  If not, we may need to choose between some combination of flexibility  and annoyance.

**Comment by aburrell** [comment]
What you're describing is how the custom routines work, if I am not mistaken.  So they wouldn't need to add `shiny` to the keyword arguments, they'd just need to add the custom routine and set the clean level to none before loading.

**Comment by rstoneback** [comment]
Hey Folks,

  Out of order, but thanks for the pulls and the approvals.

I’ve been thinking about this recently. I think we have a few options.
Quick summary, user supplies a keyword at instantiation that isn’t a pysat keyword. This keyword will then get passed along to the load routine for fun and games.
Recently we ran into an issue where a pysat keyword was desired but not entered correctly and thus expected things didn’t happen. Keyword was passed to load instead.

1) Since we have logging, we can use logging at the info or debug level. By default then users won’t see the heads up unless then logging output level is changed. So the info is there but mostly not visible. Checked at instantiation.

2) We could warn when something like a pysat keyword is entered, but not quite. Could probably be solved with regex in a single line, but we’d need to define a standard for what it means to be ‘like’ a pysat keyword. Perhaps there is a package for this so the ‘likeness’ is typical of other uses.

3) Leave it alone. non-pysat keywords are already listed if a user does print(inst) . The variable listing needs work, and should be sorted alphabetically, but that is another pull.

4) Could switch to requiring users to specifically pass non-pysat keywords in a specific way. Then we’d remove the **kwargs from instantiation and any non-pysat keywords directly supplied will cause an error. Have to sort out how users would specify keywords to be passed to load.

5) Checking if a keyword is used or not could be a version of the halting problem, which means ‘sometimes’, but we’d have to develop code analysis for it. non-pysat keywords are always used in the sense they are passed to the load routine. 
 
6) Variant of 5 that should be easier. Check if keyword passed to load routine is specifically declared in load method signature. Thus keywords are only passed when specifically listed as supported. I’m presuming there is any easy way to get this in Python. Python knows.


#4 could be the option that will produce the least overall confusion. Potentially makes pysat ‘harder’ to use but things are explicit. I think explicit features are specifically called out as a good thing somewhere.

#6 makes things more robust without really changing user experience. keywords are explicit when methods are written, that’s good. When we don’t have a match we can explicitly raise a Warning right then, good for feedback. There is a chance some instrument load methods need to get updated. If we can check if a keyword is present in a load, then we can also tell the user what keywords are allowed. Can be added to print(inst)

Cheers,
Russell

**Comment by jklenzing** [comment]
> What you're describing is how the custom routines work, if I am not mistaken. So they wouldn't need to add `shiny` to the keyword arguments, they'd just need to add the custom routine and set the clean level to none before loading.

Not quite.  The custom routine would need to be added each time.  I'm thinking of something more routine. 

I thought of a more specific example.  Over in `pysatMissions`, the `pysat_ephem` instrument currently produces one full day of data with all the modeled data available in the package (pyglow, apexpy, aacgmv2).  Depending on the usage case, I might want to only create one orbit of data, and might want to turn off some or all of the models. (Real world requirements: one problem requires one orbit of data, no models. Another requires a day of data, some models).

All of these could be handled by passing custom keywords through the system, or by various combinations of `tag` and `sat_id` as in the `pysat_testing` instruments.  Nominally, I would use `sat_id` to specify number of points / orbits, similar to the testing instruments. `tag` could be used as an all, some, or nothing when it comes to the modeled instruments.  However, more finesse (and therefore more complication) could be added by using `msis=True`, `hwm=False`, etc as custom keywords to turn each component on and off.

Thanks @rstoneback for listing out the options above.  I had been thinking of this in terms of a variation on 4 (shutting off the non-standard keywords) or 6.  To solve my problem listed above, I can find a version of 4b (no non-standard keywords) that will work.  I'm just trying to think of future issues before we make a decision.

**Comment by jklenzing** [comment]
> Python knows.

Well that sounds ominous.  :scream:

**Comment by rstoneback** [comment]
> > What you're describing is how the custom routines work, if I am not mistaken. So they wouldn't need to add `shiny` to the keyword arguments, they'd just need to add the custom routine and set the clean level to none before loading.
> 
> Not quite. The custom routine would need to be added each time. I'm thinking of something more routine.
> 
> I thought of a more specific example. Over in `pysatMissions`, the `pysat_ephem` instrument currently produces one full day of data with all the modeled data available in the package (pyglow, apexpy, aacgmv2). Depending on the usage case, I might want to only create one orbit of data, and might want to turn off some or all of the models. (Real world requirements: one problem requires one orbit of data, no models. Another requires a day of data, some models).
> 
One current solution is to generate the day of data as normal, then use the pysat orbit iterator to easily parse it down to a single orbit. I don't want to discourage thinking of use cases but I can't help but note the orbit one already has a non-keyword solution :) 
 
> All of these could be handled by passing custom keywords through the system, or by various combinations of `tag` and `sat_id` as in the `pysat_testing` instruments. Nominally, I would use `sat_id` to specify number of points / orbits, similar to the testing instruments. `tag` could be used as an all, some, or nothing when it comes to the modeled instruments. However, more finesse (and therefore more complication) could be added by using `msis=True`, `hwm=False`, etc as custom keywords to turn each component on and off.
> 

We could overload those items a bit more. While effective, I worry about the potential user confusion as just occurred with the testing instruments. If we can make things more clear while still being simple for the user that would be the best outcome. 'msis=True' is much clearer.

That report also made me think about the issue (# TBFound) about changing the Instrument instantiation parameters. Adding another group, and new names, to make things easier. 

> Thanks @rstoneback for listing out the options above. I had been thinking of this in terms of a variation on 4 (shutting off the non-standard keywords) or 6. To solve my problem listed above, I can find a version of 4b (no non-standard keywords) that will work. I'm just trying to think of future issues before we make a decision.

Agreed. That's why I listed all the options I could think of and didn't specifically list my favorite, yet... :)

**Comment by jklenzing** [comment]
> One current solution is to generate the day of data as normal, then use the pysat orbit iterator to easily parse it down to a single orbit. I don't want to discourage thinking of use cases but I can't help but note the orbit one already has a non-keyword solution :)

While this technically works, it's not very time-efficient if I need to generate 5000 or more orbits with random RAAN and argument of perigee for a given case study.

**Comment by rstoneback** [comment]
> > Python knows.
> 
> Well that sounds ominous. 😱

Snakes are scary. They swallow you whole and nobody can hear you scream from the inside. Scientists are still trying to determine how a snakes scales, muscles, and stomach combine to form a nearly perfect sound absorber, but only for internal sources.

**Comment by rstoneback** [comment]
> > One current solution is to generate the day of data as normal, then use the pysat orbit iterator to easily parse it down to a single orbit. I don't want to discourage thinking of use cases but I can't help but note the orbit one already has a non-keyword solution :)
> 
> While this technically works, it's not very time-efficient if I need to generate 5000 or more orbits with random RAAN and argument of perigee for a given case study.

True, but we are already using Python. We are trading CPU time for developer time.

I haven't timed MSIS, but the integration for an orbit shouldn't take much cpu time, based on some work I did years back.

Anyway, the details of the orbit thing aren't particularly important, other than pysat supports whatever a user wants to do. There could very well be situations where a user does something pysat 'already' does, but for good reasons. Which I think leads us back to robust and clear support for users to pass options to load in a way that is robust for their case, as well as more typical pysat cases.

**Comment by rstoneback** [comment]
Closing due to merge of pull.
