### ISSUE TITLE
Constellation calls pysat.ssnl

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#303]
`Constellation.add` invokes  `pysat.ssnl.avg._calc_2d_median`, which has been migrated to pysatSeasons.  Importing these functions for 2.x versions of pysat will allow a smooth transition for users, but the 3.0.0 roadmap currently removes this from the core code.  This should be discussed to prevent a future bug.

**Comment by rstoneback** [comment]
We should talk about it.

I don't think including pysatSeasons as a pysat dependency is a big issue. Doesn't really add to requirements in a significant way.

**Comment by aburrell** [comment]
pysatSeasons brings in plotting routines, which frequently cause issues for me.  I'd rather not have this as a pysat dependence.  Spending my morning trying to fix my validation routines, which seasonal has broken, for some reason.

**Comment by aburrell** [comment]
Also, looking at the `_constellation.py` routine `add`, it seems inappropriate to be doing median binning at this stage of the data analysis.  This should be done correctly instead of implementing a convenient hack.

**Comment by rstoneback** [comment]
Thanks for the heads up on the plotting routines. Forgot about those. 

For the future, for problems that don't have a fix like do the code better, we could do a soft import, aka the package import could be hidden behind a try, except clause. Only those folks that actually need to run the method that contains the import will get notes about missing a package.

**Comment by jklenzing** [comment]
Looking over the add and difference functions, can we reduce the code by having a single `_combine` function that is called by both `add` and `difference`? 

It looks like if the following line in `difference` is changed from "-" to "+", then `difference` becomes `add`, although with different arguments.
https://github.com/pysat/pysat/blob/c4ff909730e1602480a8d2c908ee1802e7768d1d/pysat/_constellation.py#L441

**Comment by jklenzing** [comment]
Thinking of using a boolean variable in the proposed `constellation._combine` function to toggle between `add` and `difference`.

**Comment by jklenzing** [comment]
Plan moving forward:  

We decided to remove `add` and `difference` here, as their functionality overlaps with pysatSeasons. Created an issue at pysat/pysatSeasons#15 to make sure that this functionality is maintained with the pending rewrite over there.

**Comment by jklenzing** [comment]
Closing with merge of #353.
