### ISSUE TITLE
Single subpackage for storing pysat info

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#309]
**Is your feature request related to a problem? Please describe.**
pysat stores a variety of info (file lists, directory locations) under .pysat in files. There have been a few reoccurring bugs in this area as different areas pysat roll their own info storage methods.
 
**Describe the solution you'd like**
We need a sub-package that gives us a systematic way to store and load pysat info, that is also thread safe, see issue #304 

**Describe alternatives you've considered**

**Additional context**

**Comment by jklenzing** [comment]
#376 partially addresses this, but full package will be needed eventually.

**Comment by aburrell** [comment]
Matplotlib does it this way: https://matplotlib.org/3.3.1/tutorials/introductory/customizing.html#the-matplotlibrc-file

**Comment by aburrell** [comment]
`pysat.file_timeout` for thread-safe processing will also be included here.

**Comment by jklenzing** [comment]
To close:
- [ ] Incorporate rc file to store defaults
