### ISSUE TITLE
BUG: Change how default directory is created

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#315]
**Is your feature request related to a problem? Please describe.**
pysat creates a default directory in the user's home directory.  It will do this if a directory is not specified.  This can lead to unintended duplication of data for users with a custom path if pysat resets the directory.

**Describe the solution you'd like**
pysat should prompt the user if the data directory is not set.  It should only create a directory if a custom directory is set.

**Describe alternatives you've considered**
n/a

**Additional context**
https://github.com/pysat/pysat/wiki/2019_10_23

For travis, make sure to set directory in yml file.

**Comment by rstoneback** [comment]
A slightly different path was taken but addresses the underlying issue.
