### ISSUE TITLE
BUG: error_perm: 550 SSL/TLS required on the control channel

### ISSUE THREAD

**Issue by ithaca-isr** [pysat/pysat#319]
**Describe the bug**
When using pysat on my MacOS, I get the error:
error_perm: 550 SSL/TLS required on the control channel

My MacOs is HighSierra ver 10.13.6. I am using Python 3.6 on a Jupyter notebook (Anaconda 1.6.3), which runs from my Safari browser, Version 13.0.2 (13608.2.40.1.2).

**To Reproduce**
1. Use the same versions of MAcOS, Safari, Python and Jupiter notebook.

2. Run the following code (from the pysat examples):
import os
import pysat
import matplotlib.pyplot as plt
import pandas as pds
import numpy as np

vefi = pysat.Instrument(platform='cnofs', name='vefi', tag='dc_b',
                        clean_level=None, orbit_info=orbit_info)
# set the directory to save plots to
results_dir = '/Users/sevagderghazarin/pysattest'

# there are changes in the orbit (local time info not in file)
orbit_info = {'index':'longitude', 'kind':'longitude'}

# define function to remove flagged values
def filter_vefi(inst):
    idx, = np.where(vefi['B_flag']==0)
    vefi.data = vefi.data.iloc[idx]
    return

# attach function to vefi
vefi.custom.add(filter_vefi,'modify')

# set limits on dates analysis will cover, inclusive
start = pds.datetime(2010,5,9)
stop = pds.datetime(2010,5,15)
vefi.download(start, stop)

# leave bounds unassigned to cover the whole dataset
vefi.bounds = (start,stop)

**Expected behavior** 

In my case,  when I ran the code above, I got the error messages seen below
**Screenshots**

---------------------------------------------------------------------------
error_perm                                Traceback (most recent call last)
<ipython-input-15-0b15a689c28c> in <module>()
     38 start = pds.datetime(2010,5,9)
     39 stop = pds.datetime(2010,5,15)
---> 40 vefi.download(start, stop)
     41 
     42 # leave bounds unassigned to cover the whole dataset

/Users/sevagderghazarian/anaconda/lib/python3.6/site-packages/pysat/_instrument.py in download(self, start, stop, freq, user, password, **kwargs)
    958                                sat_id=self.sat_id,
    959                                data_path=self.files.data_path,
--> 960                                **kwargs)
    961         else:
    962             self._download_rtn(date_array,

/Users/sevagderghazarian/anaconda/lib/python3.6/site-packages/pysat/instruments/nasa_cdaweb_methods.py in download(supported_tags, date_array, tag, sat_id, ftp_site, data_path, user, password, fake_daily_files_from_monthly)
    220     ftp = ftplib.FTP(ftp_site)
    221     # user anonymous, passwd anonymous@
--> 222     ftp.login()
    223 
    224     try:

/Users/sevagderghazarian/anaconda/lib/python3.6/ftplib.py in login(self, user, passwd, acct)
    416             #   host or country.
    417             passwd = passwd + 'anonymous@'
--> 418         resp = self.sendcmd('USER ' + user)
    419         if resp[0] == '3':
    420             resp = self.sendcmd('PASS ' + passwd)

/Users/sevagderghazarian/anaconda/lib/python3.6/ftplib.py in sendcmd(self, cmd)
    271         '''Send a command and return the response.'''
    272         self.putcmd(cmd)
--> 273         return self.getresp()
    274 
    275     def voidcmd(self, cmd):

/Users/sevagderghazarian/anaconda/lib/python3.6/ftplib.py in getresp(self)
    244             raise error_temp(resp)
    245         if c == '5':
--> 246             raise error_perm(resp)
    247         raise error_proto(resp)
    248 

error_perm: 550 SSL/TLS required on the control channel

![image](https://user-images.githubusercontent.com/57118135/67726258-9ecdd180-f9bb-11e9-91b4-c781ecba5afd.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by jklenzing** [comment]
Hi @ithaca-isr, thanks for documenting this.  This should be solved by upgrading to pysat 2.0.  The ftp code for the nasa cdaweb methods was removed and replaced by HTTPS protocol, which should be smoother.  CDAWeb has updated to only allowing secure connections (HTTPS or FTPS), which I think is the source of the above error.  Let us know if you still see a bug.

**Comment by ithaca-isr** [comment]
Hi @jklenzing, thanks for the suggestion, it worked! :)
