### ISSUE TITLE
cosmic 2013

### ISSUE THREAD

**Issue by schark1** [pysat/pysat#323]
**Describe the bug**

I am interesting in downloading and working with cosmic data from the 2013 reprocessing.  The documentation says this should be accessible by first getting the instrument object instance:

cosmic = pysat.Instrument(platform='cosmic2013', name='gps', tag='ionprf') 

with pysat 2.0.0, this returns an error:

No module named 'pysat.instruments.cosmic2013_gps'

There is a pysat.instruments.cosmic_gps module - has the 2013 now become the default cosmic data set? How do I download the data?
  
**To Reproduce**

python3
>>> import pysat
>>> cosmic = pysat.Instrument(platform='cosmic2013', name='gps', tag='ionprf')

**Expected behavior**
I expected it to create the instance of the cosmic2013 gps object, so I could then download data.  Also I tried to download the regular cosmic data:

>>> cosmic = pysat.Instrument(platform='cosmic', name='gps', tag='ionprf')
>>> start = pysat.datetime(2009,5,6)
>>> stop = pysat.datetime(2009,5,9)
>>> cosmic.download(start, stop, user, password)
where I used a known username and password, not reproduced here.
which threw an exception:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schaerk1/anaconda3/lib/python3.7/site-packages/pandas/tseries/frequencies.py", line 154, in to_offset
    offset = get_offset(name)
  File "/Users/schaerk1/anaconda3/lib/python3.7/site-packages/pandas/tseries/frequencies.py", line 193, in get_offset
    raise ValueError(libfreqs.INVALID_FREQ_ERR_MSG.format(name))
ValueError: Invalid frequency: USER

**Screenshots**

**Desktop (please complete the following information):**

Mac OS 10.14.6 using anaconda with python 3.7

**Additional context**

**Comment by rstoneback** [comment]
Thanks for the report!

The cosmic_gps module now defaults to the 2013 reprocessed data, when available.
I've slightly updated the download command to explicitly pass user and password into those keyword arguments. The user value, as written above, was interpreted as an input to the frequency keyword argument.

cosmic = pysat.Instrument(platform='cosmic', name='gps', tag='ionprf')
start = pysat.datetime(2009,5,6)
stop = pysat.datetime(2009,5,9)
cosmic.download(start, stop, user=user, password=password)

As a friendly tip, running 
>>> help(cosmic.download)
will provide an overview of the available input arguments.

Note there is a bug in the v2.0 cosmic download support (#313) that has already been fixed (in the develop branch) and will be released very soon as part of v2.1 (#321).

**Comment by schark1** [comment]
Thanks Russel!

Robert Schaefer
Space Department
JHU/APL, MS 200-W274
11101 Johns Hopkins Rd.
Laurel, MD 20723

240-228-2740
robert.schaefer@jhuapl.edu<mailto:robert.schaefer@jhuapl.edu>



On Nov 7, 2019, at 2:16 PM, Russell Stoneback <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the report!

The cosmic_gps module now defaults to the 2013 reprocessed data, when available.
I've slightly updated the download command to explicitly pass user and password into those keyword arguments. The user value, as written above, was interpreted as an input to the frequency keyword argument.

cosmic = pysat.Instrument(platform='cosmic', name='gps', tag='ionprf')
start = pysat.datetime(2009,5,6)
stop = pysat.datetime(2009,5,9)
cosmic.download(start, stop, user=user, password=password)

As a friendly tip, running

help(cosmic.download)
will provide an overview of the available input arguments.

Note there is a bug in the v2.0 cosmic download support (#313<https://github.com/pysat/pysat/pull/313>) that has already been fixed (in the develop branch) and will be released very soon as part of v2.1 (#321<https://github.com/pysat/pysat/pull/321>).

**Comment by rstoneback** [comment]
The references to cosmic2013 have been updated in the tutorial and examples text in pull #321

**Comment by rstoneback** [comment]
closed with v2.1 release.
