### ISSUE TITLE
Preserve Instrument docstring

### ISSUE THREAD

**Issue by asherp** [pysat/pysat#324]
Instrument documentation is not available upon instantiation of the instrument object. For example,
```python
vefi = pysat.Instrument(platform='cnofs',
                        name='vefi',
                        tag='dc_b',
                        clean_level='clean')

help(vefi)
```
This returns the documentation for the generic Instrument class
```console
Help on Instrument in module pysat._instrument object:

class Instrument(builtins.object)
 |  Instrument(platform=None, name=None, tag=None, sat_id=None, clean_level='clean', update_files=None, pad=None, orbit_info=None, inst_module=None, multi_file_day=None, manual_org=None, directory_format=None, file_format=None, temporary_file_list=False, strict_time_flag=False, ignore_empty_files=False, units_label='units', name_label='long_name', notes_label='notes', desc_label='desc', plot_label='label', axis_label='axis', scale_label='scale', min_label='value_min', max_label='value_max', fill_label='fill', *arg, **kwargs)

...
```
This makes it hard to cite the original instrument without first loading the instrument module to get at its documentation:
```python
from pysat.instruments import cnofs_ivm
help(cnofs_ivm)
```
```console
Help on module pysat.instruments.cnofs_ivm in pysat.instruments:

NAME
    pysat.instruments.cnofs_ivm

DESCRIPTION
    Supports the Ion Velocity Meter (IVM) onboard the Communication
    and Navigation Outage Forecasting System (C/NOFS) satellite, part
    of the Coupled Ion Netural Dynamics Investigation (CINDI). Downloads
    data from the NASA Coordinated Data Analysis Web (CDAWeb) in CDF
    format.

   ...
```
The [workaround used in pysatKamodo](https://github.com/pysat/pysatKamodo/blob/bd52c8afd8a3b9a859c1d8f4be73d69919e5a9eb/pysat_kamodo/pysat_kamodo.py#L19) is to replicate the code from Instrument that loads the module based on name and platform keywords. Instead, we could (should?) have the Instrument-specific docs merged with generic Instrument docs.

**Describe alternatives you've considered**
* Another approach is to implement a method like `get_instrument_docstring`.
* We could put all instrument documention into meta somewhere...

**Comment by aburrell** [comment]
So I looked into this a bit.  If you declare the instrument using the `inst_module` keyword, you can get the help output you want using `help(vefi.inst_module)`.  So, we could potentially address this by always assigning the `inst_module` attribute and highlighting this as a way of seeing the module help information.

**Comment by rstoneback** [comment]
I think some other parts of the code check against inst_module for certain actions. Those could be updated of course but something to consider. We would also have to add something to distinguish between a user supplying inst_module or not so that `__repr__` could recreate the right inputs.

What if we modified the `__doc__` attached to each instrument object so it also includes the inst_module.__doc__?

**Comment by aburrell** [comment]
I think that may go against the spirit of the `help` command.  I see why Asher wanted this functionality, but I don't want a new user to confuse the Instrument help with a specific instrument module's help command.

**Comment by rstoneback** [comment]
That is fair. 

What about something like an `inst_info` attribute with the docstring from the module in there, or `inst_doc`?

My concern with using `inst_module` is that, even if we document that the instrument docstring is there via help(inst.inst_module), many users won't know about it. `inst_doc` doesn't solve that issue but perhaps with the right name and tab introspection users may come across it.

**Comment by aburrell** [comment]
Having it in `inst_doc` still won't make it appear using `help`.  Basically, the problem is that @asherp wants `help` to do something it's not really designed to do (but makes sense for his application).  Something to put in a meeting agenda?

**Comment by rstoneback** [comment]
Oh, yeah, it won't work in help that way. Just brainstorming possible areas to store the information. Sure, on the next agenda.

**Comment by rstoneback** [comment]
https://github.com/pysat/pysat/wiki/2021_06_30

**Comment by rstoneback** [comment]
`inst_module` pathway after discussion on call.
