### ISSUE TITLE
Bug in parse delimited files

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#337]
**Describe the bug**
The _files method for dealing with delimited filenames did not work when I tried on COSMIC files.

**To Reproduce**
1. In cosmic_gps.py replace the fixed_width filename parsing call with the delimited version, including the '.' delimiter.
2. method produces an error

**Expected behavior**
Correctly parsed list

**Desktop (please complete the following information):**
 - OS: Max OS 10.12.6

**Comment by jklenzing** [comment]
Can't duplicate this in python 3.7.3 or 3.6.9.

Steps:
1) Replace line 123 of cosmic_gps.py
```
stored = pysat._files.parse_fixed_width_filenames(files, format_str)
```
with
```
stored = pysat._files.parse_delimited_filenames(files, format_str, '.')
```

2) in ipython:
```
import pysat
cosmic = pysat.Instrument(platform='cosmic', name='gps', tag='ionprf')    
cosmic.files.files  
```

Both running the nominal case in `develop` and the modified case above produce the same list of filenames.

**Comment by jklenzing** [comment]
I don't see any other programs like numpy in the routines required here.  Not sure if I'm missing something else.

**Comment by jklenzing** [comment]
Hash ref: 84bcb06

**Comment by rstoneback** [comment]
Thanks for providing an independent check. Either I did something wrong or there is really something a bit wrong with my setup. I’ll double check on my end. On the list.

**Comment by rstoneback** [comment]
I tried this again on the latest develop:

In [5]: gps = pysat.Instrument('cosmic', 'gps', 'ionPrf', update_files=True)
---------------------------------------------------------------------------

ValueError: invalid literal for int() with base 10: 'G26_2013'
> /Users/russellstoneback/Code/pysat/pysat/_files.py(808)parse_delimited_filenames()
    806     # convert to numpy arrays
    807     for key in stored.keys():
--> 808         stored[key] = np.array(stored[key]).astype(int)
    809         if len(stored[key]) == 0:
    810             stored[key] = None

**Comment by jklenzing** [comment]
The issues are stemming from treating the ground station ID as seconds, hence the `second` key being identified as 'G26_2016', a non-integer. If I remove the second assumptions from the cosmic key, the delimited files work fine.

https://cdaac-www.cosmic.ucar.edu/cdaac/cgi_bin/fileFormats.cgi?type=ionPrf

I think our efforts will be better spent on migrating cosmic to xarray for pysat 3.0.0.

**Comment by jklenzing** [comment]
Closing with merge of #439 and #442
