### ISSUE TITLE
Time dependence in 2D testing instruments

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#359]
When attempting to perform unit tests in pysatModelUtils, I need a multi-dimensional test instrument at a ~15 min time resolution.  This isn't supported, and the current required 1 s resolution makes it impossible to test certain routines.

**Describe the solution you'd like**
I would like the `sat_id` keyword argument to work in the 2D testing instruments the same way it works in the standard testing instruments.

**Describe alternatives you've considered**
I have attempted to modify the standard and 2D testing instruments to achieve the desired results, but this doesn't work.  The current alternative is to create a new test object, which defeats the purpose of having the pysat testing instruments.

**Comment by jklenzing** [comment]
Are you looking at the `pysat_testing2d_xarray` instrument? 

**Proposed Changes**

To maintain compatibility with the `pysat_testing` instrument, I would suggest we keep the interpretation of entering a numeric string as the`sat_id`  keyword as the total number of points to generate. We default to 1 day at a 15 minute resolution (96 points).  Right now there is a `scalar` variable that kind of mimics this behavior, but it is not user customizable and is not used in the xarray test instrument.

Does this meet the requirements both here and in `pysatModelUitls`?

**Comment by aburrell** [comment]
I think it does.

**Comment by jklenzing** [comment]
Working on this update now.

**Comment by rstoneback** [comment]
I was thinking we should upgrade our keywords so they are clearer. Using sat_id is overloading the keyword and is a left over from early pysat development.

How about accepting a frequency string like those used in pandas? keyword sample_frequency? 
keyword sample_num for number of samples. int
sample_offset to allow for a delayed first sample, accepts a pandas.DateOffset.

Or start_time, end_time, num_samples? This could be weird since datetimes like to have dates with them, not just a time.

I think all the instruments should be consistent but only once we sort out what the feature set should be.

**Comment by jklenzing** [comment]
I like these ideas.  Just pushed a new branch up that takes a few steps in this direction.  All test instruments now call a common routine that generates the datetime index for the test instruments.  Additionally:
- `sat_id` is consistently used as total number of data points
- 1D instruments use a 1-sec frequency, 2D instruments use a 15-min frequency

Passing locally, now I just need to see if this works for `pysatModels`.

**Comment by jklenzing** [comment]
Uploaded my current updates as #365.  We could generalize further.  Let me know what you think

**Comment by jklenzing** [comment]
How about `num_samples` and `freq`?

**Comment by rstoneback** [comment]
I think we may end up with a number of keyword arguments for the test routines. To help users out we may want to group related keywords together with a consistent prefix.


@jklenzing @aburrell
I took a pass through open pulls. If you are looking for input/a review and I missed your code/pull/or whatever,  please let me know.

Cheers,
Russell

**Comment by jklenzing** [comment]
Closing with merge of #365 and #368.  Additional keyword discussion moved to #389.
