### ISSUE TITLE
ENH: `Custom.add` api / docstring improvements

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#361]
**Is your feature request related to a problem? Please describe.**
The interface for `Custom.add` can be confusing for developers, in part because one of the keyword options used is `kind='add'`.  Additionally, it is not clear from the docstrings where each of the `kind` options should be used.

**Describe the solution you'd like**
A more clear api would be to rename the function `Custom.attach`, since the goal is to attach functions which may add data products, modify existing data products, or pass a function through.

Additionally, the docstrings and ReadTheDocs should be updated with examples of when to use each of these options.

**Describe alternatives you've considered**
It may be better to rename/reconfigure the options for `kind`.

**Additional context**
From the demo codes, it appears that `add` will add data columns to the dataset and `modify` should be used to select or restrict data.  No use case for `pass` is found.  

Over in pysatMissions, `modify` is inconsistently being used for both `add` and `modify` tasks.  This doesn't seem to create a bug over there, but more testing is needed.

**Comment by aburrell** [comment]
I agree.  I am continuously confused by all of these things.

**Comment by jklenzing** [comment]
Based on the development elsewhere, I'm not sure if `add` and `modify` really need to be separate, but it could be there are bugs / consequences I haven't encountered yet.

**Comment by jklenzing** [comment]
NOTE: If we do change the api, a deprecation warning should be added to pysat before the 2.2.0 release.

**Comment by jklenzing** [comment]
Will implement in 3.0.0.

**Comment by jklenzing** [comment]
Closing with merge of #378 and #379
