### ISSUE TITLE
Potential bug in cosmic_gps.py

### ISSUE THREAD

**Issue by gromeonimo** [pysat/pysat#363]
It appear that when loading several files, and some of them have the identical start time, pysat generate duplicates of the existing profiles, assigning them to all involved files. The issue appears to be coming from the call

output = pysat.DataFrame(load_files(fnames, tag=tag, sat_id=sat_id))

Giuseppe

**Comment by rstoneback** [comment]
Thanks for the report. We will look into it.

**Comment by rstoneback** [comment]
Being addressed in pull #370

**Comment by rstoneback** [comment]
Issue closed due to pull #370 resolution
