### ISSUE TITLE
BUG: load routines drop COSMIC scintillation data for non-unique times

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#364]
**Describe the bug**
The `scnlv1` data for cosmic does not necessarily have unique data times.  This is because there are multiple satellites with multiple fields of view.  Data is being dropped somewhere in the `_instrument` routines.  For instance, Mar 1, 2019 has 658 files, 392 of which have unique timestamps.

**To Reproduce**
```
import pysat
cosmic = pysat.Instrument(platform='cosmic', name='gps', tag='scnlv1')
cosmic.load(date=pysat.datetime(2019, 3, 1))
len(cosmic.data)
```
Produces 392 values.  Now run this manually by getting the list of file names:
```
files = cosmic.files.files  
ind = (files.index.month==3) & (files.index.day==1)    
files = files[ind]
```
Then run applicable code from the `load_files` routine (pasting lines 250-374 from cosmic_gps.py into terminal, along with `_process_lengths` definition), and post-process with
```
output = pysat.DataFrame(output)
utsec = output.hour * 3600. + output.minute * 60. + output.second
output.index = pysat.utils.time.create_datetime_index(year=output.year,
                                                   month=output.month,
                                                   day=output.day,
                                                   uts=utsec)
```
to simulate behavior of `cosmic.load`.  Now running
```
len(output)
```
yields 658, as expected.  Inspecting the data manually shows that these are unique data points.
```
In [157]: output.lat_s4max[:6]                                                                              
Out[157]: 
2019-03-01 09:47:31    57.948
2019-03-01 09:47:31    38.140
2019-03-01 09:47:31    43.408
2019-03-01 09:47:31    16.052
2019-03-01 09:47:31    55.115
2019-03-01 09:47:31    53.793
Name: lat_s4max, dtype: float64

In [158]: output.lon_s4max[:6]                                                                              
Out[158]: 
2019-03-01 09:47:31     -5.644
2019-03-01 09:47:31    123.111
2019-03-01 09:47:31    120.408
2019-03-01 09:47:31    130.848
2019-03-01 09:47:31    111.504
2019-03-01 09:47:31    112.816
Name: lon_s4max, dtype: float64

In [159]: output.prn_id[:6]                                                                                 
Out[159]: 
2019-03-01 09:47:31     2
2019-03-01 09:47:31     7
2019-03-01 09:47:31     8
2019-03-01 09:47:31     9
2019-03-01 09:47:31    16
2019-03-01 09:47:31    27
Name: prn_id, dtype: int64
```

Something outside of the load routines within cosmic_gps.py is dropping the duplicated timestamps.

**Additional context**
This may be related to #363.

**Comment by rstoneback** [comment]
See pull #370

**Comment by jklenzing** [comment]
Digging into this issue deeper, the data is dropped by the cleaning routine.  Oops.

**Comment by rstoneback** [comment]
No worries. Thanks for the update.

**Comment by jklenzing** [comment]
The unique times fix is still needed, just the cause of the bug for days listed above.

**Comment by rstoneback** [comment]
Sorted out in pull #370, closing issue.
