### ISSUE TITLE
FW: pandas.datetime class is deprecated

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#366]
From testing pysat with pandas 1.0.0
```
FutureWarning: The pandas.datetime class is deprecated and will be removed from 
pandas in a future version. Import from datetime instead.
```
From the [what's new](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.0.0.html) section of the pandas documentation, Deprecations are enforced with major updates, meaning this should go away with pandas 2.0.0.

**Comment by jklenzing** [comment]
Note:  All current unit tests pass using pandas 1.0.0 under Travis CI.

https://travis-ci.org/pysat/pysat/builds/644154427?utm_medium=notification&utm_source=github_status

**Comment by jklenzing** [comment]
Open question: do we want to continue to carry around datetime (along with the pandas objects) at the core pysat level?  Or should we just import directly from the appropriate packages?

**Comment by aburrell** [comment]
I think it's better to just import directly when we need them.

**Comment by jklenzing** [comment]
I've tested out what this will look like in #369.  Haven't pulled out the pandas methods yet.  It's a lot of little code changes.

**Comment by jklenzing** [comment]
Here's the rationale behind pandas choice to remove datetime and numpy: https://github.com/pandas-dev/pandas/issues/30296

**Comment by jklenzing** [comment]
closing with merge of #369
