### ISSUE TITLE
TST: keywords for test instruments

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#389]
The test instruments can be expanded and consolidated by allowing additional keywords.  This allows reduction in code duplication (pysat_testing and pysat_testing_xarray are identical except for output structure), as well as makes the test instruments more flexible for downstream packages.  Proposed:
- [x] start_time: allows a start time other than midnight
- [x] num_points: total number of points to generate
- [x] freq: frequency of points, compatible with pandas keyword ('1s', '100s', etc)
- [ ] pandas_format: boolean to switch between pandas and xarray formats

**Comment by jklenzing** [comment]
Note: #266 also needs a multi_file_day option.  Could be solved here.

**Comment by jklenzing** [comment]
PARTIALLY ADDRESSED BY #582.

**Comment by aburrell** [comment]
@jklenzing has this issue been solved?  I believe the tests currently do all the things you want them to do in the description.  If not, perhaps we need an updated scope?

**Comment by jklenzing** [comment]
We still the `pandas_format` and `start_time` keywords to add.

**Comment by aburrell** [comment]
Do we not regularly change those in the unit tests?  I guess I don't understand what this issue is proposing.

**Comment by jklenzing** [comment]
I'll clean up the top level comments.  The point of the pandas change was to combine the `pysat_testing` and `pysat_testing_xarray` objects to reduce code duplication, as only the output differs.  The `start_time` change was a quality of life suggestion at one point so that a test instrument need not start at midnight.

**Comment by jklenzing** [comment]
Remaining tasks here dependent on #873

**Comment by jklenzing** [comment]
Descoping `pandas_format` keyword from roadmap.
