### ISSUE TITLE
Installation documentation needs improvement

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#393]
Currently, the installation documentation in the docs and the README are not useful for anyone who doesn't use pip.  

A solution would be to have a list of all the dependencies that need to be installed for pysat to run.  The pip install command could still live there, but a description of installing from git would be good too.

**Comment by jklenzing** [comment]
We could potentially update this for 2.2 as well, and include some discussion of the roadmap and pandas limitations there.  See #448.

**Comment by jklenzing** [comment]
Closing with merge of #449 and #450
