### ISSUE TITLE
Problem downloading F10.7

### ISSUE THREAD

**Issue by alexchartier** [pysat/pysat#398]
**Describe the bug**
ValueError: time data '02 Jan 2017' does not match format '%H%M UT %d %b %Y'
from:
pysat/instruments/sw_f107.py", line 676, in rewrite_daily_file
    date = pysat.datetime.strptime(date_str, '%H%M UT %d %b %Y')

**To Reproduce**
python3
import pysat_solargeomag
import datetime
stime = datetime.datetime(2016, 6, 11, 0, 0)
etime = datetime.datetime(2016, 6, 17, 0, 0)
pysat_solargeomag.get_historic_f107_data(stime, etime)

**Expected behavior**
Download only the data from 2016/6/11 to 2016/6/17. Do not raise an error - instead produce the .nc file containing the values. 

**Desktop (please complete the following information):**
Linux. Pysat v2.1.0

**Additional context**
On Angeline Burrell's advice, I tried fixing this by deleting pre-existing F10.7 files located in pysat/sw/f107/. That did not fix the problem.

**Comment by alexchartier** [comment]
I suggest this fix:

File: /pysat/instruments/sw_f107.py 

Currently it reads:
	676     date = pysat.datetime.strptime(date_str, '%H%M UT %d %b %Y’)


Replace that line with:
   try:    
       date = pysat.datetime.strptime(date_str, '%H%M UT %d %b %Y')
   except ValueError:
       date = pysat.datetime.strptime(date_str, '%d %b %Y’)

**Comment by alexchartier** [comment]
(tab spaces lost in posting)

**Comment by rstoneback** [comment]
Hi Alex,

  Thanks for the report. I presume you are using 'prelim' data?

    f107 = pysat.Instrument('sw', 'f107', tag='prelim')
    import datetime
    stime = datetime.datetime(2016, 6, 11, 0, 0)
    etime = datetime.datetime(2016, 6, 17, 0, 0)
    f107.download(stime, etime)

produces the error for me.

I created a new branch, f107_bug, that removes the date parsing.

**Comment by alexchartier** [comment]
I used both of them I think.

See my second comment for a fix - I have tested and found no problems with that so far

________________________________

**Comment by rstoneback** [comment]
Yes, thanks for the potential fix. Turns out the parsed date isn't used so I went ahead and removed that area in pull #399 . I think there will be a couple more corrections going into the code.

There are two f107 files that go through that particular bit of code, 'prelim' and 'daily.' I didn't encounter the issue with daily. The 'forecast' and '45day' files have a different path.

**Comment by rstoneback** [comment]
Closed with merge of pull #399
