### ISSUE TITLE
bad f10.7/f10.7a values from 2014

### ISSUE THREAD

**Issue by alexchartier** [pysat/pysat#408]
**Describe the bug**
-1s in F107 and F107a on 2014-056 and -058 respectively. These are not present in the data from NASA/OMNI. 

dtype=int32), 'f107': masked_array(data=[ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 174, 174, 174,
                   174, 174, 174, 174, 174, 172, 172, 172, 172, 172, 172,
                   172, 172],

            dtype=int32), 'f107a': masked_array(data=[154.89285, 154.89285, 154.89285, 154.89285, 154.89285,
                   154.89285, 154.89285, 154.89285, 155.81464, 155.81464,
                   155.81464, 155.81464, 155.81464, 155.81464, 155.81464,
                   155.81464,  -1.     ,  -1.     ,  -1.     ,  -1.     ,
                    -1.     ,  -1.     ,  -1.     ,  -1.     ],

**To Reproduce**

f107_kp, ap = pysat_solargeomag.get_f107_kp_ap(
        'tmp.nc', datetime.datetime(2014, 2, 25, 5, 0), datetime.datetime(2014, 2, 28, 0, 0),
    )   

**Expected behavior**
Positive F10.7 values, like they have in the database

**Comment by rstoneback** [comment]
Thanks for the report.

I checked the 'prelim' F10.7 data and the values I get are ok there.

`f107 = pysat.Instrument(platform='sw', name='f107', tag='prelim')`
`f107.load(2014, 54)`
`f107[start:stop, 'f107']`

Out[29]: 
2014-02-25    174
2014-02-26    178
2014-02-27    176`

Similarly for the standard files,
`f107 = pysat.Instrument(platform='sw', name='f107')`
`In [61]: f107.load(2014, 56)`
`In [62]: f107.data`
Out[62]: 
             f107
2014-02-25  170.4

`In [63]: f107.load(2014, 58)`
`In [64]: f107.data`
Out[64]: 
             f107
2014-02-27  172.4

I'm not familiar with the pysat_solargeomag code. How is it getting F10.7 values?

**Comment by aburrell** [comment]
Here's a sample code that's what this routine uses:

```
import pysat
import datetime as dt

stime=dt.datetime(2014,2,24)
etime=dt.datetime(2014,2,26)

 all_inst = pysat.Instrument('sw', 'f107', 'all')
prelim_inst = pysat.Instrument('sw', 'f107', 'prelim')

all_inst.download()
prelim_inst.download(start=stime, stop=etime)

f107_inst = sw_methods.combine_f107(all_inst, prelim_inst, start=stime,
                                        stop=etime)
```

**Comment by rstoneback** [comment]
Thanks! Code works for me in python 2 and 3. So far it seems like we may be loading different versions of the files. Outputs below.

`In [68]: import pysat.instruments.methods.sw as sw_methods
`

```
In [72]: import pysat
    ...: import datetime as dt
    ...: 
    ...: stime=dt.datetime(2014,2,24)
    ...: etime=dt.datetime(2014,2,27)
    ...: 
    ...: all_inst = pysat.Instrument('sw', 'f107', 'all')
    ...: prelim_inst = pysat.Instrument('sw', 'f107', 'prelim')
    ...: 
    ...: all_inst.download()
    ...: prelim_inst.download(start=stime, stop=etime)
    ...: 
    ...: f107_inst = sw_methods.combine_f107(all_inst, prelim_inst, start=stime,
    ...:                                         stop=etime)
    ...: 

```
  

```
In [73]: f107_inst.data
Out[73]: 
             f107
2014-02-24  167.2
2014-02-25  170.4
2014-02-26  174.7
```

I also looked at Kp data and it is present.

```
In [4]: kp = pysat.Instrument('sw', 'kp')                                                                              
In [5]: kp.download(stime, etime)                                                                                      

In [12]: kp.load(2014, 56)                                                                                             
In [13]: kp.data                                                                                                       
Out[13]: 
                           Kp
time                         
2014-02-25 00:00:00  0.666667
2014-02-25 03:00:00  0.000000
2014-02-25 06:00:00  0.000000
2014-02-25 09:00:00  0.666667
2014-02-25 12:00:00  1.000000
2014-02-25 15:00:00  0.666667
2014-02-25 18:00:00  0.333333
2014-02-25 21:00:00  2.000000

In [14]: kp.load(2014, 58)                                                                                             
In [15]: kp.data                                                                                                       
Out[15]: 
                           Kp
time                         
2014-02-27 00:00:00  0.666667
2014-02-27 03:00:00  1.000000
2014-02-27 06:00:00  0.333333
2014-02-27 09:00:00  0.666667
2014-02-27 12:00:00  2.666667
2014-02-27 15:00:00  4.000000
2014-02-27 18:00:00  5.333333
2014-02-27 21:00:00  5.333333
           
```          

Wider timespan also works for me.

```
stime=dt.datetime(2014,1,1) 
etime=dt.datetime(2014,2,28) 

```
```
f107_inst.data                                                                                                
Out[18]: 
             f107
2014-01-01  154.3
2014-01-02  155.2
2014-01-03  176.3
2014-01-04  206.2
2014-01-05  210.3
2014-01-06  197.2
2014-01-07  229.3
2014-01-08  188.2
2014-01-09  178.1
2014-01-10  169.4
2014-01-11  160.7
2014-01-12  150.2
2014-01-13  138.7
2014-01-14  132.6
2014-01-15  122.1
2014-01-16  117.1
2014-01-17  124.7
2014-01-18  125.5
2014-01-19  123.4
2014-01-20  133.0
2014-01-21  141.4
2014-01-22  138.9
2014-01-23  132.1
2014-01-24  131.3
2014-01-25  129.1
2014-01-26  133.7
2014-01-27  139.6
2014-01-28  152.5
2014-01-29  151.8
2014-01-30  155.8
2014-01-31  160.9
2014-02-01  171.6
2014-02-02  184.4
2014-02-03  183.0
2014-02-04  182.9
2014-02-05  188.1
2014-02-06  186.1
2014-02-07  173.2
2014-02-08  167.2
2014-02-09  164.6
2014-02-10  156.8
2014-02-11  167.8
2014-02-12  156.1
2014-02-13  162.5
2014-02-14  162.5
2014-02-15  158.1
2014-02-16  150.2
2014-02-17  148.9
2014-02-18  147.9
2014-02-19  154.2
2014-02-20  153.0
2014-02-21  153.4
2014-02-22  159.7
2014-02-23  168.2
2014-02-24  167.2
2014-02-25  170.4
2014-02-26  174.7
2014-02-27  172.4  
```

**Comment by rstoneback** [comment]
I tried the master, develop, and develop-3 branches.

**Comment by alexchartier** [comment]
Russell and Angeline's tests worked because they used different times than I specified at the top. The problem seems to be caused by the handling of fractional days (datetimes not at 0 UT). 

This is not picked up or reported by Pysat - maybe the download() method should remove any nonzero hours/minutes/seconds from datetimes passed to it? 

Pysat should not return F10.7 = NaN on 2014/2/25 as it does here:

import datetime
import pysat
from pysat.instruments.methods import sw as sw_methods

stime = datetime.datetime(2014, 2, 25, 5, 0)
etime = datetime.datetime(2014, 2, 28, 0, 0)

all_inst = pysat.Instrument('sw', 'f107', 'all')
prelim_inst = pysat.Instrument('sw', 'f107', 'prelim')

all_inst.download()
prelim_inst.download(start=stime, stop=etime)

f107_inst = sw_methods.combine_f107(all_inst, prelim_inst, start=stime,
                                        stop=etime)
print(f107_inst['f107'])

2014-02-25      NaN
2014-02-26    174.7
2014-02-27    172.4

 pysat.__version__
'2.1.0'

**Comment by rstoneback** [comment]
Hi Alex,

 Thank you for the clarification. The download method does strip hours/minutes/seconds from a supplied date time when downloading data, though the NaN is popping up from the combine_f107 method since the start time input is past the start time of the loaded data. 

```
In [11]: import datetime
    ...: import pysat
    ...: from pysat.instruments.methods import sw as sw_methods
    ...: 
    ...: stime = datetime.datetime(2014, 2, 25, 5, 0)
    ...: stime2 = datetime.datetime(2014, 2, 25, 0, 0)
    ...: etime = datetime.datetime(2014, 2, 28, 0, 0)
    ...: 
    ...: all_inst = pysat.Instrument('sw', 'f107', 'all')
    ...: prelim_inst = pysat.Instrument('sw', 'f107', 'prelim')
    ...: 
    ...: all_inst.download()
    ...: prelim_inst.download(start=stime, stop=etime)
    ...: 
    ...: f107_inst = sw_methods.combine_f107(all_inst, prelim_inst, start=stime2,
    ...: stop=etime)
    ...: print(f107_inst['f107'])
    ...: 
```

Returning sw f107 all data for 25 February 2014
2014-02-25    170.4
2014-02-26    174.7
2014-02-27    172.4
Name: f107, dtype: float64

**Comment by rstoneback** [comment]
I've had a chance to talk with pysat developers and we agree that the routine is behaving as intended and documented with respect to the input datetime type. For some users and cases it may be desirable to only consider the day portion but that requires pysat to ignore a users input. Generally speaking that could likely lead to more user confusion, particularly for those users that are trying to analyze only a portion of the data. While in this case an output NaN is not desired it is consistent with the dates and times provided to the method.

pysat is currently designed in some areas to operate on a daily basis, such as downloading and loading data. However as most datasets have many values within a day there are no analysis assumptions or restrictions that operations must include every sample within a day. To the extent possible pysat is also starting to chip at the daily basis assumptions. We are beginning work to support loading date ranges and this feature will use both the date and time provided by the user. 

There is a method attached to each instrument object 
`date = inst._filter_datetime_input(date)`
that may be used for users that are operating strictly on a daily basis that filters out everything but the date. I'll discuss making this method more visible at the next pysat developer meeting.
