### ISSUE TITLE
'Altitude' variable needed in pysat 'testing' and 'testing_xarray' instruments

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#410]
One problem we have when testing the behaviour of many pysat instruments is that we need an altitude dimension, and this is not provided in the pysat 'testing' and 'testing_xarray' objects.

I would like 'Altitude' to be provided by default in these instruments. 

Currently, tests that require altitude must write a special loading function that adds this variable when loading the pysat instrument object.  However, this is such a common need that it results in a lot of duplicate code.

**Comment by jklenzing** [comment]
Closing with merge of #411
