### ISSUE TITLE
Update to newer version of pandas

### ISSUE THREAD

**Issue by walchko** [pysat/pysat#448]
Is there a reason you limit `pandas` to such an old version (here)[https://github.com/pysat/pysat/blob/e84002e57f8a808d35562f51ce957361d99c4070/setup.py#L34] in `setup.py`? Can you update to a newer version? The current version is 1.0.5.

```
else:
    # python 3+
    install_requires.extend(['xarray', 'pandas>=0.23, <0.25', 'numpy>=1.12',
                             'scipy', 'matplotlib'])
```

**Comment by jklenzing** [comment]
Short answer:  This has been updated as part of the upcoming pysat 3.0.0 release, which is fully compliant with pandas 1.0.5.  You can access this in the `develop-3` branch.

Long answer: There's a handful of older functions in the code that rely on the deprecated `pandas.Panel` function for seasonal analysis of data.  As part of our larger roadmap, these have been moved to a new analysis package `pysatSeasons`: https://github.com/pysat/pysatSeasons.  The intent is to rewrite these using `xarray` so the caps can be removed, but development focus is currnently on completing the updates to the core package.

Thanks for checking out the project!

**Comment by walchko** [comment]
ok, thanks!
