### ISSUE TITLE
DOC: Survey documentation for v2.2 release

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#464]
**Is your feature request related to a problem? Please describe.**
Documentation in areas needs improvement and corrections. Focus needs to be paid on the new instrument section given that is where most challenges occur. The documentation across instrument docstrings is inconsistent and sometimes incorrect.

**Describe the solution you'd like**
Some time needs to be invested in existing areas.

**Describe alternatives you've considered**
Do nothing?

**Additional context**
A higher level organization discussion needs to happen so that users have some clarity when looking at the documentation about where info about a particular method may be outside the API.

**Comment by jklenzing** [comment]
Closing with merge of #469, #480, #482.
