### ISSUE TITLE
Seasonal Averaging and xarray

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#47]
The current seasonal average supports a wiede variety of data in the pandas format, and all of it gets aligned as needed. With the basics of xarray in the xarray-init branch, support for this data format needs to be added to seasonal averaging.

**Comment by jklenzing** [comment]
Linking to #159.  Panel deprecation warning suggests switching to xarray.  Perhaps there is a unified way of handling this?

**Comment by rstoneback** [comment]
That is a possibility, hence the push to get xarray as a data format.

I’m still not familiar enough with using xarray to have a good feel if things will work out.
So far, xarray isn’t as easy to use.

On Feb 22, 2019, at 11:40 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


Linking to #159<https://github.com/rstoneback/pysat/issues/159>. Panel deprecation warning suggests switching to xarray. Perhaps there is a unified way of handling this?

**Comment by jklenzing** [comment]
Migrating to pysat/pysatSeasons#3 and closing here.
