### ISSUE TITLE
BUG: xarray data access

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#471]
There is a possible bug with how we access xarray data found in #468. While that specific issue was solved by using xarray notation to bypass the index acces via pysat, the error analysis is documented here to help with future flake8 compliance pulls and potential bugs in other instruments.  The issue arises when trying to set 2D data via indices, ie, 
```
inst = pysat.Instrument(platform='icon', name='mighti', tag='vector_wind_green', clean_level='none')
inst.load(2020, 2)
idx, idy, = np.where(inst['Wind_Quality'] != 1)
inst[idx, idy, 'Zonal_Wind'] = np.nan
```
This can be traced to the `except` path here:
https://github.com/pysat/pysat/blob/ec813443c71cd1ae000d6f93d1386d1dfc5caba5/pysat/_instrument.py#L565-L569

The error triggered at 568 is 
```
IndexError: arrays used as indices must be of integer or boolean type
```
It's possible that the real error is masked by the bare except statement.  If I remove the try/except statement to force the main line, I get the following error at 566
```
KeyError: "not all values found in index 'Altitude'"
```

Solution needed: sort out what error the except statement is supposed to catch, then debug from there.

**Comment by jklenzing** [comment]
Tracked down the source of the error.  When passing >1D data, the except statement winds up trying to pass mixed indices (in the case above, a datetime index and integers).  This needs to be updated using the latest xarray standards.

https://xarray.pydata.org/en/stable/indexing.html#

**Comment by jklenzing** [comment]
NOTE: this issue affects `setitem` and `getitem` in the `Instrument` class

**Comment by rstoneback** [comment]
Worth reviewing the whole setitem and getitem codes while working on this one.

**Comment by jklenzing** [comment]
Closing with merge of #647
