### ISSUE TITLE
Instrument nomenclature

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#473]
**Is your feature request related to a problem? Please describe.**
The problem is that a basic `Instrument` parameter is `sat_ids`.  This name is confusing for anything that isn't a satellite, and for some satellites as well.  

**Describe the solution you'd like**
A better name would be `inst_ids`, since this is an ID that is used for all pysat `Instrument`s.

**Describe alternatives you've considered**
To leave things as-is.

**Additional context**
This is especially confusing for the pysatModels instruments.  As this is a breaking change, the best time to do this would be in 3.0.0.  A deprecation warning would need to be issued in 2.2.0.

**Comment by rstoneback** [comment]
I like the suggestion. There has been some other talk about changing the Instrument instantiation parameters to include another category as well. I'll see if I can track that down. We should do this at the same time for v3.0

**Comment by rstoneback** [comment]
From pull #123 I made a comment,

> We currently have:
platform / name (instrument) / sat_id / tag
Proposal:
platform / name / sat_id / level / product

Instrument parameters and directory structure:
so platform / name / inst_id / level / product

**Comment by rstoneback** [comment]
I checked with @jklenzing on GOLD and four parameters turned out to be sufficient, 
platform / name / inst_id / level / tag

**Comment by aburrell** [comment]
So... do we want to add `level` as a `pysat.Instrument` attribute, similar to `inst_id` and `tag`?

**Comment by aburrell** [comment]
After discussion at the meeting today, we decided not to include `level`.

**Comment by jklenzing** [comment]
Closing with merge of above pulls.
