### ISSUE TITLE
BUG: Instrument metadata labels are left free

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#483]
**Describe the bug**
The metadata parameter labels, inst.units_label, aren't hooked up to anything after instantiation. If a user changes them, code can break.

If a user changes the labels at the metadata level, that change does go through.

**To Reproduce**
1. inst = pysat.Instrument('pysat', 'testing')
2. inst.units_label = 'broken'
3. inst.meta[variable, inst.units_label] doesn't work

**Expected behavior**
The labels between the Instrument object and metadata object need to remain in sync.

**Comment by rstoneback** [comment]
remove from instruments. Make naming more consistent. meta.labels.units or meta.labels.desc, etc. One and only one place to set things.

**Comment by rstoneback** [comment]
> remove from instruments. Make naming more consistent. meta.labels.units or meta.labels.desc, etc. One and only one place to set things.

While working on the code for another issue I remembered that we need to store the labels on the instrument side since meta keeps getting replaced with every load. Removing them should be interpreted as hiding them. We could protect them instead but the visible presence of attributes, in two locations, one set that can be changed, the other not, seems confusing.

**Comment by aburrell** [comment]
Create a labels class that is used by both Instrument and Meta

**Comment by aburrell** [comment]
I think this is addressed by #587 @rstoneback @jklenzing ?

**Comment by jklenzing** [comment]
I think this is right.

**Comment by aburrell** [comment]
Ok, I have been thinking about this more through the day.  I think #587 could reasonably be said to address this, but I think we could further address it by removing the instance if MetaLabels held by the Instrument object.  This would mean we'd need to go through and replace all 'inst.labels.xxx' calls with 'inst.meta.labels.xxx' calls instead.  But I think it would work and reduce the weight of the Instrument object.  Thoughts?

**Comment by rstoneback** [comment]
> I think this is addressed by #587 @rstoneback @jklenzing ?

I don't think so. If a change is made to the labels on inst it won't appear on meta until the next load. I think the labels on inst would need to be a property so that it can automatically transfer the labels to meta whenever there is a change.

Going to confirm by checking the behavior. Y'all move fast.

**Comment by rstoneback** [comment]
> Ok, I have been thinking about this more through the day. I think #587 could reasonably be said to address this, but I think we could further address it by removing the instance if MetaLabels held by the Instrument object. This would mean we'd need to go through and replace all `inst.labels.xxx` calls with `inst.meta.labels.xxx` calls instead. But I think it would work and reduce the weight of the Instrument object. Thoughts?

The labels needs to remain on Instrument since it stores the labels a user picks. Meta gets replaced with every load.

**Comment by rstoneback** [comment]
```
In [1]: import pysat                                                                                                                                                                                                        

In [2]: test = pysat.Instrument('pysat', 'testing')                                                                                                                                                                         

In [3]: test.load(2009, 1)                                                                                                                                                                                                  
<ipython-input-3-c4961dc4892a>:1: UserWarning: Metadata set to defaults, as they were missing in the Instrument
  test.load(2009, 1)

In [4]: test.meta.labels.units                                                                                                                                                                                              
Out[4]: 'units'

In [5]: test.labels.units = 'new_label'                                                                                                                                                                                     

In [6]: test.meta.labels.units                                                                                                                                                                                              
Out[6]: 'units'
```
Also looks like we are missing some metadata :)

**Comment by aburrell** [comment]
Ok, in that case I think we can close this?  Looking for confirmation so I don't jump the gun...

**Comment by rstoneback** [comment]
No, I don't think we can close it. The steps at the top don't work yet.

**Comment by rstoneback** [comment]
I've been thinking about this, not sure the property thing will work given the setting happens within the labels class, not at the instrument level.

**Comment by rstoneback** [comment]
I'm typing too much without enough planning. There is the auto-update on meta itself.

**Comment by rstoneback** [comment]
> Ok, I have been thinking about this more through the day. I think #587 could reasonably be said to address this, but I think we could further address it by removing the instance if MetaLabels held by the Instrument object. This would mean we'd need to go through and replace all `inst.labels.xxx` calls with `inst.meta.labels.xxx` calls instead. But I think it would work and reduce the weight of the Instrument object. Thoughts?

I think you are right @aburrell. inst.labels can go to inst._labels, leaving inst.meta.labels as the primary visible interface, and as stated all pysat code should 
> replace all `inst.labels.xxx` calls with `inst.meta.labels.xxx` calls

and then its done.

**Comment by rstoneback** [comment]
> Ok, I have been thinking about this more through the day. I think #587 could reasonably be said to address this, but I think we could further address it by removing the instance if MetaLabels held by the Instrument object. This would mean we'd need to go through and replace all `inst.labels.xxx` calls with `inst.meta.labels.xxx` calls instead. But I think it would work and reduce the weight of the Instrument object. Thoughts?

Ok, I was still a bit behind. You are correct. The labels that is there on the inst doesn't need to be there.
