### ISSUE TITLE
DOC: Transfer updated documentation and updated docstrings to develop-3

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#486]
**Is your feature request related to a problem? Please describe.**
Documentation in v2.2 is ahead of develop-3. 

**Describe the solution you'd like**
Bring in the variety of updates to documentation and docstrings over to develop-3.
Branches - docs2_v22_update
Clean out the variety of branches created in the final fury as well.

**Describe alternatives you've considered**
Doing nothing has a cost to pay eventually

**Additional context**

**Comment by jklenzing** [comment]
The new docstrings for the ICON instruments should be up in #441.  Need to start a pull with the others

**Comment by jklenzing** [comment]
ucar_tiegcm is now handled at pysat/pysatModels#58

**Comment by jklenzing** [comment]
Areas left to clean / update
- [ ] core
- [ ] constellations
- [ ] instruments -- #487 
- [ ] instrument methods / templates
- [ ] utils
- [x] pysatMadrigal (migrated code) -- pysat/pysatMadrigal#9
- [x] pysatModels (migrated code) -- pysat/pysatModels#58
- [ ] pysatSeasons (migrated code)

**Comment by rstoneback** [comment]
pull #489 also has some documentation updates.

**Comment by rstoneback** [comment]
The documentation in docs has been transferred, along with the other late game v2.2 bug fixes.

**Comment by rstoneback** [comment]
I didn't see any documentation changes related to constellations, or utils/, or _instrument.py in v2.2.x that wasn't in develop-3. I think this is complete.

**Comment by rstoneback** [comment]
@jklenzing are there specific items that need to be changed that you know of for the unchecked areas?

**Comment by jklenzing** [comment]
I think those are just docstring scrubs

**Comment by jklenzing** [comment]
I'll get these in this afternoon

**Comment by jklenzing** [comment]
This should be done from my notes.  Can probably close it unless there is something else to add.
