### ISSUE TITLE
DOC: ReadTheDocs Not Building

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#488]
**Describe the bug**
ModuleNotFoundError: No module named 'h5py'

**To Reproduce**
On RTD

**Expected behavior**
Built documentation

**Screenshots**

**Additional context**
It is a fortran module. From memory, could be solved with mock, makes it looks like it exists on RTD when it doesn't.

RTD reccommends:
https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by jklenzing** [comment]
Something similar is happening at sami2py/sami2py#121, but for numpy.

**Comment by aburrell** [comment]
We can help solve this issue in the future by building the docs for the develop branch as well.  However, I think we should put out a bugfix for 2.2 (2.2.1) for this.

**Comment by rstoneback** [comment]
Agreed. Starting on this now.
