### ISSUE TITLE
ENH: Pull Request Templates

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#498]
**Is your feature request related to a problem? Please describe.**
There is only one pull request template though it doesn't specifically have a checklist for more than one type of pull.

**Describe the solution you'd like**
Additional templates for more situations.
Pull request into standard branch.
Pull request into Release Candidiate (?)
Pull request into main branch

**Comment by aburrell** [comment]
GitHub currently does not support more than one PR template.  I added additional guidance for release pull requests in PR #551 .
