### ISSUE TITLE
BUG: Instrument Data Access

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#504]
**Describe the bug**
Selecting multiple variables at once doesn't work like it used to.

**To Reproduce**

inst = pysat.Instrument('pysat', 'testing')
# this works
inst[:, ['uts', 'mlt']]
# this doesn't work in v2.2.1 but it does in v2.1
# v2.2.1 
inst[['uts', 'mlt']]
ValueError: invalid literal for int() with base 10: 'uts'

# v2.1
In [4]: inst[['uts', 'mlt']]
Out[4]: 
                       uts        mlt
Epoch                                
2009-01-01 00:00:00      0   0.000000
2009-01-01 00:00:01      1   0.004124
2009-01-01 00:00:02      2   0.008247
2009-01-01 00:00:03      3   0.012371
2009-01-01 00:00:04      4   0.016495
2009-01-01 00:00:05      5   0.020619

**Expected behavior**
Same as v2.1

**Comment by jklenzing** [comment]
My suspicion is that this is related to the removal of bare except statements in _instrument.  There's about 4 of these related to set and get.
Example:
https://github.com/pysat/pysat/blob/2177e1eb0947d073f64cabe47dbc27ab7093a219/pysat/_instrument.py#L412-L417

Try adding ValueError to the exceptions.

If that solves it, we'll need a new test too.  I don't think I test for that particular one.

**Comment by rstoneback** [comment]
Thanks Jeff! I’ll try it out. I only had one use of that notation so my quick fix was to update that. When I get done processing some data I’ll check this fix out. Cheers.

**Comment by jklenzing** [comment]
Included the fix in #502 for python 3.0.  Let's discuss whether another patch is planned for 2.2 at the meeting tomorrow.

**Comment by jklenzing** [comment]
After the pysat meeting, decision not to patch this bug in 2.2 as the use case is not a documented way in the example code.

Closing with merge of #502
