### ISSUE TITLE
BUG: custom.attach not the same in v2.2.x as v3.x

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#506]
**Describe the bug**
custom.attach in v2.2.1 does not have the same method signature as custom.attach in v3.0. The signature for attach in v2.2.1 follows that of add. To ensure compatibility across versions this should be updated.

This matters when supplying keyword and argument values while setting the custom method.

**Comment by jklenzing** [comment]
We discussed dropping this at the meeting today.  Do we still need to do anything here?

**Comment by aburrell** [comment]
I think we need to add a deprecation warning.

**Comment by rstoneback** [comment]
If we release another version to include a deprecation warning for attach we might as well just fix it.

**Comment by aburrell** [comment]
Except that will break people code without warning them.  I'd rather not go update OCBpy again because of this.
