### ISSUE TITLE
ENH: Add support for registering multiple instrument modules at once

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#516]
**Is your feature request related to a problem? Please describe.**
pysat* packages are organized via pysat*.instruments. ... with multiple instrument modules under pysat*.instruments.
Currently, these individual instruments have to be registered individually.

**Describe the solution you'd like**
Be able to supply pysat*.instruments and have each instrument within registered

**Describe alternatives you've considered**
Current situation.

**Comment by jklenzing** [comment]
Possibilities:
- auto register during installation
- auto register during first import
- ask the user if they want to register all instruments during first import
- only have manual registration (all instruments)
- manual registration (selective instruments)

**Comment by rstoneback** [comment]
To add to the list I was thinking we could have each pysat* package register itself when installed. 

I think the autoimport on first use could be good though perhaps that needs a switch. 
Operational users may prefer that pysat remain static unless otherwise specifically directed. 

We need some support to add a switch, it is an issue.

**Comment by rstoneback** [comment]
The registry module was updated to provide a few easy to use mechanisms for registering one or more instruments at a time. These may be used by pysat dependent packages to register themselves upon installation.
