### ISSUE TITLE
DOC: pysat 3.0.0 specific documentation changes

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#528]
**Describe the bug**
The current documents in develop-3 assume that the pysat structure is the same as pysat 2. 

**Solution**
A minimal list of areas to fix is:

- [x] docs/api
- [x] docs/citing
- [x] docs/dependency
- [x] docs/ecosystem
- [x] docs/analysis/*
- [x] docs/instruments/*
- [x] docs/examples
- [x] docs/faq
- [x] docs/installation
- [x] docs/introduction
- [x] docs/new_instrument
- [x] docs/quickstart
- [x] docs/tutorial/tutorial_basics
- [x] docs/tutorial/tutorial_custom
- [x] docs/images/pysat_load_flow_chart.png + docs/tutorial/tutorial_load.rst - @rstoneback 
- [x] docs/tutorial/tutorial_full_independence
- [x] docs/tutorial/tutorial_independence
- [x] docs/tutorial/tutorial_iteration
- [x] docs/tutorial/tutorial_orbit
- [x] docs/tutorial/tutorial_v3_upgrade

**Comment by rstoneback** [comment]
[ ] tutorial_basics.rst has the old `units_label` notation rather than the updated `labels.units`

**Comment by aburrell** [comment]
V3 upgrade needs to include directions for updating the local files.  Whatever is there didn't move any of my files and if we don't have a file moving method, we need to tell people how to do so.

**Comment by rstoneback** [comment]
> V3 upgrade needs to include directions for updating the local files. Whatever is there didn't move any of my files and if we don't have a file moving method, we need to tell people how to do so.

The update_data_directory thing in the tutorial_v3_upgrade documentation didn't work?

**Comment by aburrell** [comment]
Nope, it didn't :(. I can try to go through it again, but I've already manually updated part of my system to continue to work on the tutorials.  Maybe Jeff can test?

**Comment by rstoneback** [comment]
> Nope, it didn't :(. I can try to go through it again, but I've already manually updated part of my system to continue to work on the tutorials. Maybe Jeff can test?

That is weird. It worked on my system with multiple tests and tests run on Travis. What did it say when it didn't work?

**Comment by aburrell** [comment]
It failed silently.  I only found out when I tried to load data.

**Comment by aburrell** [comment]
Perhaps I did things wrong, though...

**Comment by rstoneback** [comment]
> It failed silently. I only found out when I tried to load data.

Do I have a copy of the command in your terminal history?

**Comment by rstoneback** [comment]
By default that function runs in test_mode. That could produce no errors and it definitely won't move the files.

**Comment by aburrell** [comment]
Yeah, I recall setting that to False.  You explained that part well!

**Comment by rstoneback** [comment]
> Yeah, I recall setting that to False. You explained that part well!
> 
> And no, that was a week+ ago.

In this case it sucks I explained that well since that flag is perhaps the only simple reason why the files wouldn't be moved without an error.
