### ISSUE TITLE
test_instrument.py duplicate code

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#532]
**Is your feature request related to a problem? Please describe.**
There are many tests in test_instrument.py that could be combined using parametrization

**Describe the solution you'd like**
Combine suitable tests using `@pytest.mark.parametrize`

**Describe alternatives you've considered**
Leaving alone

**Comment by jklenzing** [comment]
linking to #870

**Comment by jklenzing** [comment]
Closing with merge of #899

**Comment by jklenzing** [comment]
Remaining duplication issues documented as #902.
