### ISSUE TITLE
Check out weakref use on Files

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#534]
**Describe the bug**
eval(repr(inst.files)) will sometimes (mostly) fail complaining about the weakly refined object not being there.

**To Reproduce**
1. import pysat.Files as Files
2. inst = pysat.Instrument('pysat', 'testing)
3. eval(repr(inst.files))

**Expected behavior**
Reproduce the Files instance

**Screenshots**

**Desktop (please complete the following information):**
 - Other details about your setup that could be relevant

**Additional context**

**Comment by aburrell** [comment]
This may be a useful reference: https://pymotw.com/2/weakref/

**Comment by rstoneback** [comment]
`weakref` was removed in a pull. It is now in the pysat v3 release candidate branch as well as the develop-3 branch.
https://github.com/pysat/pysat/commit/b0b6af7676d2c9cdcf36f5ab0d352074d9d2344b
