### ISSUE TITLE
Supported tag and inst_id check

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#537]
**Describe the bug**
Users may forget and supply an incorrect tag or sat_id. pysat should use the latest pysat Instrument standards that specifies which tags/ids are accepted to perform this check automatically. Be sure and support all tags or ids, aka '*'.

**To Reproduce**
1. create a pysat.Instrument that requires a tag or sat_id and don't provide one
2. Potentially See error
3. Some Instruments perform their own check

**Expected behavior**
A clear and concise description of what is wrong when a missing or incorrect parameter is supplied.

**Additional context**
We shouldn't force every instrument to perform this error check.

**Comment by aburrell** [comment]
See #67

**Comment by jklenzing** [comment]
Link to #67

**Comment by jklenzing** [comment]
Currently a check in `list_files` under general methods.  Need to add in `_instrument` for universal support.
