### ISSUE TITLE
Check standards for pysat.Instrument templates

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#538]
**Is your feature request related to a problem? Please describe.**
Review the template instrument to ensure it is up to the latest standards, particularly with regard to error checking in methods. This code should set the standard for proper pysat style.

**Describe the solution you'd like**
A great template file to start with when adding support for a new instrument.

**Describe alternatives you've considered**
Current system

**Additional context**

**Comment by jklenzing** [comment]
Closing with merge of #571
