### ISSUE TITLE
Constellation method `data_mod`

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#540]
**Is your feature request related to a problem? Please describe.**
The constellation method `data_mod` performs `custom.attach` on all instruments in the constellation.  The inputs are *args and **kwargs, although this does not conform to the docstring.

**Describe the solution you'd like**
Change the method name to something more consistent with the Instrument class and make the inputs match the docstring.

**Describe alternatives you've considered**
Keep things as they are, but update the docstring.

**Comment by jklenzing** [comment]
Could be generalized for other methods
