### ISSUE TITLE
.pysat file structure

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#542]
**Is your feature request related to a problem? Please describe.**
There are many hidden instrument files in the .pysat directory

**Describe the solution you'd like**
I would like all of these files to be in a .pysat/instrument directory

**Describe alternatives you've considered**
Leaving it alone

**Additional context**
This is a breaking change

**Comment by jklenzing** [comment]
Possibility: Store current instruments lists in `.pysat/instruments`, store old lists in `.pysat/instruments/archive`
