### ISSUE TITLE
Lots of duplication in `Meta.__eq__`

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#543]
**Describe the bug**
There is a lot of duplicate code in `Meta.__eq__`

**Expected behavior**
Create smaller routines that allow the current routine to be simplified and easier to read.

**Comment by rstoneback** [comment]
It's been on my internal list but better for it to be tracked. Thanks.

**Comment by aburrell** [comment]
Looking more closely at this, a lot could be simplified by defining some test functions that could also be used in unit/integration tests (e.g., an `assert_lists_equal` function).  I am also curious why Meta got an `__eq__` method and the other major classes didn't.

```
def assert_lists_equal(list_one, list_two):
    assert len(list_one) == len(list_two)
    for val in list_one:
        assert val in list_two
    return

# Use in Meta.__eq__
try:
    assert_lists_equal(list_one, list_two)
except AssertionError:
    return False
```
