### ISSUE TITLE
Orbit and Meta unit test missing docstrings

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#545]
**Is your feature request related to a problem? Please describe.**
Most of the Orbit unit tests are missing docstrings

**Describe the solution you'd like**
I'd like one line docstrings to be present for all test methods

**Describe alternatives you've considered**
Leaving things as is

**Comment by jklenzing** [comment]
Linking to #565

**Comment by jklenzing** [comment]
Closing with merge of #781 and #864
