### ISSUE TITLE
Pandas SettingWithCoppyWarning

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#546]
**Describe the bug**
A pandas SettingWithCoppyWarning is raised when setting metadata using a series

**To Reproduce**
```
import pysat
inst = pysat.Instrument("pysat", "testing", clean_level="clean")
inst.load(2009, 1)
inst['new_data'] = inst['mlt']
inst['hi'] = inst['mlt']
inst.meta['hi'] = inst.meta['new_data']
```

**Expected behavior**
Meta needs to be changed so that this warning is not raised any longer.

**Comment by jklenzing** [comment]
I think line 642 is the culprit:
https://github.com/pysat/pysat/blob/359dd5b155ed27938e28f199bdeca3a3740a3bc9/pysat/_meta.py#L636-L642
