### ISSUE TITLE
DOC: broken links and incorrect docstring formats

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#553]
**Describe the bug**
The new docs tests introduced to travis currently fail with "build finished with problems, 36 warnings".  

**To Reproduce**
Check out the "docs" test on recent develop-3 travis builds (after #551 is merged, or the #551 tests).

**Expected behavior**
All problems and warnings should be resolved.  Once resolved, the travis allowed failure for this test should be removed.

**Additional context**
You can run this locally using the `sphinx-build` commands on Lines 8 and 9 of the travis yml.

**Comment by jklenzing** [comment]
Broken links addressed in #602, though a number of style problems are still in the logs for the docs tests.

**Comment by jklenzing** [comment]
Outstanding issues documented in #651
