### ISSUE TITLE
BUG: tests for remove 2d names from xarray objects fails locally

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#554]
**Describe the bug**
When running tests locally with `develop-3`, I get failures for two tests that run successfully on travis CI:
```
FAILED pysat/tests/test_methods_general.py::TestRemoveLeadTextXarray::test_remove_2D_names_w_target - RuntimeError: dictionary keys ...
FAILED pysat/tests/test_methods_general.py::TestRemoveLeadTextXarray::test_remove_2D_names_w_target_list - RuntimeError: dictionary ...
```
The full error message originates from _meta.py
```
    def keys_nD(self):
        """Yields keys for higher order metadata"""
    
>       for ndkey in self.ho_data:
E       RuntimeError: dictionary keys changed during iteration

pysat/_meta.py:964: RuntimeError
```
**To Reproduce**
```
pytest pysat/tests/test_methods_general.py::TestRemoveLeadTextXarray
```

**Expected behavior**
All tests should succeed.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.15.6
 - Python 3.8.2
 - numpy 1.18.5 (also tested 1.19.2)
 - scipy 1.5.0
 - pandas 1.1.2 (also tested 1.0.5)
 - xarray 0.16.0

**Additional context**
This is likely due to my system setup, but it could be a new package change in one of the requirements, hidden or otherwise. Not seeing any significant differences between my setup and travis though (other than 3.8, which seems to work fine the travis_docs branch).  Any other dependencies I should check?

**Comment by aburrell** [comment]
This is addressed in #551

**Comment by aburrell** [comment]
It was a bug in the way the test got the keys (not strictly python 3 compliant).

**Comment by jklenzing** [comment]
Confirmed that the new branch works.  Thanks!
