### ISSUE TITLE
Python 2 clean up

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#564]
**Describe the problem**
Many of the files still include imports that are left over support for python 2:

- `from importlib import reload as re_load`
- `from __future__ import blah`

**Expected behavior**
These should be removed, and reload should not be given a nickname.

**Comment by jklenzing** [comment]
Closing with merge of #570

**Comment by aburrell** [comment]
I found some instances of `sys.version_info.major == 2` in the code. (seen in _instrument.py).

**Comment by jklenzing** [comment]
Just did a sweep of develop-3.  No instances of `sys.version_info.major` in the code.  This was addressed somewhere, but I don't remember where.

**Comment by jklenzing** [comment]
Addressed in #574.  Closing.
