### ISSUE TITLE
Unit tests missing docstrings

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#565]
**Is your feature request related to a problem? Please describe.**
For a clear error report, each unit test method needs a one-line docstring.  This standard has not been consistently implemented in the code.  Also, some docstrings are copied over from other tests.

**Describe the solution you'd like**
I would like the docstrings to be checked and added or changed as needed.

**Describe alternatives you've considered**
Leaving it alone and causing problems debugging in the future.

# Unit test files to be updated
- [x] test_constellation.py
- [x] test_custom.py
- [x] test_files.py
- [x] test_instrument.py
- [x] test_instruments.py
- [x] test_meta.py
- [x] test_methods_general.py
- [x] test_orbits.py
- [x] test_params.py
- [x] test_registry.py
- [x] test_utils.py
- [x] test_utils_coords.py
- [x] test_utils_files.py
- [x] test_utils_testing.py
- [x] test_utils_time.py

**Comment by jklenzing** [comment]
I've been working on the tests in a serial fashion, breaking off a new branch whenever it's about review size.  Most of these are queued up for review, just need to finish test_instruments (the longest one...).

**Comment by jklenzing** [comment]
Rough drafts of all tests complete.  Linking to #860.

**Comment by jklenzing** [comment]
Closing with merge of #883
