### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#57]
Support on windows need to be completed and verified.

**Comment by jklenzing** [comment]
Should we try to incorporate appveyor in addition to travis?  I've caught some windows compatibility issues with this in sami2py.

**Comment by aburrell** [comment]
I think we should, but only after 3.0.  AppVeyor is much slower than travis and I think our current output log will break things.

**Comment by jklenzing** [comment]
Besides having windows users (which we have now), are there other specific things we could do to close this issue?

**Comment by jklenzing** [comment]
Using the test branch from #778, these are the failures in Github Actions under a windows run:
- FAILED pysat/tests/test_meta.py::TestBasics::test_nan_metadata_filtered_netcdf4_via_meta_attribute
- FAILED pysat/tests/test_meta.py::TestBasics::test_nan_metadata_filtered_netcdf4_via_method
- FAILED pysat/tests/test_meta.py::TestBasicsImmutable::test_nan_metadata_filtered_netcdf4_via_meta_attribute
- FAILED pysat/tests/test_meta.py::TestBasicsImmutable::test_nan_metadata_filtered_netcdf4_via_method
- FAILED pysat/tests/test_params.py::TestBasics::test_update_standard_value -  ...
- FAILED pysat/tests/test_params.py::TestBasics::test_add_user_parameter -   Fi...
- FAILED pysat/tests/test_utils.py::TestCIonly::test_initial_pysat_load - TypeE...
- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_basic_write_and_read_netcdf4_default_format[True]
- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_basic_write_and_read_netcdf4_default_format[False]
- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_basic_write_and_read_netcdf4_mixed_case_format
- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_write_and_read_netcdf4_default_format_w_compression
- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_write_and_read_netcdf4_default_format_w_weird_epoch_name
- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_write_and_read_netcdf4_default_format_higher_order
- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_write_and_read_netcdf4_default_format_higher_order_w_zlib
- FAILED pysat/tests/test_utils_coords.py::TestLonSLT::test_calc_solar_local_time[testing]
- FAILED pysat/tests/test_utils_coords.py::TestLonSLT::test_calc_solar_local_time[testing_xarray]
- ERROR pysat/tests/test_files.py::TestCIonly::test_initial_pysat_load - TypeEr...
- ERROR pysat/tests/test_params.py::TestBasics::test_set_data_dirs[.-check0] - ...
- ERROR pysat/tests/test_params.py::TestBasics::test_set_data_dirs[.\\hi-check1]
- ERROR pysat/tests/test_params.py::TestBasics::test_set_data_dirs[.\\hi\\-check2]
- ERROR pysat/tests/test_params.py::TestBasics::test_set_data_dirs[.\\-check3]
- ERROR pysat/tests/test_params.py::TestBasics::test_set_data_dirs[paths4-None]
- ERROR pysat/tests/test_params.py::TestCIonly::test_settings_file_must_be_present
- ERROR pysat/tests/test_params.py::TestCIonly::test_settings_file_cwd - TypeEr...
- ERROR pysat/tests/test_utils_files.py::TestFileDirectoryTranslations::test_updating_directories

Will update with specific issues when the source is tracked down.

**Comment by jklenzing** [comment]
Also noting that the windows jobs under Github Actions are noticeably slower than ubuntu (~70 minutes vs ~54 minutes for pytest only).

**Comment by rstoneback** [comment]
In #804 down to

- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_basic_write_and_read_netcdf4_default_format[True]
- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_basic_write_and_read_netcdf4_default_format[False]
- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_basic_write_and_read_netcdf4_mixed_case_format
- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_write_and_read_netcdf4_default_format_w_compression
- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_write_and_read_netcdf4_default_format_w_weird_epoch_name
- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_write_and_read_netcdf4_default_format_higher_order
- FAILED pysat/tests/test_utils.py::TestBasicNetCDF4::test_write_and_read_netcdf4_default_format_higher_order_w_zlib
- FAILED pysat/tests/test_utils_coords.py::TestLonSLT::test_calc_solar_local_time[testing]
- FAILED pysat/tests/test_utils_coords.py::TestLonSLT::test_calc_solar_local_time[testing_xarray]

**Comment by rstoneback** [comment]
unit tests in windows now pass as of #804

**Comment by jklenzing** [comment]
Closing with incorporation of unit tests for windows.
