### ISSUE TITLE
TST: InstTestClass support for module-level specification of `user` and `password`

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#573]
**Is your feature request related to a problem? Please describe.**
Currently, pysatMadrigal cannot raise an Error if the user forgets to supply a username and password.  Instead, the loading routine defaults to supplying the test information.  This is not helpful for Madrigal, which likely uses this information in their reports to funding agencies.

**Describe the solution you'd like**
I would like the InsTestClass to have `user` and `password` attributes.

**Describe alternatives you've considered**
Leaving this as is or exploring other alternatives.

**Comment by jklenzing** [comment]
Closing with merge of #623
