### ISSUE TITLE
Meta labels

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#575]
**Describe the bug**
Many of the default metadata labels are similar and usually set to the same values

**To Reproduce**
Load up any instrument

**Expected behavior**
Default metadata labels should provide unique information

**Desktop (please complete the following information):**
 - OS: OS X Mojave
 - Version 3.7

**Additional context**
Part of #483 and is being addressed in https://github.com/pysat/pysat/tree/meta_reshape

**Comment by aburrell** [comment]
From @rstoneback: 
--------------------

> Here’s a link to a pdf with variable attributes for the ISTP/IACG standard. https://pds-ppi.igpp.ucla.edu/doc/cdf/CDF-ISTP-IACG-Variable-Attributes-20130807.pdf
> Comes from here, essentially: https://spdf.gsfc.nasa.gov/istp_guide/istp_guide.html
> NetCDF has only a couple requirements for variables: https://www.unidata.ucar.edu/software/netcdf/documentation/NUG/_best_practices.html

My thoughts after going over this:
----------------------------------
What I'm getting from these documents, is that there is no reason for us to default to having as many meta labels as we do.  Instead, they should be added when the instrument wants them. 
 
NetCDF wants 'long_name' and 'units', and thinks anything else is a bonus.
 
ISTP/IACG additionally wants 'fill_val', 'min_val', 'max_val', 'units', 'long_name', DESC, FIELDNAME, VAR_TYPE, LABL_PTR_X, FORMAT, and DEPEND_X
 
DESC -> Catalog description that is really useful when it is used correctly.
DEPEND_X -> not needed in meta, as is obvious from the index/coords
FORMAT -> data format, again, not needed as the data will be in that format
VAR_TYPE -> not needed in meta, as is obvious from placement in data, metadata, or index/coords
LABL_PTR_X -> 'axis'; typically identical to 'long_name', so I think should be optional
FIELDNAME -> 'plot'; typically identical to 'long_name' (contrary to the requirements of the standard), so I think should be optional
 
pysat labels currently set by default and not required by any standard: 'notes' and 'scale'

Given this breakdown, I think we should remove 'notes', 'scale', 'plot', and 'axis' from the default labels.  Since 'scale', 'plot', and 'axis' are all related to plotting data, perhaps they could be grouped into a set of optional labels (e.g., fig_labels=True).  This would make it simple for instruments wanting a set of labels conforming to ISTP standards, since it would initialize the necessary additional labels.
 
'notes' is a useful place for dumping extra info, but if there isn't extra info to dump, should it really be there?
 
'desc' is potentially useful, but often not well assigned.  I think it should be required and that we should go through the instruments and make sure it's not given the same value as the variable name.
 
It would also be worthwhile to add a link to: https://spdf.gsfc.nasa.gov/istp_guide/vattributes.html in the docs, if we haven't already.

**Comment by rstoneback** [comment]
> ## From @rstoneback:
> > Here’s a link to a pdf with variable attributes for the ISTP/IACG standard. https://pds-ppi.igpp.ucla.edu/doc/cdf/CDF-ISTP-IACG-Variable-Attributes-20130807.pdf
> > Comes from here, essentially: https://spdf.gsfc.nasa.gov/istp_guide/istp_guide.html
> > NetCDF has only a couple requirements for variables: https://www.unidata.ucar.edu/software/netcdf/documentation/NUG/_best_practices.html
> 
> ## My thoughts after going over this:
> What I'm getting from these documents, is that there is no reason for us to default to having as many meta labels as we do. Instead, they should be added when the instrument wants them.
> 

I implemented most of the ICON standard for meta as a default, which I think may become the SPDF standard for netCDFs. The documents I linked don't cover the additional redundancies present in ICON that gets taken care of by pysat. It is better than it could've been. I've been thinking about where the additional parameters come from, it could have been a review of existing NC loading software. I will have to check the root ICON document again. I know the Berkeley SPEDAS software had an overall large influence on the ICON variable names, may have impacted meta as well.

> NetCDF wants 'long_name' and 'units', and thinks anything else is a bonus.
> 

Pretty much.

> ISTP/IACG additionally wants 'fill_val', 'min_val', 'max_val', 'units', 'long_name', DESC, FIELDNAME, VAR_TYPE, LABL_PTR_X, FORMAT, and DEPEND_X
> 
> DESC -> Catalog description that is really useful when it is used correctly.
> DEPEND_X -> not needed in meta, as is obvious from the index/coords

This is covered by the file creation routine.

> FORMAT -> data format, again, not needed as the data will be in that format

This is covered by the file creation routine.

> VAR_TYPE -> not needed in meta, as is obvious from placement in data, metadata, or index/coords

This is covered by the file creation routine.

> LABL_PTR_X -> 'axis'; typically identical to 'long_name', so I think should be optional
> FIELDNAME -> 'plot'; typically identical to 'long_name' (contrary to the requirements of the standard), so I think should be optional
> 
> pysat labels currently set by default and not required by any standard: 'notes' and 'scale'
> 
> Given this breakdown, I think we should remove 'notes', 'scale', 'plot', and 'axis' from the default labels. Since 'scale', 'plot', and 'axis' are all related to plotting data, perhaps they could be grouped into a set of optional labels (e.g., fig_labels=True). This would make it simple for instruments wanting a set of labels conforming to ISTP standards, since it would initialize the necessary additional labels.
> 

Thanks for the review. I really don't want to argue for the current file standards, across the field it is a mess, and even within a funding agency I take issue with what they have chosen. I do worry about creating yet another file standard though. Obligatory xkcd. https://xkcd.com/927/

> 'notes' is a useful place for dumping extra info, but if there isn't extra info to dump, should it really be there?
> 

If things are left 'free' as it were, folks will invent their own words. Or they may just not include the information if there isn't a designated spot. 

> 'desc' is potentially useful, but often not well assigned. I think it should be required and that we should go through the instruments and make sure it's not given the same value as the variable name.
> 

I believe currently we take meta, however it is, from the file.

> It would also be worthwhile to add a link to: https://spdf.gsfc.nasa.gov/istp_guide/vattributes.html in the docs, if we haven't already.

I'll give this some thought. I am working on packaging the IVM software today and just realized I forgot to fix a thing. I need to go and fix it.

**Comment by rstoneback** [comment]
I've thought about it. I don't like the current standard and we don't have to follow NASA or any other organization for what pysat does by default. I'm ok with changing the default list of parameters. You are certainly better at organization than I am so as long as I can still make ICON compatible files I'm good. 

Not all of ICON is really in there by default anyway. pysat doesn't normally have redundant values for fill_value though ICON requires both _FillValue and FillVal, or ValidMax and Valid_Max. scale_label is set to 'ScaleTyp' (8 char limitation). 

Changing meta defaults on ICON support won't have much impact as long as new ones can be added. The depend and other variable information stored as meta in the to_netcdf4 method would need to be retained in some fashion. The xarray based Instruments also don't currently get the same treatment. FYI this runs into the xarray and pandas equivalence issues (one of the old ones).

**Comment by jklenzing** [comment]
To Close:
- [ ] Remove plot, axis, and scale from defaults
- [ ] Check to ensure that these are still supported as optional kwargs

**Comment by jklenzing** [comment]
Closing with merge of #634
