### ISSUE TITLE
_instrument.py `_get_data_info` style and testing

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#577]
**Describe the issue**
Currently netCDF older than netCDF4 is not tested (see missing lines in Coveralls)

Also, an `old_format` flag (equal to `file_format != 'NETCDF4'`) is declared, and used twice.  It seems to me the style would be cleaner to not declare the flag and just use the evaluation twice, since it'll take up essentially the same amount of space and evaluations.

(Lines 2148-2166 at time of issue creation).

**Comment by jklenzing** [comment]
We currently don't have the ability to write older netcdf files (unless I'm missing something), which makes testing older files difficult.  Options:
- Add support and test (probably not worth the time to figure out)
- Add a test file and test
- Drop support
- Not drop support, but rewrite to reduce uncovered lines

**Comment by jklenzing** [comment]
Linking to #578

**Comment by jklenzing** [comment]
Closing with merge of #634
