### ISSUE TITLE
TST: _instrument.py `_get_var_type_code` not well tested

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#578]
**Describe the bug**
Most input options for this routine (3/12) are not tested.

**To Reproduce**
Go to Coveralls

**Expected behavior**
All lines of code should be tested.

**Comment by jklenzing** [comment]
To close:
- [ ] Remove old_format support in _instrument
- [ ] Add test for unknown data type

**Comment by jklenzing** [comment]
Closing with merge of #634
