### ISSUE TITLE
Support Monthly and Yearly Data

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#58]
Space weather indices, such as Dst, or solar indices, may require analysis on time scales longer than a day. The current Instrument object is optimized around a day. While it supports loading by file instead of day, not the most user friendly. Works for many basic data needs, however it doesn't offer all of pysat's functionality. All data should have best effort support from pysat.

I think we can fake monthly and yearly support without having to reimplement a new class. We may need a class, but it can just pull mostly everything from the current one.

Plan:
  - Create a new class, MonthlyInstrument ? - to be determined
  - subclass the Instrument object
  - make a new load routine, optimized around loading by month, that just has a different front end but really calls the existing load
  - when a load is requested by month, or by year, then the new load routine makes a call to the hidden load routine using filenames
  - To make everything work out, the files for the monthly instrument need to be by month; yearly data by year. This can be faked on a per instrument basis, as needed.
  - The iterators likely need some work in this setup
  - Data padding may not work. Something to look at.
  - Alternative is to create a new load routine with all of the features of the current one, but based around month
  - The alternative is most ideally implemented by pulling out as much core code as possible so as to reduce the amount of code upkeep in the future.

**Comment by jklenzing** [comment]
Expanding the scope, what about indices which have a single data file?

**Comment by jklenzing** [comment]
Linking to #123 since the directory structure mapping function will be useful here.

**Comment by jklenzing** [comment]
Was this completely addressed by #582?

**Comment by rstoneback** [comment]
Yep, thanks for the reminder.

**Comment by jklenzing** [comment]
No problem.  Slowly catching up to all the changes in the code.
