### ISSUE TITLE
TST/DOC: testing and documentation for portalocker interaction

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#590]
**Is your feature request related to a problem? Please describe.**
The portalocker unit tests could be made more robust.  Current usage (test_race_condition) only attempts to run five copies of pysat simultaneously.  Additionally, the user documentation should be updated so that other packages know how to activate this.

**Describe the solution you'd like**
The unit tests should check to ensure a locked file is locked when pysat attempts to access it.

**Describe alternatives you've considered**
Untested code. 🙀 

**Additional context**
See discussion in #525

**Comment by jklenzing** [comment]
Tests to add:
- [ ] Check that locked file is locked
- [ ] Check that timeout variables works as expected

**Comment by JonathonMSmith** [comment]
Should this be testing the NetworkLock class, code that locks files in pysat, or both?

The only instances of file locking I can find in pysat are the following:
https://github.com/pysat/pysat/blob/583ad920443d605628e70451aa452a79db8d7902/pysat/_params.py#L142-L146
https://github.com/pysat/pysat/blob/583ad920443d605628e70451aa452a79db8d7902/pysat/tests/test_files.py#L112-L116

One of these is in testing. I think I'm missing something about when and where pysat is locking files.

**Comment by jklenzing** [comment]
We should be testing the `NetworkLock` class under `pysat.utils`.  My thought for the test was to create a locked file and attempt to write to it

**Comment by JonathonMSmith** [comment]
Sounds good. Got a little lost in the weeds here I think.
