### ISSUE TITLE
Issue with installing pysat for python 3.6

### ISSUE THREAD

**Issue by ithaca-isr** [pysat/pysat#606]
Hi,

I installed a python 3.6 virtual environment using conda. After activating my environment, I typed pip3.6 install pysat, but I get maybe 20 instances of the following error:  "Cache entry deserialization failed, entry ignored". 

At the end of the installation it said, successfully installed pysat-2.2.1, however, when I run import pysat, it say"model not found error".  I have a MacBook pro, python 3.6.10, clang 4.0.1, gcc 4.2.1

Would greatly appreciate any help

Thanks!

**Comment by jklenzing** [comment]
Thanks for the report!  Depending on your virtual environment setup, it sounds like there could be an issue with the pip cache.  See https://github.com/pypa/pip/issues/5250 for more information.

I'm not sure where the "model not found error" is originating from.  It could be a result of the above error (a requirement not being installed) or something else.  Do you have a more detailed error message?

**Comment by ithaca-isr** [comment]
Hi Jeff,

Thanks for your response. It's not my personal computer but one of the
students I'm mentoring for a space physics course. I attached a screenshot
of the errors.

How are you doing? Last time I saw you was at the hackathon at Cedar 2018
in Santa Fe

Thanks
Sevag

**Comment by jklenzing** [comment]
Hi Sevag,

Been doing all right.  I think github dropped the image along the line.  Could you either email me or upload it via the web interface in the issue?  

Thanks!

**Comment by ithaca-isr** [comment]
Hi Jeff,

I responded to you via email. Hope you got it. Let me know
Sevag

**Comment by jklenzing** [comment]
A couple of thoughts after talking with people and trying to reproduce the error:
- It might be solved by updating pip, then reinstalling pysat.  
- You should also check your path (echo $PATH) to be sure that the pip installed codes and conda installed codes are both available.  
Let me know if you're still having trouble

**Comment by ithaca-isr** [comment]
thanks Jeff. Let me try and I'll let you know

**Comment by jklenzing** [comment]
Sevag, were you able to sort out the install?  Let me know if there are still issues.  -Jeff

**Comment by ithaca-isr** [comment]
Hi Jeff,

Sorry for not responding earlier. I was helping one of the students I'm
mentoring and she still hasn't had the time to try out the suggestion.
Waiting for her to get back to me. Will let you know when I hear back.
thanks so much for your help.

Sevag

**Comment by jklenzing** [comment]
Feel free to ping me if this is still an issue.

**Comment by ithaca-isr** [comment]
thanks Jeff. I think for now it seems like the person having the issue
never got back to me. I'll let you know if anything changes.
Sevag
