### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#61]
Currently pysat prints a bunch of different statements to the stdoutput. It would be much better if all of those statements were replaced with logging. Users could select how much feedback they get to terminal and to file.

Plan:
 - Replace all of the print statements with logging statements

**Comment by asher-pembroke** [comment]
I think it would be beneficial to have the name of the current module as part of the format. For example:

```python
from pysat import logger
logger.warning('test')
```
```console
2019-09-26 16:56:27,978 pysat        WARNING  test
```

instead of the more generic:
```python
import logging
logging.info('test')
```
```console
WARNING:root:test
```
This would make it easier to separate pysat info from instrument info, for example.

**Comment by rstoneback** [comment]
Absolutely. Thanks Asher.

**Comment by asher-pembroke** [comment]
Closing this issue now that logging branch is merged.
