### ISSUE TITLE
ENH: Constellation support for multiple instruments in single file

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#614]
**Is your feature request related to a problem? Please describe.**
Multiple pysat instruments (including space weather products and GOLD data) have multiple instruments / data products in the same file.  With current standards, one would load the same file multiple times to extract all necessary information for analysis.  This can be inefficient over large studies.

**Describe the solution you'd like**
Pysat should be able to load a file once and parse the data into multiple instrument objects.  `Constellation` seems like a natural interface for this.

**Describe alternatives you've considered**
Allowing multiple data objects in a single instrument.  This could potentially get messy.

**Aditional Info**
See pysat/pysatNASA#7 for info on GOLD, pysat/pysatSpaceWeather#1 for indices.

**Comment by rstoneback** [comment]
Given the small size of an instrument definition file I'm not sure that reading it multiple times is much of a performance bottleneck. Could also be the case that the file is cached by hw so subsequent file access may be even faster.

**Comment by aburrell** [comment]
I think what we could do is make it optional to provide a load routine in the constellation file.  Then the Constellation load method would preferentially call that routine instead of using the Instrument load methods.

**Comment by aburrell** [comment]
This would also require a Constellation download routine, and some way of indicating where the data is stored.

**Comment by jklenzing** [comment]
This also could be useful for COSMIC2 IVM, where the datasets for each `inst_id` are separate but all are stored in a single zip file.

**Comment by rstoneback** [comment]
Could use the attached Instrument objects to get the relevant locations, inst.files.data_path

**Comment by jklenzing** [comment]
> I think what we could do is make it optional to provide a load routine in the constellation file. Then the Constellation load method would preferentially call that routine instead of using the Instrument load methods. @jklenzing do you want to give this a try for GOLD?

It might be a while before I get to this.  Too many things in the queue.

**Comment by rstoneback** [comment]
> > Could use the attached Instrument objects to get the relevant locations, inst.files.data_path
> 
> I was thinking more along the lines of saving the files to the highest common location (e.g., shared 'inst_id' means only saving under platform/name/tag or shared 'tag' saving under platform/name).

Currently for cosmic-2 ivm the directory format in the instrument module file is defined to leave out inst_id. Similarly tag could be left out as needed. Instrument objects also store the directory template string, `inst.files.directory_format`, so that's also available to the Constellation class to use. Not trying to argue against the feature but the more we reuse existing items the less there is to maintain.

**Comment by rstoneback** [comment]
For GOLD  I get a load time of < 4 ms. Double loading in this case is tolerable.

The generalized discussion for load and download at the constellation level could be useful for gold but perhaps not required. Same time, small file size and more complicated file structure does provide a good test case for expansion of methods at the Constellation level.

**Comment by jklenzing** [comment]
Hmm.  I guess if we update the directory structure for gold to ignore 'inst_id' we could avoid the double-download issue.  We only currently support 1 out of 6 gold L2 data products, so this could be an issue for the others.  Since we've agreed to delay the GOLD changes until after pysat 3.0.2 (?) is released, this could be something to investigate.

**Comment by aburrell** [comment]
Just a note that this is no longer necessary for pysatSpaceWeather, after https://github.com/pysat/pysatSpaceWeather/pull/107 is merged.

**Comment by jklenzing** [comment]
Nominal path forward for GOLD: accept loading the file twice. Closing until we decide this should be revisted.
