### ISSUE TITLE
Transparent Instrument defaults

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#620]
**Is your feature request related to a problem? Please describe.**
Some of the Instrument keyword arguments default to None, even though they may be able to default to something more transparent (like False).  This is the case for `mutli_file_day`.  However, with this keyword argument and several others that can be set in the instrument, will changing the default mess up the behaviour?

**Describe the solution you'd like**
- [x] 1) For keyword arguments currently set to None and not touched by the Instrument, make sure None is a sensible option and not just a placeholder
- [x] 2) For keyword arguments that can be reset by instruments, is None needed or can something more standard be used?
- [x] 3) Make sure the Instrument docstring is updated.

**Describe alternatives you've considered**
Leaving things the way they are.

**Comment by jklenzing** [comment]
Need to identify instruments to test this code
- multi_file_day : dmsp_ivm, timed_saber

**Comment by jklenzing** [comment]
To close:
- [ ] remove `manual_org` keyword, rewrite `directory_format` docstring
- [ ] Change `multi_file_day` to default to False

**Comment by jklenzing** [comment]
Update: To remove multi_file_day as a default for all instruments, changes need to occur in the test instruments (See #266, #389, #620)
