### ISSUE TITLE
Duplicate metadata in testing instruments

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#621]
**Is your feature request related to a problem? Please describe.**
The testing instruments share many common aspects, including their metadata.

**Describe the solution you'd like**
I would like to define a testing method that sets the metadata for the different testing instruments, so that if we need to
change things (like the metadata labels) it exists all in one place.

**Describe alternatives you've considered**
1) Leave the metadata inside each load routine
2) Leave the metadata in each instrument but outside the load routine

**Additional context**
I was just messing with this in #587 and it seemed like a simple place to reduce duplicate code.  I have a metadata initialization method in `pysatSpaceWeather.instruments.methods.kp_ap` that was helpful reducing duplicate code lines, so I thought we could do the same thing here.

**Comment by jklenzing** [comment]
Closing with merge of #875
