### ISSUE TITLE
Improve discovery of supported instruments

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#67]
Currently users are required to go to the documentation or code to determine which tags are supported by each instrument. Instruments can be discovered at the command line, though this can be improved.

We need a routine that lists out the available instruments, what the tags are, etc.

Each instrument already has a dictionary with text descriptions that can be used. Routine needs to go through and determine what instruments are in pysat.instruments, import them, then print out salient info.

**Comment by armandophys** [comment]
See issue #100 ? Maybe the help(pysat) method can be taken advantage of in this situation.

**Comment by rstoneback** [comment]
It can. The instrument files have a docstring so that could get printed out.

I already have some test code that discovers which modules are present and sets them up to be tested. Was thinking of adapting that in a routine with a nice printout, maybe even return a dict of platform, name, tag, sat-Id combos or something.

On Oct 18, 2018, at 1:59 PM, armandophys <notifications@github.com<mailto:notifications@github.com>> wrote:


See issue #100<https://github.com/rstoneback/pysat/issues/100> ? Maybe the help(pysat) method can be taken advantage of in this situation.

**Comment by aburrell** [comment]
This would improve the user experience, and so should be included before version 2.0 is released.

**Comment by jklenzing** [comment]
Bumping this to 3.0 since instrument usage is changing there.

**Comment by jklenzing** [comment]
Items to add:
- [ ] Method to display supported instruments
- [ ] Method to display docstring for a given instrument

**Comment by jklenzing** [comment]
Now that we have the instrument registry, this should be easy to implement.  Two possible ways of listing instruments:
- `pysat.utils.show_instruments()`
- `pysat.instruments.show()`

Preferences?  Other suggestions?

For the instrument docstrings, see #324.

**Comment by jklenzing** [comment]
pysat.utils.registry.load_saved_modules returns a list of instruments, maybe build off of this?

**Comment by jklenzing** [comment]
This issue was created before our current roadmap.  Since pysat 3.0.0 is importing all instruments from external libraries, what does this issue look like now?  Do we still need it?

**Comment by aburrell** [comment]
I think that this issue may look different, but is a feature that would be useful depending on how external libraries end up working.  Perhaps we can revisit this once we have two or three external instrument libraries working?
