### ISSUE TITLE
Expand Constellation unit tests

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#672]
**Is your feature request related to a problem? Please describe.**
We should probably have a 2d xarray constellation object, but that should be a separate pull (and issue), maybe for 3.1.0.

**Comment by aburrell** [comment]
Currently constellations/testing.py has `pysat_ndxarray` as one of the Instruments.  I think this fulfills the requirements here?

**Comment by jklenzing** [comment]
That's correct.
