### ISSUE TITLE
Deprecated `pysat.data_dir`

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#683]
**Is your feature request related to a problem? Please describe.**
`pysat.data_dir` is deprecated in pysat 3.0

**Describe the solution you'd like**
Add a deprecation warning, a note in the docstring, and a unit test for the deprecation warning.

**Describe alternatives you've considered**
Surprise the users!

**Comment by rstoneback** [comment]
See #754

**Comment by jklenzing** [comment]
Closing with merge of #754
