### ISSUE TITLE
Deprecated use of `inst_id` in testing instruments

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#686]
**Is your feature request related to a problem? Please describe.**
Use of `inst_id` to simulate number of samples in testing instruments is deprecated in pysat 3.0

**Describe the solution you'd like**
Add a deprecation warning, the new kwargs, a note in the docstring, and a unit test for the deprecation warning.

**Describe alternatives you've considered**
Surprise the users!

**Comment by jklenzing** [comment]
Closing with merge of #736
