### ISSUE TITLE
Deprecated `time.season_date_range`

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#692]
**Is your feature request related to a problem? Please describe.**
`time.season_date_range` is deprecated in pysat 3.0

**Describe the solution you'd like**
Add a deprecation warning, a note in the docstring, and a unit test for the deprecation warning.

**Describe alternatives you've considered**
Surprise the users!

**Comment by aburrell** [comment]
Deprecation warning needs to add a final version to the message.

**Comment by jklenzing** [comment]
Test was hidden away here too.  Updated to use `TestDeprecation` class as elsewhere.

**Comment by jklenzing** [comment]
Closing with merge of #711
