### ISSUE TITLE
Deprecated `coords.scale_units`

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#693]
**Is your feature request related to a problem? Please describe.**
`coords.scale_units` is deprecated in pysat 3.0

**Describe the solution you'd like**
Add a deprecation warning, a note in the docstring, and a unit test for the deprecation warning.

**Describe alternatives you've considered**
Surprise the users!

**Comment by aburrell** [comment]
Needs a version number in deprecation warning.

**Comment by jklenzing** [comment]
This does have a test, but it's not grouped with the others for some reason.  Will move.

**Comment by jklenzing** [comment]
Closing with merge of #711
