### ISSUE TITLE
Deprecated `ssnl`

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#696]
**Is your feature request related to a problem? Please describe.**
`ssnl` is deprecated in pysat 3.0

Missing deprecations:
- [x] _occurence2D (occur_prob)
- [x] _occurence3D (occur_prob)
- [x] _calc_2d_median (avg)
- [x] _core_mean (avg)
- [x] _calc_1d_median (avg)

**Describe the solution you'd like**
Add a deprecation warning, a note in the docstring, and a unit test for the deprecation warning.

**Describe alternatives you've considered**
Surprise the users!

**Comment by jklenzing** [comment]
Looking through the code, the forward facing functions all have deprecation warnings (as well as docstrings).  We can add warnings to these at well.  This would result in chained warnings for users, but might catch some development issues where people bypass the forward-facing functions.  

Also noting that the `_occurrenceND` functions don't have docstrings at all. :(

**Comment by aburrell** [comment]
> but might catch some development issues where people bypass the forward-facing functions.

That was my reasoning behind making this list.
