### ISSUE TITLE
Migrated file methods to pysat.utils.files

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#700]
**Is your feature request related to a problem? Please describe.**
File methods migrated to `pysat.utils.files` in pysat 3.0

**Describe the solution you'd like**
Add a deprecation warning to old routines, a note in the docstring, and a unit test for the deprecation warning.

**Describe alternatives you've considered**
Surprise the users!

**Comment by aburrell** [comment]
@jklenzing and @rstoneback these are currently set to be removed in pysat 4.0, do we want to follow our current process and deprecate it here instead?

**Comment by jklenzing** [comment]
I think we should deprecate them here

**Comment by jklenzing** [comment]
Are we just including a deprecation warning, or the extra functions as well?

**Comment by aburrell** [comment]
I think just the warning.  They're the same functions (I believe), it's just that they'll have moved.

**Comment by jklenzing** [comment]
Closing with merge of #710
