### ISSUE TITLE
pysat v3.0 Release and Dependent Packages

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#718]
**Describe the Issue**
A backwards compatible upgrade to pysat (v3.0) will be released within the month. A release candidate is currently out on testpypi. Based upon GitHub's dependents section, one of your packages uses pysat and may require an update to use the new version. Thank you for using pysat!

```
python -m pip install --index-url https://test.pypi.org/simple/ pysat==3.0.0rc2
```

**Comment by rstoneback** [comment]
@NathanTP @jssmith @ga59cor

**Comment by jklenzing** [comment]
Will close upon code deployment
