### ISSUE TITLE
Create paths provided via pysat.params['data_dirs']

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#720]
**Is your feature request related to a problem? Please describe.**
Users aren't enthused when pysat does not create a pysat data directory for them.

**Describe the solution you'd like**
Added code to create provided path if it doesn't already exist.

**Describe alternatives you've considered**
Leaving as is.

**Additional context**
Received from v3.0RC user

**Comment by jklenzing** [comment]
This will also streamline unit testing for downstream packages.  It may create some issues in Travis, as I recall you can't write to the home directory there.  Not sure about other CI services.

**Comment by rstoneback** [comment]
This issue is stale. The code changes are live now! I've taken out the specific call to make a directory on Travis, well, now I use pysat to make it.

from `__init__.py`
```
    # Set initial data directory if we are on Travis
    if (os.environ.get('TRAVIS') == 'true'):
        data_dir = '/home/travis/build/pysatData'
        params['data_dirs'] = [data_dir]
```

**Comment by rstoneback** [comment]
the travis environment variable is actually something that I added to travis at some point. We could rename it on Travis to online_testing or something. Do other testing places support user set environmental variables?

**Comment by jklenzing** [comment]
We could potentially set it outside pysat.  I'm using a console command to set it in the github actions test branch.
 
https://github.com/pysat/pysat/blob/03ebf53ee5d326ebf3176add2cbbe8248c643ee5/.github/workflows/python-package.yml#L47-L48

**Comment by jklenzing** [comment]
> the travis environment variable is actually something that I added to travis at some point. We could rename it on Travis to online_testing or something. Do other testing places support user set environmental variables?

I can set user variables in github actions.  Should work for other services.

**Comment by aburrell** [comment]
You can set environment variables in AppVeyor too.  Pretty common, actually.
