### ISSUE TITLE
ENH/BUG: setting of pysat data directory via function

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#732]
**Is your feature request related to a problem? Please describe.**
The current usage of `pysat.params['data_dirs'] = './pysatData'` to set the data directory does not work outside of an interactive environment (such as ipython).  For instance, this fails when trying to set this via the terminal:
```
 python -m "pysat.params['data_dirs'] = './pysatData'"
```
Error message:
```
Error while finding module specification for "pysat.params['data_dirs'] = './pysatData'" (ModuleNotFoundError: No module named "pysat.params['data_dirs'] = '")
```

**Describe the solution you'd like**
A function that redirects to the above command, similar to the previous `pysat.utils.set_data_dir`.

**Describe alternatives you've considered**
restricted functionality? Autocreate a directory?  A way of setting this that I've missed?

**Additional context**
This is primarily affecting setup of CI tests in alternate services.  We've patched over this in the Travis CI tests by auto-detecting the environment and hardwiring the code.  While this works for now, if the downstream packages require new services or migration from Travis CI (which may be the case for pysatMissions), it will require future patches to the main package, which will make maintenance a pain.

There may be other use cases affected for non-interactive usage.

**Comment by jklenzing** [comment]
Linking to pysat/pysatMissions#45

**Comment by rstoneback** [comment]
the '-m' option imports the named module and executes any associated __main__, which pysat isn't set up for. I think you are looking for 
```
python -c "import pysat; pysat.params['data_dirs'] ='./pysatData'"
```

**Comment by rstoneback** [comment]
Note that setting up the directory as a special command for TravisCI has been removed over in #727. There are still tests do check for Travis itself. Some of these are robust enough now that I think the non-user environment check may be removed.

**Comment by jklenzing** [comment]
This works.  Thanks!  I've got a working test branch of pysatMissions set up to use github actions now with the release candidate.

My use case is solved, are there other things we should patch for this release?

**Comment by rstoneback** [comment]
I'm working on things as they pop up when I start running them on the RC, or if I hear from someone that there is an issue. Speaking of, #730, popped up today. I believe python versions below 3.8 are in good shape, but there is a problem with the newest of the new.

**Comment by rstoneback** [comment]
well, I say 3.8, but he is listing 3.7.9. Perhaps I got confused with pysatCDF which is working in 2 of the 3 python3 versions.

**Comment by jklenzing** [comment]
Closing, as the specific problem is solved here.
