### ISSUE TITLE
DEP: remove support for inst_id as number of samples in test instruments 

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#734]
**Is your feature request related to a problem? Please describe.**
3.0.0 shouldn't have any deprecation warnings

**Describe the solution you'd like**
Deprecate inst_id/sat_id support for size of samples in pysat testing instruments in pysat 2.3.0 (#686)

PR should merge into #676

**Comment by jklenzing** [comment]
Since the 3.0 changes are merged in, I've updated the milestone for the remaining changes.

**Comment by aburrell** [comment]
There's already an issue for that, as stated in the description, so I am changing the milestone back and closing the issue.
