### ISSUE TITLE
MAINT: version caps for final pysat 2.x release

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#747]
Cap remaining versions for pysat 2.3.0
- [ ] scipy
- [ ] matplotlib

**Comment by aburrell** [comment]
I was thinking about this, and thought we could keep this open and revisit it in the future when it becomes applicable.  I added the `main-2` branch so we could maintain pysat 2.3.0 and 3.X simultaneously.

**Comment by jklenzing** [comment]
Should I change the milestone to "future"?

**Comment by jklenzing** [comment]
Current caps in the 2.3.0 release:
- numpy>=1.12, <1.20
- pandas>=0.23, <0.25
- xarray<0.15

We don't have caps for scipy and matplotlib, but I don't think this matters anymore. Proposing we close this issue.

**Comment by jklenzing** [comment]
Best case scenario, we do a limited test for the ops environment. Currently failing due to lack of "Cython"

https://github.com/pysat/pysat/actions/runs/8527140171/job/23357899125

**Comment by aburrell** [comment]
I am fine closing this and doing a final "won't fix" pysat2 release (if there are any changes).

**Comment by aburrell** [comment]
We can drop the ops test for this branch and put in a higher python cap.

**Comment by jklenzing** [comment]
The only changes I have in the RC are to use GitHub Actions instead of Travis CI.

**Comment by jklenzing** [comment]
> We can drop the ops test for this branch and put in a higher python cap.

Since we are limited to pandas<0.25, the max python version we can support is 3.7, which reached end-of-life on 27 Jun 2023
