### ISSUE TITLE
STY/TST: caplog usage in unit tests

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#751]
**Is your feature request related to a problem? Please describe.**
We currently have multiple styles of perusing the logs in the unit tests.  

**Describe the solution you'd like**
Consistency is key.  Ideally, the logs would be temporarily turned on and not permanently set.  Example:
```
    def test_download_recent_data(self, caplog):
        with caplog.at_level(logging.INFO, logger='pysat'):
            self.testInst.download()
```

**Describe alternatives you've considered**
There may be a cleaner method.  Should make sure that we don't inundate the test logs with comments.

**Additional context**
Affects:
- [x] test_custom.py::TestLogging
- [x] test_instrument.py::TestBasics::test_download_updated_files
- [x] test_instrument.py::TestBasics::test_download_recent_data
- [x] test_instrument.py::TestBasics:: test_instrument_partial_function_keywords
- [x] test_instrument.py::TestBasics::test_instrument_partial_keywords_liveness
- [x] test_utils_coords.py:: TestLonSLT:: test_calc_solar_local_time_inconsistent_keywords

**Comment by rstoneback** [comment]
Two of the functions were updated in #753

- test_instrument.py::TestBasics:: test_instrument_partial_function_keywords
- test_instrument.py::TestBasics::test_instrument_partial_keywords_liveness

**Comment by jklenzing** [comment]
Closing with merge of #882
