### ISSUE TITLE
DOC: update changelog

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#756]
Because we have two different develop branches, the 3.0 changelog should be updated with the 2.3 changes.  Not sure about the planned order of release of 3.0.0 and 2.3.0.  This could go in either 3.0.0 or 3.0.1.  @aburrell? @rstoneback?

**Comment by rstoneback** [comment]
I have a few deadlines this week, including v3.0, but no funding requirement deadline for v2.3. I think 2.3 will be coming out just a little later than v3.0, I need to resolve that `is instance` thing, perhaps with a string comparison check.

**Comment by aburrell** [comment]
I would have preferred side-by-side releases, but I am ok bending to reality.  I think the current 2.3.0 changelog should be added to 3.0.0 and it can be updated to the final version in 3.0.1.

**Comment by rstoneback** [comment]
I'm still hoping to get 2.3 out 'on time'. Couple days yet until 3.0 deadline.

**Comment by rstoneback** [comment]
I put the changelog changes into the current changelog associated pull.

**Comment by jklenzing** [comment]
Closing with merge of #752
