### ISSUE TITLE
Rename develop branches

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#760]
**Is your feature request related to a problem? Please describe.**
After the 3.0.0 release, the python 3 branch is now the standard path and the python 2 path has the `-2` suffix. 

**Describe the solution you'd like**
For consistency with `main` and `main-2`, the current `develop` should be renamed `develop-2` and after this the `develop-3` branch should be renamed `develop`.

**Describe alternatives you've considered**
Leaving things the way they are and have `develop` feed into `main-2` while `develop-3` feeds into `main`.

**Comment by rstoneback** [comment]
See #758 and #759 for updates.

**Comment by aburrell** [comment]
Ugg, looks like I'm stepping on your toes.  Stepping away from this website! Let me know when you want reviews.

**Comment by rstoneback** [comment]
> Ugg, looks like I'm stepping on your toes. Stepping away from this website! Let me know when you want reviews. 🐘

No worries! It happened to be on my mind, even when I set up #758 to begin with. Plus I was counting down the minutes on a test pass to take the next step.

I was going to say the same. I'll confine myself to getting the release out on pypi then sending the CEDAR email. We should all take a break from pysat, at least for the weekend. There I have to catch up on some DINEOFs :) I'm getting closer to a reasonable schedule but there is a backlog first.

**Comment by rstoneback** [comment]
Branches have been renamed. `develop` -> `develop-2` and `develop-3` -> `develop`.
