### ISSUE TITLE
BUG: data access via slicing if data is missing

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#761]
**Describe the bug**
If I try to extract data points that do not exist, I get unhelpful feedback from pandas.

**To Reproduce**
Assuming registration of pysatSpaceWeather and download of data
```
import datetime as dt
import pysat
sw = pysat.Instrument('sw', 'f107', tag='all')
sw.load(2012, 1)
sw[dt.datetime(2012, 1, 1), 'f107']
```
yields an error, since this day is missing.  (2012-1-2 works as expected).
```
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Root cause**
It stems from the try / except notation here:
https://github.com/pysat/pysat/blob/900dead3ff3e51db96d37ef54e3a3e9b082affa1/pysat/_instrument.py#L703-L711

If I pass through a datetime val that does not exist in the dataframe, pandas throws a keyError, triggering the except lines.  It then tries to misapply the inputs, providing more errors.

**Comment by jklenzing** [comment]
Context: I'm using pysat to look up f107 values for a given day. I'm running this over a loop generating evenly spaced model runs using input f107 values for sami2py.  For my immediate use case, I can catch this and replace it with a three-day average if a day is missing.  However, it's really confusing to trace the root cause of the error, and I suspect others will run into this.

**Comment by aburrell** [comment]
I think I've run into this before as well.

**Comment by rstoneback** [comment]
Thanks for the report. For the particular case of F10.7  this situation may be avoided by resampling the F10.7 data within sw_f107.py so there is data, or at least a NaN, for each day.

**Comment by jklenzing** [comment]
Solution: save error messages from both and output both for clarity

**Comment by jklenzing** [comment]
Closing with merge of #783
