### ISSUE TITLE
ENH: Review and document file parsing code in pysat.utils.files

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#762]
**Is your feature request related to a problem? Please describe.**
Filename parsing doesn't work the best if the leading and/or trailing characters are a keyword. Diagnosing this bug is challenging since a range of functions used to be one very large function.

**Describe the solution you'd like**
Iterate through the functions in order, testing each one individually. Improve docstrings, variable names, and behaviors for keywords at boundaries. In order, `construct_searchstring_from_format`, `search_local_system_formatted_filename` then `parse_fixed_width_filenames` and `parse_delimited_filenames`. The final two likely require the most attention but they each rely upon `construct_searchstring_from_format` internally.

Plus, add a note that current parsing starts at the end of the filename. 
    # When processing a fixed width filename, '?' must be used at the end so
    # the function can determine the width, but '*' may be used at the beginning
    # where information doesn't need to be parsed.

**Describe alternatives you've considered**
Leave it as is, though there are unexpected gotchas that can frustrate others.

**Additional context**

**Comment by rstoneback** [comment]
Add to online documentation and docstrings as well

**Comment by aburrell** [comment]
Changes in #853 may help address this issue.

**Comment by jklenzing** [comment]
Linking to #854.  It is not clear from the docstrings when to use `parse_fixed_width_filenames` vs `parse_delimited_filenames`, as the example string for each is identical.
