### ISSUE TITLE
Test xarray data sources with existing pysat routines

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#77]
After initial xarray support is pulled into develop, use the included pysat testing instrument based on xarray and perform a number of typical pysat operations. Ensure custom functions work. Check existing functions written for pandas based Instrument object and determine how they behave with an xarray object.

**Comment by aburrell** [comment]
Adding TIEGCM added an instrument that uses xarray, making progress on this issue.

**Comment by jklenzing** [comment]
I think that GOLD will be our first end-to-end test of an xarray instrument.

**Comment by rstoneback** [comment]
There are also the synthetic xarray sources as part of testing.

I’m going to transfer SuperDARN over to xarray here soon and then I’m going to have to work with it as part of my DINEOF work. I think that will be the best for me to get  more comfortable with xarray.

Cheers,
Russell

On Mar 12, 2019, at 1:15 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


I think that GOLD will be our first end-to-end test of an xarray instrument.

**Comment by jklenzing** [comment]
That's right.  I was largely thinking of the full download and load check run in test_instruments.py, like the other cdaweb instruments.

**Comment by rstoneback** [comment]
Ah, thanks for the clarification.

On Mar 12, 2019, at 1:31 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


That's right. I was largely thinking of the full download and load check run in test_instruments.py, like the other cdaweb instruments.

**Comment by jklenzing** [comment]
As of #391, all test instruments are run through the standardized test_instruments routines.  Is there anything else we want to do to address this issue?

**Comment by aburrell** [comment]
No, I think this issue has been completed.
