### ISSUE TITLE
Weak reference in orbits

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#770]
**Describe the bug**
I have started making orbit plots, and now I frequently get this error:

```
    319     cindi.bounds = (stime, etime)
--> 320     for cindi in cindi.orbits:
    321         # Set the output filename
    322         if plot_dir is None:

~/Programs/Git/pysat/pysat/_orbits.py in __iter__(self)
    289         while True:
    290             try:
--> 291                 self.next()
    292                 yield self.inst
    293             except StopIteration:

~/Programs/Git/pysat/pysat/_orbits.py in next(self)
    852 
    853         # Check if data exists
--> 854         if not self.inst.empty:
    855             # Set up orbit metadata
    856             self._calc_orbits()

ReferenceError: weakly-referenced object no longer exists

```
**To Reproduce**
Steps to reproduce the behavior: Make a for loop for creating plots and increment by orbit.  Will not always fail.

**Expected behavior**
Cycling without losing references to instrument attributes

**Desktop (please complete the following information):**
 - OS: OS X Mojave
 - Version Python 3.7
 - Other details about your setup that could be relevant: iPython, pysatNASA

**Comment by rstoneback** [comment]
Thanks for the report. I will poke around myself, but can you rename the ‘for cindi in cindi.orbits()’ to something like ‘for cindi_orbit in cindi.orbits()’?

**Comment by rstoneback** [comment]
A better fix, potentially, is over in the linked pull.

**Comment by aburrell** [comment]
I ended up using `orbit_num` to set up an iteration loop where `next` is called.  I had set it up the way it was because I was following a documentation example.  On a separate note, I think it would be nice to have `first` and `last` orbit calls.

**Comment by rstoneback** [comment]
> On a separate note, I think it would be nice to have `first` and `last` orbit calls.

ok. In the meantime, you can use orbits[] to grab first and last orbit for a day. 
```
In [4]: test.orbits[0]                                                                                                                                                                                                      
pysat INFO: test_load_kwarg = None
pysat INFO: Returning pysat testing data for 30 January 2008
pysat INFO: typical lt diff 0.004123711340206171
pysat INFO: test_load_kwarg = None
pysat INFO: Returning pysat testing data for 31 January 2008
pysat INFO: typical lt diff 0.004123711340206171
pysat INFO: Loaded Orbit: 0

In [5]: test.orbits[-1]                                                                                                                                                                                                     
pysat INFO: Loaded Orbit: 15
```

**Comment by rstoneback** [comment]
> I ended up using `orbit_num` to set up an iteration loop where `next` is called.
Glad you found a way forward.

> I had set it up the way it was because I was following a documentation example. 
:) Yeah. Not blaming you but I was attempting to use your setup to diagnose if it was specifically a garbage collection issue.

> On a separate note, I think it would be nice to have `first` and `last` orbit calls.
Note above.
