### ISSUE TITLE
BUG: windows compatibility in Github Actions

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#778]
**Describe the bug**
Cannot import pysat in github actions under a windows environment.  Not sure if this applies to other windows environments as well.

**To Reproduce**
Created a custom workflow (https://github.com/pysat/pysat/actions/runs/832145000) to install pysat under a variety of environments and try to set the directory.  The code works on ubuntu and mac, but fails when the "import pysat" command is invoked:
```
    import pysat
  File "D:\a\pysat\pysat\pysat\__init__.py", line 89, in <module>
    params = _params.Parameters(path=pysat_dir, create_new=True)
  File "D:\a\pysat\pysat\pysat\_params.py", line 148, in __init__
    os.fsync(fout.fileno())
OSError: [Errno 9] Bad file descriptor
```

**Expected behavior**
I should be able to import the package

**Desktop (please complete the following information):**
 - OS: windows-latest under github actions

**Additional context**
@JonathonMSmith, do you encounter this on your windows environment? 

Linking to #57, as solving this is a step forward for that issue.

**Comment by rstoneback** [comment]
This was encountered during pyhc hackathon session on Bryan Harter's machine. Windows does not appear to like this call. I think we could wrap it in a try: except: OSError Bad file... type thing.

**Comment by rstoneback** [comment]
Once the `fsync` calls were commented out pysat imported

**Comment by jklenzing** [comment]
Tried this out in the nomerge branch: https://github.com/pysat/pysat/runs/2605931699?check_suite_focus=true

Replacements made:
https://github.com/pysat/pysat/blob/4ad506207becba0cac396563218d905eb908dda5/pysat/_params.py#L148-L152
https://github.com/pysat/pysat/blob/4ad506207becba0cac396563218d905eb908dda5/pysat/utils/_core.py#L756-L762

This allowed me to set the data directory from the command line in windows, mac, and ubuntu under Github actions.  Note that a script is used to to make the directory paths system independent.
```
import os
import pysat

here = os.path.abspath('.')
pysat.params['data_dirs'] = os.path.join(here, 'pysatData')
print(pysat.params['data_dirs'])
```
Note that fsync appears elsewhere in the code.  Probably should replace throughout.

**Comment by rstoneback** [comment]
Thanks Jeff. Originally I thought perhaps a check for windows would be the best route forward but with WSL it makes things harder.

**Comment by jklenzing** [comment]
I think this might be the right route forward.  Pushed another test branch to start cataloging the windows errors.

**Comment by rstoneback** [comment]
Test pass under windows in GitHub Actions. At least two relevant pulls, #809, #804.

**Comment by rstoneback** [comment]
Closing as pysat can be imported in windows in GitHub Actions.
