### ISSUE TITLE
Remove freq keyword from download

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#788]
**Is your feature request related to a problem? Please describe.**
Current pysat 'standard' is to allow users to supply a frequency keyword which is then used to pare down a date range. This requires users to remember or look up that a particular instrument isn't standard.

**Describe the solution you'd like**
If a particular data source isn't stored by day, then that specific data source download method should accept date ranges as input and intelligently download an appropriate range of data.

**Describe alternatives you've considered**
Leave as is.

**Additional context**

**Comment by jklenzing** [comment]
Deprecations for 3.1.0
