### ISSUE TITLE
Data Design Document

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#793]
**Is your feature request related to a problem? Please describe.**
We have a section in the documentation about adding an instrument. This document doesn't have everything yet since we haven't distilled all of the potential rules about adding a dataset.

**Describe the solution you'd like**
Create something like a pep8 for instrument data philosophy. Something that perhaps has some narrative at the beginning to set the stage and then iterating on a list of do's and don't's [sic].

**Describe alternatives you've considered**
Leaving things unspecified and folks will do whatever, whenever.

**Additional context**
a pep8 for adding an instrument data set won't solve all problems.

**Comment by jklenzing** [comment]
Partially addressed in https://github.com/pysat/pysat/pull/1077
