### ISSUE TITLE
Constellation platform/name/tag/inst_id attributes

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#795]
**Is your feature request related to a problem? Please describe.**
I was thinking that it could be useful to assign `platforms`, `names`, `tags`, and `inst_ids` attributes (trailing `s` a style choice we should discuss) to the Constellation.  Since many of the pre-built constellations use data from the same platform (or similar), this would be an easy way to describe the scope of the Constellation.

It could also be used to initialize a Constellation based on the registered pysat Instruments.

**Describe the solution(s) you've considered**
1) Have the `platforms`, `names`, `tags`, and `inst_ids` attributes be lists of strings
  A) Each list would have at least one string value, and only unique values would be included
  B) This would not uniquely define a Constellation, but could be used to load a Constellation by adding every registered instrument that fulfills the permutations.
  C) This would not change the `Constellation.__repr__()`, since the instrument list is the cleaner way to define things.
  D) This would change the `Constellation.__str__()`, by providing a quick look that allows the user to see "Oh, this is a subset of the ACE realtime constellation" (`platforms=['ace'], names=['mag', 'swepam'], tags=['realtime'], inst_ids=[''])`
  E) Has the benefit of being similar to the Instrument attributes, but not exactly the same (so not expected to behave the same)
  F) Negative: `tags` and `inst_ids` variable names already used in Instrument sub-modules, but the scope does not overlap
2) Have the `platform`, `name`, `tag`, and `inst_id` attributes be strings
  A) Each string would have non-unique results separated by character, like `+`, that is never used when creating platform, name, tag, or inst_id strings.
  B) Same as 1B
  C) Same as 1C
  D) Similar to 1D, but with a different read style.
  E) Has the benefit of being the same as the Instrument attributes, and so when applying `const_to_inst`, would easily transfer over.  However, they behave a bit differently, which could be confusing.
  
Thoughts about loading with these kwargs:
```
# Load all names/inst_ids for the chosen platform/tag combo
ace = pysat.Constellation(platforms=['ace'], tags=['realtime'])

# Load all ACE combos as above, but also include an F10.7 forecast
sw_realtime = pysat.Constellation(instruments=[pysat.Instrument('sw', 'f107', 'forecast')], platforms=['ace'], tags=['realtime'])
```

**Additional context**
I started by adding this to #764, but decided it should be it's own thing.

**Comment by rstoneback** [comment]
Thought about 1A. If you only include unique values then `platforms` `tags` etc. could be different lengths. This configuration would make it hard to iterate via something like `for stuff in zip(platforms, names, tags, ....)`. I like option 1 but with the change that all values for `tags` etc are kept.

Thoughts about 1F. `tags` and `inst_ids` are used in both areas in the same sense, they define the supported values, either at the Instrument level or Constellation level. To me it is consistent.

So far I currently prefer solution 1 over 2.

I could see a use for 2A in `const_to_inst`.
