### ISSUE TITLE
Constellation Test Class with Missing Data

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#798]
**Is your feature request related to a problem? Please describe.**
All instruments in a constellation don't always have data. 

**Describe the solution you'd like**
We should ensure that this case is covered by unit tests.

**Describe alternatives you've considered**
Leave as is.

**Additional context**
First mentioned at https://github.com/pysat/pysat/pull/785

**Comment by jklenzing** [comment]
We could implement this by feeding a different `file_date_range` to one of the test instruments in the constellation.  Should be easy to implement.

**Comment by jklenzing** [comment]
NOTE to self: work on after flake8/docstrings5 is merged.

**Comment by jklenzing** [comment]
Linking to https://github.com/pysat/pysatNASA/issues/152
