### ISSUE TITLE
Consider Additional Constellation Data Boolean Flags

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#800]
**Is your feature request related to a problem? Please describe.**
the pysat.Instrument object has an empty parameter with a straightforward interpretation. If there is any data, then it is False. For constellations there are a greater variety of data states.

**Describe the solution you'd like**
Consider adding additional attributes, `full`, `partial`, and modifying `empty`. To reflect
- All instruments have data
- Some instruments have data
- No instruments have data

Or some other similar system.

**Describe alternatives you've considered**
Leave as is.

**Additional context**
Current constellation has no attributes, https://github.com/pysat/pysat/pull/785 adds an `empty`, though there is some discussion on what empty should really be.

**Comment by rstoneback** [comment]
With more thought we only need two, `full` and `empty`, to describe no data, some data, all have data.

**Comment by jklenzing** [comment]
Tri-oolian?

**Comment by rstoneback** [comment]
![image](https://user-images.githubusercontent.com/3595641/119855743-c9ee0f00-bed7-11eb-9a8e-2a70b44a4dc8.png)

Partial coverage if empty and full are false. @aburrell put in the underlying code so for me the question is what is the best way to express the functionality already there.

**Comment by aburrell** [comment]
Option! `empty` (all instruments empty) `empty_partial` (at least one instrument is empty).

**Comment by rstoneback** [comment]
Thanks @aburrell. I realized after my talk the other day, and before your recent push, that I forgot to bring up a poll about what to call this attribute as discussed in the pysat meeting. 🐒 Sorry about that and thanks for the pull.
