### ISSUE TITLE
Testing Instrument Support Module Keywords

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#805]
**Is your feature request related to a problem? Please describe.**
Some instrument data sets have custom features that are enacted via keywords in the underlying instrument functions.

**Describe the solution you'd like**
It could be great if end-to-end tests were run with and without the keywords.

We would likely need to define test inputs to the keywords at the instrument level.

Consider adding this functionality.

**Describe alternatives you've considered**
Leave it alone.

**Additional context**
There is already a way to add custom tests to a relevant module. See https://github.com/pysat/pysatMissions/blob/develop/pysatMissions/tests/test_instruments.py starting at line 72.

It may be that this is already enough.

**Comment by jklenzing** [comment]
Potentially, just adding a simple load test under the class would be enough.  The `pytest-ordering` markers should make sure that downloads occur first.  Note that pysatMissions auto-generates data, but I think the principle would work.

**Comment by rstoneback** [comment]
I was able to add the test that I wanted without any issues.
