### ISSUE TITLE
Question: day of year support for listing files

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#810]
**Is your feature request related to a problem? Please describe.**
Some files use day of year in their filenames.  I set up `pysat.instruments.methods.general.list_files` inputs to use `doy` as the format tag for that in filenames, and it didn't work.

Question: Is this allowed and I'm just doing it wrong?

**Describe the solution you'd like**
If I am not wrong, I would like the option to have day of year as a date in the filename

If I am just doing it wrong, I would like more detail in the `pysat.instruments.methods.general.list_files` docstrings.

**Describe alternatives you've considered**
Forcing files to have different names locally from their established standards.

**Comment by rstoneback** [comment]
It works for me on CINDI files to use existing `day` template keyword.

from my `list_files`
```
        elif tag == 'daily_update':
            return pysat.Files.from_os(data_path=data_path,
                                   format_str='CINDI-IVM-{year:4d}{day:03d}.NC')
```

filename on system, `CINDI-IVM-2009076.NC`

**Comment by rstoneback** [comment]
I didn't actually show end to end that it worked. Output included for completeness.
```
In [20]: ivm = pysat.Instrument(inst_module=cindi_ivm_gsw.instruments.cindi_ivm, tag='daily_update', update_files=True)                                                                          

In [21]: ivm.files.files[100:120]                                                                                                                                                                
Out[21]: 
2009-04-23    CINDI-IVM-2009113.NC
2009-04-24    CINDI-IVM-2009114.NC
2009-04-25    CINDI-IVM-2009115.NC
2009-04-26    CINDI-IVM-2009116.NC
2009-04-27    CINDI-IVM-2009117.NC
2009-04-28    CINDI-IVM-2009118.NC
2009-04-29    CINDI-IVM-2009119.NC
2009-04-30    CINDI-IVM-2009120.NC
2009-05-01    CINDI-IVM-2009121.NC
2009-05-02    CINDI-IVM-2009122.NC
2009-05-03    CINDI-IVM-2009123.NC
2009-05-04    CINDI-IVM-2009124.NC
2009-05-05    CINDI-IVM-2009125.NC
2009-05-06    CINDI-IVM-2009126.NC
2009-05-07    CINDI-IVM-2009127.NC
2009-05-08    CINDI-IVM-2009128.NC
2009-05-10    CINDI-IVM-2009130.NC
2009-05-12    CINDI-IVM-2009132.NC
2009-05-13    CINDI-IVM-2009133.NC
2009-05-14    CINDI-IVM-2009134.NC
dtype: object

In [22]: pysat.__version__                                                                                                                                                                       
Out[22]: '3.0.0'

```

**Comment by aburrell** [comment]
Ok, thanks for the clarification.  In this case, there needs to be a comment in the routine docstring that 'day' will specify both day of month and day of year, because that's not what I would expect.

**Comment by aburrell** [comment]
So... I accidentally committted these changes directly to develop.  Stepping away before I break more things.

**Comment by rstoneback** [comment]
The combo day/doy support goes way back to the early days of pysat before standards were improved. Clearly the docs needed some improvement 🐵 🙈
