### ISSUE TITLE
New style guide

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#816]
**Describe the bug**
As discussed in pysatMadrigal, the contributing guidelines need to be changed to support Windows OS.

**To Reproduce**
Go read the contributing guidelines

**Expected behavior**
All pysat ecosystem contributing guidelines should be the same

**Desktop (please complete the following information):**
N/A

**Additional context**
To address this:
- [x] update the contributing guidelines 
- [ ] add issues for contributing guidelines in other pysat ecosystem packages

**Comment by jklenzing** [comment]
We could put the style guide in a single location for ease of maintenance, then import from each project

**Comment by aburrell** [comment]
That would be really nice for a lot of these community documents.  Not sure how to do it, though.

**Comment by rstoneback** [comment]
Create a pysatCommunity (?) as a central place to store the documents.

**Comment by aburrell** [comment]
What about a 'pysatEcosystem_Template' repository that also has standard templates of other files (e.g., Issues, .ymls, etc).

**Comment by jklenzing** [comment]
Added repository here: https://github.com/pysat/pysatEcosystem_Template

**Comment by jklenzing** [comment]
Closing this since the repository is open.  Please add suggestions to the issues there: https://github.com/pysat/pysatEcosystem_Template/issues

Based on the latest `pysat` release with a few updates.
