### ISSUE TITLE
Coveralls no longer being called for pull requests

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#817]
**Describe the bug**
In my last pysat pull request (#812) I noticed that coveralls wasn't going off and I couldn't find the branch on the pysat coveralls page after going there to check.  I looked at the GitHub Actions main.yml and couldn't find a coveralls call.  Was it deliberately removed or accidentally removed?

**To Reproduce**
Go to tagged PR or Coveralls

**Expected behavior**
A nice Coveralls call that lets me easily see which lines are covered/not covered.

**Additional context**
Possibly introduced after the Windows debugging.

**Comment by jklenzing** [comment]
Looking through the commits, I think this was deleted in my initial windows fix branch when I was debugging things by running selective tests, then accidentally merged into develop.  This should have been restored as part of the commit labeled "run ALL the tests", but this escaped my review.

**Comment by jklenzing** [comment]
Closing with merge of #818
