### ISSUE TITLE
BUG: xarray assumptions about time

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#823]
**Describe the bug**
With the release of xarray 0.16.0, a `decode_timedelta` kwarg was added to the the `load_dataset` routine, defaulting to `None` (but in practice acting as `True`).  This will attempt to convert values to a `np.timedelta64` if the unit attribute looks like time, ie, hours, minutes, seconds.  This could be an issue for datasets that use separate variables rather than a single epoch (such as older datasets), or for specialty time units such as SLT, MLT.

**To Reproduce**
Download test file from: https://github.com/sami2py/sami2py/blob/main/sami2py/tests/test_data/sami2py_output.nc

```
import xarray as xr
model1 = xr.load_dataset('sami2py_output.nc')
model2 = xr.load_dataset('sami2py_output.nc',  decode_timedelta=False)
```

`model1['ut']` is stored as a timedelta64, with time in ns
`model2['ut']` is stored as a float, with time in hours

**Expected behavior**
Users of data should not be surprised by time units.

**Additional context**
Note that 'slt' is unchanged, as the unit attribute is listed as 'hrs'.  However, if this were 'hour' or 'hours', presumably it too would be converted to a timedelta in ns.

Recommend we add `decode_timedelta=False` to the usage of xr.load_dataset in the `utils` functions.  Potentially add this as an option to pass through.

http://xarray.pydata.org/en/stable/generated/xarray.open_dataset.html#xarray.open_dataset

**Comment by aburrell** [comment]
100% agree with the recommendation to set `decode_timedelta=False`.

**Comment by jklenzing** [comment]
Verified that changing the unit attribute of 'slt' to 'hours' will cause this to load as a `timedelta64`.

**Comment by jklenzing** [comment]
Requires updates to documentation for creators of third-party instrument libraries

**Comment by jklenzing** [comment]
Closing with merge of #886
