### ISSUE TITLE
Issue with pandas 1.2.6

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#833]
**Describe the bug**
Unit tests online using latest pandas (v1.2.6) are producing errors in areas that were working.

https://github.com/pysat/pysat/pull/831#issuecomment-873166754

Something with setting partial data.

pandas v1.2.5 works

**To Reproduce**
1. Run unit tests with affected version
2. See error

**Expected behavior**
pysat unit tests should pass

**Screenshots**

**Desktop (please complete the following information):**
 - OS: GitHub Actions
 - Version GitHub Actions
 - Other details about your setup that could be relevant

**Additional context**

**Comment by jklenzing** [comment]
Closing with merge of #838
