### ISSUE TITLE
numpy minimum version 1.17.3

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#834]
**Describe the bug**
Recent unit test runs are requiring numpy 1.17.3

Initial fix here, https://github.com/pysat/pysat/pull/831

**To Reproduce**
1. Run unit tests for rc1 (#821) without #831
2. See error

**Expected behavior**
Tests run.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: GitHub Actions
 - Version GitHub Actions
 - Other details about your setup that could be relevant

**Additional context**

**Comment by jklenzing** [comment]
I think this is fixed in the release candidate now
