### ISSUE TITLE
Include registry examples in pysat tutorial

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#837]
**Is your feature request related to a problem? Please describe.**
I frequently forget how to register instruments in pysat, since I don't do it often.  The first place I look is in the pysat docs tutorial (basics and params), but nothing there is helpful.  Instead, I always end up going to the index, searching for register, and ending up in the API section.

**Describe the solution you'd like**
An example of how to register instruments in the tutorial.  Ideally in either basics or params, since I usually look there.

**Describe alternatives you've considered**
Adding a link to the API in the tutorial, since the API example is fine for me.  But this might not be clear for other users.

**Additional context**
Registration is an important step and one that isn't performed frequently so needs clear and easy to find documentation.

**Comment by rstoneback** [comment]
A link to the registry and an example was added to tutorial_basics.
