### ISSUE TITLE
Create Roadmap

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#845]
**Is your feature request related to a problem? Please describe.**
Some users, particularly those that may be considering building on top of pysat, want a clear view of what to expect from pysat in the future.

**Describe the solution you'd like**
1) Rebalance existing issues
2) Consider longer term goals
3) Distill into a version roadmap

**Describe alternatives you've considered**
Continuing on as is. 

**Additional context**
NumFocus recommends/requires a roadmap

**Comment by rstoneback** [comment]
A document has been started here, https://github.com/pysat/pysat/wiki/Roadmap-(Draft)

**Comment by rstoneback** [comment]
roadmaps for [numpy](https://numpy.org/neps/roadmap.html) and [pandas](https://pandas.pydata.org/about/roadmap.html)

**Comment by rstoneback** [comment]
review request of the draft text @aburrell @jklenzing @JonathonMSmith

**Comment by jklenzing** [comment]
Goals:
3.1 - wiki draft complete
3.2 - stable version in documentation

**Comment by jklenzing** [comment]
Current version: https://github.com/pysat/pysat/wiki/Roadmap

**Comment by jklenzing** [comment]
To close, copy wiki text into readthedocs
