### ISSUE TITLE
DOC BUG: examples in general.py

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#846]
**Describe the bug**
The examples in `pysat.instruments.methods.general` are old and incomplete

**To Reproduce**
Try and run any of the examples as is (especially `list_files`)

**Expected behavior**
The examples should be absent or provide all the steps needed to perform the example task

**Comment by rstoneback** [comment]
Perfect lead in to more general testing of examples in all of the docstrings, which can easily fall out of date.

**Comment by jklenzing** [comment]
Would something generalized be appropriate?  ie
```
        from pysat.instruments.methods import general as mm_gen
        fname = 'instrument_{year:04d}{month:02d}{day:02d}_v{version:02}.cdf'
        supported_tags = {'tag_name': fname}
        list_files = functools.partial(mm_gen.list_files,
                                       supported_tags=supported_tags)
```
or should it be capable of being run on an actual file?

**Comment by aburrell** [comment]
It should be able to work on an actual file, but that can probably be put off until the docstring examples are tested.

**Comment by jklenzing** [comment]
With the merge of #856, should we leave this open for the docstring testing part or close and open a new issue?

**Comment by aburrell** [comment]
Close this and open a new issue for docstring testing.
