### ISSUE TITLE
TST: missing unit tests for files utilities

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#854]
**Is your feature request related to a problem? Please describe.**
Not all files utility functions have unit tests

**Describe the solution you'd like**
Unit test classes for the following functions:
- [x] process_parsed_filenames
- [x] parse_fixed_width_filenames
- [x] construct_searchstring_from_format
- [x] search_local_system_formatted_filename
- [x] check_and_make_path

**Describe alternatives you've considered**
Only test through integration tests.

**Additional context**
Unit tests are valuable for exploring all the ways a function can be used.

**Comment by jklenzing** [comment]
Open question: do any instruments use delimited filenames?  Scanning existing packages, most seem to use the fixed_width command.  pysatNASA has the capability, but it is not used.

**Comment by aburrell** [comment]
I've needed it in the past, but it didn't work at the time so I used some annoying work-arounds.  Not sure if it's used at the moment.  SuperDARN would need this.
