### ISSUE TITLE
TST: missing unit tests for core utilities

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#857]
**Is your feature request related to a problem? Please describe.**
The core utility unit testing does not contain unit tests for the `generate_instrument_list` method.

**Describe the solution you'd like**
Add unit tests for this function.

**Describe alternatives you've considered**
Not unit testing this function, only using the output to run the Instrument unit and integration tests.

**Comment by jklenzing** [comment]
Closing with merge of #867
