### ISSUE TITLE
ENH: utils.scale_units definitions

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#865]
**Is your feature request related to a problem? Please describe.**
Currently, `scale_units` accepts 'deg', 'degree', 'degrees' as possible units.  However, some instruments use 'degrees North' and 'degrees East' for lat and lon respectively, which errors. 

**Describe the solution you'd like**
Potentially, using string search to find possible keys, or breaking input keys at a space in case further units are incorporated.

**Describe alternatives you've considered**
Fixing downstream where this applies.

**Additional context**
 Found while trying to interpolate modeled data onto ICON IVM by using pysatModels.  This could be fixed there in the automated usage of scale_units, but is worth discussing here.

**Comment by jklenzing** [comment]
Other examples found from datasets: 'degrees_east' and 'degrees_north'

**Comment by aburrell** [comment]
When looking at it it seemed sensible to have the user shape the units into an appropriate form for the scale_units function instead of having the function try to prepare for all possible inputs, as long as a suitably wide range are accepted.

**Comment by jklenzing** [comment]
Standards in the core code are appropriate, fixed in pysatModels.
