### ISSUE TITLE
BUG: tag or inst_id of None raises Error

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#892]
**Describe the bug**
Using None of inst_id or tag when instantiating an Instrument produces an error.

**To Reproduce**
1. Create an Instrument with a tag or inst_id of None
2. See error
3. AttributeError: 'NoneType' object has no attribute 'lower'

**Expected behavior**
Used to work ok with None inputs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Python 3.7, pysat v3.0.1
 - Other details about your setup that could be relevant

**Additional context**

**Comment by jklenzing** [comment]
Functionality was previously removed without deprecating.  Adding it back in for now, with a DeprecationWarning.  Closing with merge of #909
