### ISSUE TITLE
ENH: Update pysat.Instrument.rename to use meta.rename

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#900]
**Is your feature request related to a problem? Please describe.**
The pysat.Instrument.rename method renames a variable and associated metadata. There is now also a rename associated with meta itself.

**Describe the solution you'd like**
Makes sense to update Instrument.rename to internally use the meta.rename.

**Describe alternatives you've considered**
Leave as is.

**Additional context**
Instrument.rename works, and changes metadata variable names, but better to only have one code path for changing meta names. Possible edge case differences between the meta renaming within pysat.Instrument and meta.rename. meta.rename is the way forward.

**Comment by jklenzing** [comment]
Waiting on #896 to be merged
