### ISSUE TITLE
STY: grouping of pysat test instruments

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#908]
**Is your feature request related to a problem? Please describe.**
As we move toward more consistent libraries, the usage of test instruments should be re-evaluated. 2D pandas support will be removed, and new ground-based instruments may need to be supported.

**Describe the solution you'd like**
Rescope and possibly rename test instruments for clarity
- `pysat_testing` => pandas satellite data, 1D
- `pysat_testing2d_xarray` => xarray satellite data including 1D, 2D, and 3D data
- `pysat_testmodel` => xarray model data, 4D
- NEW MODULE => ground-based observatory?
- `pysat_testing2d` => deprecate, dropping higher order pandas support
- `pysat_testing_xarray` => deprecate, duplicates code in `pysat_testing2d_xarray`

**Describe alternatives you've considered**
Leaving things as is?

May want to rename test instruments for consistency, particularly if a ground-based observatory is added. `pysat_testsat` or `pysat_testorbital` for consistency with `pysat_testmodel`? Or something new for all three?

**Additional context**
Based on discussion at 9/29/2021 meeting.  See #389 and #873 for the road not taken.

**Comment by aburrell** [comment]
How about `pysat_testingnd` instead of `pysat_testing2d_xarray`?

**Comment by aburrell** [comment]
`pysat_ndtesting`?

**Comment by jklenzing** [comment]
OK, just noticed the rename of `pysat_testing2d_xarray` is still on my to do list before we can bump this version.  The rename is easy.  All the functions are moved to the new instrument module. The old one imports all these functions and has a new `init` routine to throw the deprecation warning.

My main question is how should we proceed with the unit tests? For instance, should I run the constellation tests on both the old and new instrument, or is the new one sufficient, provided we have a routine to check that loading data with the old one is the same and throws the same deprecation warning?

**Comment by jklenzing** [comment]
Test branch linked under the development tag if you want to see what the instrument deprecation looks like so far.

**Comment by jklenzing** [comment]
milestone bump!
