### ISSUE TITLE
Add support for renaming

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#91]
Couple renaming at Instrument level to changes at both the data and MetaData layer.

**Comment by jklenzing** [comment]
This is partially supported with the changes in #441 to remove variable prefixes.  Could potentially build off of that, or fold those changes into the syntax here,

**Comment by rstoneback** [comment]
This is partially supported with the changes in #441<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpysat%2Fpysat%2Fpull%2F441&data=02%7C01%7Crstoneba%40utdallas.edu%7Cd7f2ab8f1fac4eec9b1808d81b716336%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637289521097762883&sdata=voWMR6kQvPAQFCZlm75vFoyeHUdzLEjo4XW2DERPf9s%3D&reserved=0> to remove variable prefixes. Could potentially build off of that, or fold those changes into the syntax here,

Yes, I also technically have code in my ICON code to do it I just haven’t had the chance to port it.

**Comment by jklenzing** [comment]
With the merge of #458, is there anything else needed for this?

**Comment by rstoneback** [comment]
No. GitHub should have closed any linked issues.

On Jul 22, 2020, at 2:28 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:



With the merge of #458<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpysat%2Fpysat%2Fpull%2F458&data=02%7C01%7Crstoneba%40utdallas.edu%7C48266446949a4841c5a008d82e756f41%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637310429204007994&sdata=OvHHuxd9vw22DJinPrtAEt5FNgeMPUrGI4Z7OQWkS68%3D&reserved=0>, is there anything else needed for this?

**Comment by jklenzing** [comment]
They say it will close, but I've yet to see it happen.  Closing.
