### ISSUE TITLE
Create 'Projects Standard' Documents

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#910]
**Is your feature request related to a problem? Please describe.**
While all of pysat's issues are labeled by milestone (after review), and usually tagged as appropriate, it takes specific effort by a developer to sort out what needs to be done and when.

**Describe the solution you'd like**
Make better use of the Projects GitHub feature. Some previous projects posted weren't very well scoped, thus, we should create a project standards document to specify what groupings for a project are appropriate.

**Describe alternatives you've considered**
Going as is.

**Additional context**
Roadmap in documentation is the highest level, longest term vision. Projects is the next group down, and issues is the smallest.

**Comment by aburrell** [comment]
We are not great at actively using projects.  E.g., this last meeting we didn't go over any of the umbrella or local projects.  Since milestones are currently working ok, should we just close this out and be better at adding the existing projects to the meeting agendas?

**Comment by jklenzing** [comment]
Implementing in pysatEcosytem_template
