### ISSUE TITLE
BUG: Loading data without a time index

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#923]
**Describe the bug**
If pysat gets data without time information it does not complain. While some features will continue to work, some may not, and could very well be confusing for users. 

**To Reproduce**
1. Load a netCDF file that doesn't have a time index into pysat.Instrument
2. The data is there
3. Metadata is not there
4. Some data access from Instrument will not work.

**Expected behavior**
A warning that data doesn't conform to expectations and that unexpected behavior may occur.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 11.5.2
 - Version Python 3.8

**Additional context**

**Comment by jklenzing** [comment]
Implement a warning and a switch to bypass warning

**Comment by jklenzing** [comment]
Noting this issue predates the release of 3.0.2.  I think it may be stale. If I load an xarray dataset without a time index, I get an error.  Do you have an example?

**Comment by aburrell** [comment]
I think the goal was to be able to load a file without a time index, so long as a date is provided instead.  As well as a bypass for the warning that gets raised with GUVI.

**Comment by jklenzing** [comment]
I think the GUVI issue is separate.  That comes from the assigned epoch not being a dimension.

I'm stuck because I don't know how to test this.  If I create a xarray style dataset without a time axis, pysat already throws an error.
