### ISSUE TITLE
BUG: problem getting files to recognize all files

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#925]
**Describe the bug**
I am trying to load historic F10.7 data (pysatSpaceWeather).  I have not been able to get pysat to find all of the files that are available.

**To Reproduce**
Not sure how others could reproduce this.  I have files from `f107_monthly_1947-02.txt` to `f107_monthly_2018-04.txt` in the standard directory.  However, this is the output from pysat:

```
f107 = pysat.Instrument('sw', 'f107', tag='historic', update_files=True)
f107.files.files
1947-03-01    f107_monthly_1947-03.txt_1947-03-01
1947-03-02    f107_monthly_1947-03.txt_1947-03-02
1947-03-03    f107_monthly_1947-03.txt_1947-03-03
1947-03-04    f107_monthly_1947-03.txt_1947-03-04
1947-03-05    f107_monthly_1947-03.txt_1947-03-05
                             ...                 
1991-03-27    f107_monthly_1991-03.txt_1991-03-27
1991-03-28    f107_monthly_1991-03.txt_1991-03-28
1991-03-29    f107_monthly_1991-03.txt_1991-03-29
1991-03-30    f107_monthly_1991-03.txt_1991-03-30
1991-03-31    f107_monthly_1991-03.txt_1991-03-31
Freq: D, Length: 16102, dtype: object
```

The first file and many, many "last" files are missing.  I tried deleting all the stored files in case they had been corrupted when rsyncing between computers, but they were recreated with the same start and end dates.

**Expected behavior**
pysat should find all the available files, not just some files in the middle.

**Desktop (please complete the following information):**
 - OS: OS X Mojave
 - Version: 3.9
 - Other details about your setup that could be relevant: develop branch of pysatSpaceWeather.

**Comment by rstoneback** [comment]
Can you upload all of your monthly f107 files here as a .zip?

**Comment by aburrell** [comment]
Here they are:
[historic.tar.gz](https://github.com/pysat/pysat/files/7331089/historic.tar.gz)

**Comment by rstoneback** [comment]
You may want to check `f107.files.data_path` to ensure it is looking at the directory you expect. Now that pysat has multi-directory support it could potentially be pointed elsewhere.

Also, what version of pandas? Checking the code we use pandas to generate daily names from the monthly files.

You may also want to poke at line 333 in sw_f107 in pysatSpaceWeather
```
            out_files = pysat.Files.from_os(data_path=data_path,
                                            format_str=format_str)
```
