### ISSUE TITLE
HTTPSConnectionPool(host='zenodo.org', port=443)

### ISSUE THREAD

**Issue by ChineseHuang** [pysat/pysat#971]
in this code:
composite = 'true_color'
scn.load([composite])
have same error:

HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/1288441/files/pyspectral_atm_correction_luts_marine_clean_aerosol.tgz (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

**Comment by aburrell** [comment]
Hi @ChineseHuang, could you please specify which version of pysat and python you are using, as well as the pysat commands that lead to this error?  It looks like you may not be using our code and came to this repository by mistake.

**Comment by ChineseHuang** [comment]
satpy:0.26.0，python：3.7



At 2022-01-03 21:39:27, "Angeline Burrell" ***@***.***> wrote:

Hi @ChineseHuang, could you please specify which version of pysat and python you are using, as well as the pysat commands that lead to this error? It looks like you may not be using our code and came to this repository by mistake.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aburrell** [comment]
This is the pysat repository, not satpy.  Good luck with your issue, but you're in the wrong place.
