### ISSUE TITLE
MAINT: empty pandas.Series behavior changing

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#977]
**Is your feature request related to a problem? Please describe.**
Affects line 221 of test_files.py

```
FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
```

**Describe the solution you'd like**
Update for new pandas standards

**Describe alternatives you've considered**
🐼 

**Additional context**
Found with release of pandas 1.4.0

**Comment by jklenzing** [comment]
Simple to fix: `pds.Series([], dtype='float64')` to declare an empty series will maintain existing behaviour.  `dtype='str'` also works, and probably matches our use case better.  Thoughts?

**Comment by aburrell** [comment]
Why does 'str' match our current use better?  Naïvely I would assume that most data would be float.

**Comment by jklenzing** [comment]
It's normally a series of file names. In the tests, we replace it with an empty series. Both ways work locally, I'm open to either.

**Comment by aburrell** [comment]
If it's normally a series of filenames that I support 'str'.  Thanks for figuring this out so quickly @jklenzing!

**Comment by rstoneback** [comment]
This is how `from_os` currently returns a Series. It has `dtype='object'`
<img width="660" alt="image" src="https://user-images.githubusercontent.com/3595641/151457304-bf4b3db9-027b-4056-863d-ce4d4a044ecf.png">

**Comment by jklenzing** [comment]
In that case, object is probably the right way to go. I can update the PR accordingly.
