### ISSUE TITLE
Instrument update for xarray coords

### ISSUE THREAD

**Issue by aburrell** [pysat/pysat#988]
**Describe the bug**
When updating an xarray Instrument through pysat, coordinates are not treated correctly.

**To Reproduce**
```
inst = pysat.Instrument('pysat', 'testmodel')
inst.data = inst.data.assign_coords({'new_coord': 1.0})
print(inst.data)
```

Yields:
```
Dimensions:    (altitude: 41, latitude: 21, longitude: 72, time: 96)
Coordinates:
  * time       (time) datetime64[ns] 2009-01-01 ... 2009-01-01T23:45:00
  * latitude   (latitude) float64 -50.0 -45.0 -40.0 -35.0 ... 40.0 45.0 50.0
  * longitude  (longitude) float64 0.0 5.0 10.0 15.0 ... -20.0 -15.0 -10.0 -5.0
  * altitude   (altitude) float64 300.0 305.0 310.0 315.0 ... 490.0 495.0 500.0
    new_coord  float64 1.0
Data variables:
    uts        (time) float64 0.0 900.0 1.8e+03 ... 8.37e+04 8.46e+04 8.55e+04
    slt        (time, longitude) float64 0.0 0.3333 0.6667 ... 22.75 23.08 23.42
    mlt        (time, longitude) float64 0.2 0.5333 0.8667 ... 22.95 23.28 23.62
    dummy1     (time, latitude, longitude) float64 0.0 0.0 0.0 ... 18.0 0.0 3.0
    dummy2     (time, latitude, longitude, altitude) float64 0.0 0.0 ... 9.0
```

Next,
```
inst['new_coord'] = 2.0
print(inst.data)
<xarray.Dataset>
Dimensions:    (altitude: 41, latitude: 21, longitude: 72, time: 96)
Coordinates:
  * time       (time) datetime64[ns] 2009-01-01 ... 2009-01-01T23:45:00
  * latitude   (latitude) float64 -50.0 -45.0 -40.0 -35.0 ... 40.0 45.0 50.0
  * longitude  (longitude) float64 0.0 5.0 10.0 15.0 ... -20.0 -15.0 -10.0 -5.0
  * altitude   (altitude) float64 300.0 305.0 310.0 315.0 ... 490.0 495.0 500.0
    new_coord  (time) float64 2.0 2.0 2.0 2.0 2.0 2.0 ... 2.0 2.0 2.0 2.0 2.0
Data variables:
    uts        (time) float64 0.0 900.0 1.8e+03 ... 8.37e+04 8.46e+04 8.55e+04
    slt        (time, longitude) float64 0.0 0.3333 0.6667 ... 22.75 23.08 23.42
    mlt        (time, longitude) float64 0.2 0.5333 0.8667 ... 22.95 23.28 23.62
    dummy1     (time, latitude, longitude) float64 0.0 0.0 0.0 ... 18.0 0.0 3.0
    dummy2     (time, latitude, longitude, altitude) float64 0.0 0.0 ... 9.0
```

**Expected behavior**
Coordinates should not change their dimensions.  This only appears to happen if a coordinate is dimensionless.

**Desktop (please complete the following information):**
 - OS: OS X Big Sur
 - Version: python 3.8
 - Other details about your setup that could be relevant: came up when working with JRO ISR data (pysatMadrigal)

**Additional context**
Likely not using the xarray `assign` methods correctly.

**Comment by jklenzing** [comment]
Assumptions currently made at 
https://github.com/pysat/pysat/blob/74f19f68346a54b999497155cabe083a5cdc3e9b/pysat/_instrument.py#L1032-L1035

Need to decide if existing behaviour needs to be maintained for other use cases.

**Comment by jklenzing** [comment]
Pinging @rstoneback and @aburrell.  We need to decide what the preferred behaviour should be here.

**Comment by jklenzing** [comment]
Should we assume that single variables are loaded as coords?

**Comment by rstoneback** [comment]
> Assumptions currently made at
> 
> https://github.com/pysat/pysat/blob/74f19f68346a54b999497155cabe083a5cdc3e9b/pysat/_instrument.py#L1032-L1035
> 
> Need to decide if existing behaviour needs to be maintained for other use cases.

Yeah, as you found, a single number assignment was broadcasted along time, similar to the behavior in pandas. A desire to store a single number wasn't really considered at the time. The broadcasting was also thinking more along 'variables' than 'coordinates', hence the fixed use of the epoch coordinate. 

At minimum, the code should check if `key` already exists in the xarray. If so, use existing coordinate structure. If not, or epoch is only coordinate, continue with broadcast over epoch. This change will fix the bug and keep backwards compatibility for existing code.

xarray data assignment is more complicated than our interface, in general. I don't think it is a good idea to make further assumptions on coordinates. If there is doubt, make the user specify via the attached xarray object.

**Comment by aburrell** [comment]
> At minimum, the code should check if key already exists in the xarray. If so, use existing coordinate structure. If not, or epoch is only coordinate, continue with broadcast over epoch. This change will fix the bug and keep backwards compatibility for existing code.
> 
> xarray data assignment is more complicated than our interface, in general. I don't think it is a good idea to make further assumptions on coordinates. If there is doubt, make the user specify via the attached xarray object.

I agree with @rstoneback.  I think that will result in the second behaviour @jklenzing made as an example, when coordinates are desired.

**Comment by jklenzing** [comment]
I think so, @aburrell.  I'm leaning toward dropping variables into the coords if there is no dependence on the epoch.  This would be more clear.

**Comment by rstoneback** [comment]
I think setting data via pysat should have as much consistency as possible across the various data types, including future data-types. To me, this suggests we should make setting new data as pandas like as possible by default. As in new data is presumed to depend upon epoch unless the user specifies otherwise. Existing data keeps format.

Long term, I think it is more confusing if
`inst[new_assignment] = 1.0`
does different things depending upon the underlying data format.

**Comment by aburrell** [comment]
> this suggests we should make setting new data as pandas like as possible by default (@rstoneback)

This is something we always do, since time is a required dimension.  However, it doesn't make sense to have something depend on time and pad it out when it isn't called for.  That only slows down processing.

>  I'm leaning toward dropping variables into the coords if there is no dependence on the epoch. (@jklenzing)

This makes sense, and is what I do for many of the ground-based data sets (e.g., ISR radar location).

**Comment by jklenzing** [comment]
The linked commands above are only activated for xarray.  pandas behaviour will be maintained.

**Comment by rstoneback** [comment]
> The linked commands above are only activated for xarray. pandas behaviour will be maintained.

I understand, the comments were directed towards the xarray code.

**Comment by jklenzing** [comment]
Closing with merge of #1071
