### ISSUE TITLE
BUG: `io.inst_to_netcdf` does not create custom epochs for xarray objects

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#991]
**Describe the bug**
If `io.inst_to_netcdf` is run on a pandas instrument, the custom epoch will be created.  This behaviour is not maintained for xarray objects.  

**To Reproduce**
```
import pysat
inst = pysat.Instrument('pysat', 'testing2d_xarray')
inst.load(2009, 1)

# Save data to netcdf
fname = 'test_file.nc'
pysat.utils.io.inst_to_netcdf(inst, fname, epoch_name='penguin')

# Load data with custom 
data, meta = pysat.utils.io.load_netcdf('test_file.nc', pandas_format=False, epoch_name='penguin')
data

# Check for custom epoch
'penguin' in data.variables
```

**Expected behavior**
Should behave similarly to pandas.  Requires assumptions about time, which may need to be re-evaluated since xarray has more indices than just time, and may not have a time for some objects.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Max OS X
 - python 3.8.11

**Additional context**
see #984

**Comment by rstoneback** [comment]
Support for using supplied epoch name is in #983

**Comment by jklenzing** [comment]
I've added todo statements as part of #984.
