### ISSUE TITLE
Update standards for pysat.logger

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#997]
**Is your feature request related to a problem? Please describe.**
Way back with testing and reloading libraries I found that using `pysat.logger. ...` was the most robust for reloads of pysat.
Current documentation has ```logger = pysat.logger``` which sometimes goes wonky. It was an intermittent problem.

**Describe the solution you'd like**
Adopt pysat.logger

**Describe alternatives you've considered**
Could leave as is, the unit tests where I found the problem still exist but the suite passes.....  Could be fine, as is, or could be going through the process may only help in some limited situations.

**Additional context**
🙈

**Comment by jklenzing** [comment]
My general preference would be to just use `pysat.logger` when needed rather than importing multiple loggers.

**Comment by jklenzing** [comment]
I've noticed some instances of `logger = logging.getLogger(__name__)`, which I think grabs the default logger.  Not sure if this would potentially grab other loggers as well.

**Comment by rstoneback** [comment]
> I've noticed some instances of `logger = logging.getLogger(__name__)`, which I think grabs the default logger. Not sure if this would potentially grab other loggers as well.

That should be at like the init level. Supposed to help with submodules having logging tied to importing module.

**Comment by jklenzing** [comment]
Closing with merge of #1038
