### ISSUE TITLE
Consider adding tests for loading more than one day

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#998]
**Is your feature request related to a problem? Please describe.**
Some Instruments, like SAMI, may have custom support for loading multiple days. Checking through the tests it doesn't look like multi day loading is tested.

**Describe the solution you'd like**
Test loading two days worth of data. 

**Describe alternatives you've considered**
Force Instruments that have custom code to implement their own testing.

**Additional context**
Might require changes to _test_dates and other things. Likely not as simple as, "Let's add another test."

**Comment by aburrell** [comment]
Addressed in PR #1162
